/**
 * النصوص العربية. تعكس بنية مفاتيح `tr.ts` واحدا لواحد؛ المفتاح
 * الناقص يعود إلى التركية، واختبار التطابق
 * (`__tests__/ceviri-tamlik.test.ts`) يلتقط أي انحراف.
 */
export default {
  // HUKUKI EKRANLAR (i18n E asamasi, 2026-09-13): basliklar ve
  // "Turkce metin esastir" notu. Belgelerin kendisi lib/hukuki/ altinda.
  hukuki: {
    gizlilikBaslik: 'إشعار الخصوصية',
    kosullarBaslik: 'شروط الاستخدام',
    sonGuncelleme: 'آخر تحديث: {{tarih}}',
    ustunlukNotu: 'النص الملزم لهذه الوثيقة هو النسخة التركية؛ وهذه الترجمة لأغراض الاطلاع فقط.',
  },

  ortak: {
    devam: 'متابعة',
    iptal: 'إلغاء',
    tumunuSec: 'تحديد الكل',
    temizle: 'مسح',
    kaydet: 'حفظ',
    tekrarDene: 'حاول مجددا',
    yukleniyor: 'جارٍ التحميل…',
    birSorunOldu: 'حدث خطأ ما.',
    agYok: 'لا يوجد اتصال بالإنترنت، حاول مجددا',
    gonder: 'إرسال',
    gonderiliyor: 'جارٍ الإرسال…',
    tamam: 'تم',
    sira: 'المرتبة {{sira}}',
    sil: 'حذف',
    vazgec: 'إلغاء',
    geri: 'رجوع',
    kapat: 'إغلاق',
    ara: 'بحث',
    sonucYok: 'لا توجد نتائج.',
  },
  karsilama: {
    baslik: 'اعرف من حولك، ',
    baslikVurgu: 'واستكشف.',
    aciklama: 'سجّل حضورك، وتعرّف على أشخاص جدد.\nاكتشف الأماكن الرائجة من حولك.',
    kisiSayisi: '{{sayi}} أشخاص',
    disarida: '{{sayi}} أشخاص بالخارج قربك',
    turKafe: 'مقهى',
    turRestoran: 'مطعم',
    turBar: 'بار',
    adim1Baslik: 'سجّل حضورك',
    adim1Aciklama: 'كن مرئيا في المكان الذي أنت فيه',
    adim2Baslik: 'من حولك',
    adim2Aciklama: 'اكتشف الأشخاص في المكان نفسه',
    adim3Baslik: 'دردش',
    adim3Aciklama: 'تعرّف على أشخاص جدد',
    adim4Baslik: 'اكتشف الأماكن الرائجة',
    adim4Aciklama: 'شاهد الأماكن الرائجة في مدينتك',
    hesapOlustur: 'إنشاء حساب',
    hesabinVarMi: 'لديك حساب بالفعل؟',
    girisYap: 'تسجيل الدخول',
    haritaAtfi: 'بيانات الخريطة © مساهمو OpenStreetMap',
  },
  kayit: {
    baslik: 'ابدأ ببريدك الإلكتروني',
    epostaEtiket: 'البريد الإلكتروني',
    epostaYerTutucu: 'name@example.com',
    devam: 'متابعة',
    veya: 'أو',
    appleIle: 'المتابعة عبر Apple',
    googleIle: 'المتابعة عبر Google',
    hataEposta: 'أدخل بريدا إلكترونيا صالحا.',
    hataEpostaKayitli: 'يوجد حساب بهذا البريد بالفعل. يمكنك تسجيل الدخول بكلمة مرورك.',
    hataSaglayiciKapali: 'طريقة الدخول هذه غير متاحة حاليا. يمكنك المتابعة ببريدك الإلكتروني.',
    telefonEtiket: 'رقم الهاتف',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'إرسال الرمز',
    gonderiliyor: 'جارٍ الإرسال…',
    zatenHesap: 'لديك حساب بالفعل؟',
    girisYap: 'تسجيل الدخول',
    hataTelefon: 'أدخل رقم هاتف صالحا.',
    hataZatenKayitli: 'يوجد حساب بهذا الرقم بالفعل. يمكنك تسجيل الدخول بكلمة مرورك.',
  },
  profilOlustur: {
    baslik: 'إنشاء حساب',
    adYerTutucu: 'اسمك الكامل',
    adHata: 'أدخل اسمك الكامل.',
    dogumEtiket: 'تاريخ الميلاد',
    dogumSec: 'اليوم / الشهر / السنة',
    dogumHataGecersiz: 'اختر تاريخ ميلادك.',
    dogumHataYas: 'يجب أن يكون عمرك 18 عاما على الأقل لاستخدام Slooin.',
    tarihGun: 'اليوم',
    tarihAy: 'الشهر',
    tarihYil: 'السنة',
    tarihTamam: 'تم',
    aylar: {
      1: 'يناير',
      2: 'فبراير',
      3: 'مارس',
      4: 'أبريل',
      5: 'مايو',
      6: 'يونيو',
      7: 'يوليو',
      8: 'أغسطس',
      9: 'سبتمبر',
      10: 'أكتوبر',
      11: 'نوفمبر',
      12: 'ديسمبر',
    },
    kullaniciAdiYerTutucu: 'اسم المستخدم',
    kullaniciAdiIpucu: 'اسم المستخدم لا يطابق الصيغة المطلوبة.',
    kullaniciAdiKontrol: 'جارٍ التحقق…',
    kullaniciAdiMusait: 'اسم المستخدم هذا متاح.',
    kullaniciAdiAlinmis: 'اسم المستخدم هذا مأخوذ، جرّب غيره.',
    sifreEtiket: 'كلمة المرور',
    sifreYerTutucu: '{{adet}} أحرف على الأقل',
    tekrarEtiket: 'تكرار كلمة المرور',
    tekrarYerTutucu: 'كلمة المرور نفسها مرة أخرى',
    sifrelerFarkli: 'كلمتا المرور غير متطابقتين بعد.',
    sifreGoster: 'إظهار كلمة المرور',
    sifreGizle: 'إخفاء كلمة المرور',
    hataSifreKisa: 'يجب أن تتكون كلمة المرور من {{adet}} أحرف على الأقل.',
    hataSifreUyusmuyor: 'كلمتا المرور غير متطابقتين. راجعهما.',
    adimSayaci: 'الخطوة {{simdiki}} / {{toplam}}',
    adim1Baslik: 'دعنا نتعرف عليك',
    adim1Aciklama: 'يظهر اسمك في ملفك الشخصي. تاريخ ميلادك لا يُعرض لأحد أبدا.',
    adEtiket: 'الاسم الكامل',
    adOrnek: 'مثال: سارة أحمد',
    yasNotu: 'Slooin للأعمار 18 فما فوق.',
    adim2Baslik: 'اختر اسم المستخدم',
    adim2Aciklama: 'من 3 إلى 20 حرفا؛ قد يحتوي على أحرف لاتينية صغيرة وأرقام ونقاط وشرطات سفلية.',
    kullaniciAdiEtiket: 'اسم المستخدم الخاص بك',
    adim3Baslik: 'حدد كلمة مرورك',
    adim3Aciklama: 'ستسجل الدخول إلى حسابك بكلمة المرور هذه.',
    sifreUygun: 'كلمة المرور طويلة بما يكفي.',
    sifrelerAyni: 'كلمتا المرور متطابقتان.',
    devam: 'متابعة',
    sozlesmeNotuOn: 'بإنشاء حساب فإنك تؤكد قبولك ',
    sozlesmeKosullar: 'شروط الاستخدام',
    sozlesmeNotuOrta: ' وأنك قرأت ',
    sozlesmeGizlilik: 'سياسة الخصوصية',
    sozlesmeNotuSon: '.',
    gonder: 'إنشاء حساب',
    gonderiliyor: 'جارٍ الإنشاء…',
    oturumDustu: 'انتهت جلستك، سجّل الدخول مجددا.',
    beklenmeyenHata: 'حدث خطأ غير متوقع.',
  },
  bildirimler: {
    baslik: 'الإشعارات',
    arkadaslikBolumu: 'طلبات الصداقة',
    etiketBolumu: 'طلبات الإشارة',
    arkadaslikMetni: 'يريد أن يكون صديقك.',
    etiketMetni: 'يريد الإشارة إليك في تسجيل حضور في {{mekan}}.',
    kabul: 'قبول',
    onayla: 'موافقة',
    reddet: 'رفض',
    bosBaslik: 'لا جديد',
    bosAciklama: 'تظهر هنا طلبات الصداقة والأشخاص الذين يريدون الإشارة إليك.',
  },
  kisiler: {
    baslik: 'البحث عن أشخاص',
    yerTutucu: 'اسم المستخدم أو الاسم',
    enAzIki: 'اكتب حرفين على الأقل.',
    bulunamadi: 'لم يُعثر على أحد.',
    ipucu: 'يمكنك البحث عن شخص باسم المستخدم أو الاسم.',
  },
  baglar: {
    baslik: 'الأصدقاء',
    arkadasliktanCikar: 'إزالة الصديق',
    bosArkadas: 'لا أصدقاء بعد',
    engelle: 'حظر',
  },
  mesajlar: {
    baslik: 'الرسائل',
    bosBaslik: 'لا محادثات بعد',
    silinmisKullanici: 'مستخدم محذوف',
    gizle: 'إخفاء',
    istekler: 'الطلبات',
    istekRozeti: 'طلب',
  },
  mesajIstekleri: {
    baslik: 'الطلبات',
    aciklama: 'تنتظر هنا الرسائل من أشخاص ليسوا أصدقاءك. إذا رددت، تنتقل المحادثة إلى الرسائل.',
    bosBaslik: 'لا طلبات معلقة',
    bosAciklama: 'إذا راسلك شخص ليس صديقك، سترى الرسالة هنا.',
    kabul: 'قبول',
    reddet: 'رفض',
    geri: 'الرسائل',
  },
  hesabiSil: {
    baslik: 'حذف حسابك',
    uyari: 'لا يمكن التراجع عن هذا. إذا أردت العودة، فستحتاج إلى إنشاء حساب جديد من الصفر.',
    ipucu: 'يُحذف ملفك الشخصي وذكرياتك وصداقاتك وقائمة محادثاتك. تبقى رسائلك في سجل الطرف الآخر، لكن اسمك لن يظهر بعد الآن.',
    dondur: 'أفضّل تجميد حسابي',
    parolaEtiket: 'أدخل كلمة مرورك للتأكيد',
    parolaYerTutucu: 'كلمة مرورك',
    parolaGerekli: 'أدخل كلمة مرورك للتأكيد.',
    sil: 'حذف حسابي نهائيا',
  },
  sohbet: {
    baslik: 'محادثة',
    istekSeridi: 'هذا طلب رسالة. إذا رددت، تنتقل المحادثة إلى الرسائل.',
    kabulEt: 'قبول',
    reddet: 'رفض',
    mesajYok: 'لا رسائل بعد',
    yerTutucu: 'اكتب رسالة...',
    kapaliKapi: 'لا يمكنك مراسلة هذا الشخص حاليا.',
  },
  etkilesim: {
    profiliGor: 'عرض ملف {{ad}}',
    begen: 'إعجاب',
    begeniyiKaldir: 'إلغاء الإعجاب',
    yorumlar: 'التعليقات',
    yorumSayisi: '{{sayi}} تعليقات',
    yorumYaz: 'اكتب تعليقا…',
    gonder: 'إرسال',
    paylas: 'مشاركة',
    yorumSil: 'حذف التعليق',
    yorumSilOnay: 'حذف هذا التعليق؟',
    yorumSikayet: 'إبلاغ',
    yorumSikayetOnay: 'الإبلاغ عن هذا التعليق؟ يُخفى التعليق المُبلّغ عنه فورا ويراجعه فريق الإشراف.',
    yorumSikayetEdildi: 'تم استلام بلاغك وإخفاء التعليق.',
    bosYorumBaslik: 'لا تعليقات بعد',
    bosYorumAciklama: 'يمكنك كتابة الأول.',
    silinmisKullanici: 'مستخدم محذوف',
  },
  anaSayfa: {
    aramaYerTutucu: 'بحث',
    suAnDisarida: 'بالخارج الآن',
    disaridaSayi: '{{sayi}} أشخاص',
    disaridaDiger: 'آخرون',
    disaridaErisim: '{{ad}}، في {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'هنا الآن',
    bosBaslik: 'خلاصتك فارغة',
    bosAciklama: 'سجّل حضورك في مكان ما أو كوّن صداقات؛ ستظهر تسجيلات حضورهم هنا.',
    kesfet: 'استكشاف الأماكن',
    azOnce: 'الآن',
    dakika: 'قبل {{sayi}} د',
    saat: 'قبل {{sayi}} س',
    gun: 'قبل {{sayi}} ي',
    silOnay: 'حذف تسجيل الحضور هذا نهائيا؟',
    silAciklama: 'يُحذف تسجيل الحضور وملاحظته وصورته نهائيا. ولن يبقى في ذكرياتك أيضا؛ لا يمكن التراجع عن هذا.',
    silAriza: 'تعذّر حذف تسجيل الحضور.',
    haritadaGor: 'عرض {{ad}} على الخريطة',
    secenekler: 'خيارات المنشور',
    fotografiBuyut: 'تكبير الصورة',
    duzenle: 'تعديل',
    arkadasEtiketle: 'الإشارة إلى صديق',
    duzenleBaslik: 'تعديل المنشور',
    notEtiketi: 'ملاحظة',
    notYerTutucu: 'أضف ملاحظة',
    etiketlenenler: 'المُشار إليهم',
    etiketiKaldirEtiketi: 'إزالة الإشارة إلى {{ad}}',
    duzenleAriza: 'تعذّر تحديث المنشور.',
  },
  kullanici: {
    bulunamadi: 'لم يُعثر على هذا الملف',
    takipEt: 'إضافة صديق',
    istekBeklemede: 'قيد الانتظار',
    istegiGeriCek: 'سحب الطلب',
    bagiKopar: 'إزالة الصديق',
    gelenIstekAciklama: 'إذا قبلت، فسيرى كل منكما تسجيلات حضور الآخر ويمكنكما التراسل.',
    kabulEt: 'قبول',
    reddet: 'رفض',
    anilar: 'الذكريات',
    enSik: 'الأكثر زيارة',
    aniYok: 'لا ذكريات بعد',
    profilKapali: 'هذا الملف خاص',
    profilKapaliAciklama: 'يجب أن تكونا صديقين لرؤية الذكريات.',
    yerYok: 'لا أماكن بعد',
    sikayetEt: 'إبلاغ',
    engelle: 'حظر',
    engelleOnayi: 'إذا حظرته، فلن يرى أحدكما الآخر في أي مكان وستُحذف كل الرسائل بينكما نهائيا. لا يمكن التراجع عن هذا.',
    engelleEvet: 'نعم، حظر',
    vazgec: 'إلغاء',
    geri: 'رجوع',
    mesajYaz: 'مراسلة',
    arkadassin: 'أصدقاء',
    paylas: 'مشاركة الملف الشخصي',
    paylasMetni: '{{ad}} على Slooin: {{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'تعديل الملف الشخصي',
    adEtiket: 'الاسم الكامل',
    adYerTutucu: 'اسمك الكامل',
    adHata: 'أدخل اسمك الكامل.',
    kullaniciAdiEtiket: 'اسم المستخدم',
    biyografiEtiket: 'نبذة',
    biyografiYerTutucu: 'أخبرنا قليلا عن نفسك',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'اسم المستخدم الخاص بك',
    instagramIpucu: 'يمكنك لصق رابط أيضا. لا يتم التحقق منه؛ يظهر كرابط في ملفك.',
    bolgeEtiket: 'مكان إقامتك',
    bolgeSecilmedi: 'غير محدد',
    bolgeIpucu: 'اختياري. إذا اخترت واحدا، فسيظهر في ملفك.',
    bolgeIlSec: 'اختر المحافظة',
    bolgeIlceSec: 'اختر المنطقة',
    bolgeKaldir: 'إزالة المنطقة',
    instagramHata: 'يتكون اسم مستخدم Instagram من أحرف وأرقام ونقاط وشرطات سفلية؛ ولا يمكن أن يبدأ أو ينتهي بنقطة.',
    kaydediliyor: 'جارٍ الحفظ…',
    kaydedildi: 'تم تحديث ملفك الشخصي.',
  },
  ayarlar: {
    baslik: 'الإعدادات',
    geri: 'رجوع',
    profilGizli: 'ملف خاص',
    profilGizliAciklama: 'عند التفعيل، يرى أصدقاؤك فقط ذكرياتك وتسجيلات حضورك. يبقى اسمك واسم المستخدم وصورتك عامة ليتمكن الآخرون من إيجادك وإرسال طلب صداقة.',
    verilerimiIndir: 'تنزيل بياناتي',
    verilerimiIndirHazirlaniyor: 'جارٍ التحضير…',
    verilerimiIndirHata: 'تعذّر تحضير البيانات. حاول مجددا.',
    gizlilikMetni: 'سياسة الخصوصية',
    bolumGorunurluk: 'إعدادات الخصوصية',
    aniGorunurlugu: 'ذكرياتي السابقة',
    etiketOnayi: 'اسألني قبل الإشارة إليّ',
    etiketOnayiAciklama: 'عند الإيقاف، يمكن لأصدقائك الإشارة إليك مباشرة. عند التفعيل، تُسأل أولا؛ ولا يرى أحد الإشارة حتى توافق.',
    aramadaGorun: 'إظهاري في البحث',
    aramadaGorunEtiket: 'الظهور في البحث',
    bolumKisiler: 'الأشخاص',
    engellenenler: 'المحظورون',
    bolumHesapIslemleri: 'الحساب',
    dondur: 'تجميد حسابي',
    dondurAciklama: 'لا تُحذف بياناتك. يُعاد تفعيل حسابك تلقائيا عند تسجيل الدخول التالي.',
    dondurEvet: 'نعم، تجميد',
    vazgec: 'إلغاء',
    hesabiSil: 'حذف حسابي',
    cikisYap: 'تسجيل الخروج',
    aniHerkeseAcik: 'الجميع',
    aniTakipcilerim: 'متابعيّ فقط',
    aniKimse: 'لا أحد',
    secilmedi: 'غير محدد',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'اسم مستخدم جديد',
    sonrakiDegisim: 'يمكنك تغييره مجددا في: {{tarih}}',
  },
  aniGorunurlugu: {
    baslik: 'ذكرياتي السابقة',
    geri: 'رجوع',
    aciklama: 'ينطبق هذا الاختيار على كل ذكرياتك، لكن الذكريات الناتجة عن تسجيل حضور مخفي لا تتأثر وتبقى خاصة.',
  },
  engellenenler: {
    baslik: 'المحظورون',
    engeliKaldir: 'إلغاء الحظر',
    bosBaslik: 'لم تحظر أحدا',
    bosAciklama: 'إذا حظرت شخصا، فسيظهر هنا ويمكنك التراجع من هنا.',
    geri: 'رجوع',
  },
  profil: {
    yerSayisi: 'الأماكن',
    duzenle: 'تعديل الملف الشخصي',
    paylas: 'مشاركة',
    paylasilamadi: 'تعذّر فتح المشاركة على هذا الجهاز.',
    sekmeAnilar: 'الذكريات',
    sekmeYerler: 'الأكثر زيارة',
    sekmeFotograflar: 'الصور',
    fotografSayisi: 'الصور',
    bosFotografBaslik: 'لا صور بعد',
    bosFotografAciklama: 'إذا أضفت صورا عند تسجيل الحضور، فستُجمع كلها هنا.',
    bosArkadasBaslik: 'لا أصدقاء بعد',
    kezSayisi: '{{sayi}} مرات',
    bosYerBaslik: 'لم تذهب إلى أي مكان بعد',
    bosYerAciklama: 'كلما سجلت حضورك، تُرتّب هنا الأماكن التي تزورها أكثر.',
    ayarlar: 'الإعدادات',
    fotografEkle: 'إضافة صورة الملف',
    fotografiBuyut: 'تكبير صورة الملف',
    fotografKaldir: 'إزالة الصورة',
    fotografKaldirOnay: 'إزالة صورتك؟',
    kapat: 'إغلاق',
    aniSayisi: 'الذكريات',
    bagSayisi: 'الأصدقاء',
    canliEtiket: 'أنت هنا الآن',
    ayril: 'مغادرة',
    canliSil: 'حذف',
    canliSilOnay: 'حذف تسجيل الحضور هذا نهائيا؟ لن يبقى في ذكرياتك أيضا.',
    bosCanliBaslik: 'لست في أي مكان الآن',
    bosCanliAciklama: 'سجّل حضورك حيث أنت وشاهد من هناك في هذه اللحظة.',
    checkInYap: 'تسجيل الحضور في مكان ما',
    anilarBaslik: 'الذكريات',
    bosAniBaslik: 'لا ذكريات بعد',
    bosAniAciklama: 'تبقى تسجيلات حضورك هنا كذكريات.',
    profilYok: 'ملفك الشخصي غير جاهز بعد',
    profilYokAciklama: 'حدد اسمك واسم المستخدم ثم تابع من هنا.',
    profilOlustur: 'إنشاء ملفك الشخصي',
  },
  dogrula: {
    geri: 'رجوع',
    baslik: 'تحقق من بريدك',
    aciklama: 'أرسلنا رمزا من 6 أرقام إلى {{eposta}}.',
    kodEtiketi: 'رمز التحقق',
    gonder: 'تحقق',
    gonderiliyor: 'جارٍ التحقق…',
    kodGelmedi: 'لم يصلك الرمز؟',
    spamNotu: 'إذا لم يكن في صندوق الوارد، فتحقق من مجلد الرسائل غير المرغوب فيها أيضا.',
    tekrarGonder: 'إعادة الإرسال',
    tekrarBekle: 'يمكنك إعادة الإرسال بعد {{saniye}} ث',
    tekrarGonderildi: 'تم إرسال رمز جديد.',
    hakKalmadi: 'طُلبت رموز كثيرة جدا لهذا العنوان. يمكنك المحاولة مجددا بعد ساعة.',
    hataEksik: 'أدخل الرمز كاملا.',
    zatenKayitliBaslik: 'يوجد حساب بهذا العنوان بالفعل',
    zatenKayitliAciklama: 'تم إنشاء حساب بـ {{eposta}} بالفعل. يمكنك تسجيل الدخول بكلمة مرورك.',
    girisYap: 'تسجيل الدخول',
    baskaNumara: 'المتابعة بعنوان آخر',
  },
  altGezinme: {
    anaSayfa: 'الرئيسية',
    bildirimler: 'الإشعارات',
    mesajlar: 'الرسائل',
    profil: 'الملف',
  },
  arkadasSecici: {
    baslik: 'أشر إلى أصدقائك',
    bos: 'ليس لديك أصدقاء بعد. عندما ترسل طلب صداقة ويُقبل، سيظهرون هنا ويمكنك الإشارة إليهم في تسجيلات حضورك.',
    tamamSayili: 'تم ({{sayi}})',
  },
  harita: {
    cevre: 'الأماكن من حولك',
    kisiBurada: '{{ad}}، {{sayi}} أشخاص هنا',
    buMekan: 'هذا المكان، {{durum}}',
    buradasin: 'أنت هنا',
  },
  sikayet: {
    baslik: 'إبلاغ',
    sebepSec: 'اختر سببا',
    alindi: 'تم استلام بلاغك',
    tesekkur: 'شكرا لإخبارنا.',
    mesajBaglami: 'أثناء المراجعة، تُفتح الرسائل المحيطة بهذه الرسالة للإشراف أيضا.',
    aciklamaYerTutucu: 'هل تريد إضافة شيء؟',
    sebepler: {
      taciz: 'تحرش أو تنمر',
      uygunsuz_icerik: 'محتوى غير لائق',
      sahte_hesap: 'حساب مزيف',
      spam: 'رسائل مزعجة أو إعلانات',
      diger: 'أخرى',
    },
  },
  hesapDurumu: {
    askida: 'حسابك موقوف',
    yasakli: 'تم إغلاق حسابك نهائيا',
    sebep: 'السبب: {{sebep}}',
    bitis: 'ينتهي: {{tarih}}',
    ipucu: 'خلال هذه الفترة لا يرى الآخرون ملفك ولا يمكنك نشر محتوى جديد. لم تُحذف بياناتك.',
    yenile: 'تحديث',
    cikisYapilamadi: 'تعذّر تسجيل الخروج',
  },
  checkIn: {
    baslik: 'تسجيل حضور جديد',
    notYerTutucu: 'أضف ملاحظة (اختياري)',
    ilkUyariBaslik: 'ماذا يشارك تسجيل الحضور هذا؟',
    ilkUyariMetin: 'عندما تسجل حضورك، يصبح المكان الذي أنت فيه وملاحظتك (إن وجدت) مرئيين لأصدقائك. ينتهي من تلقاء نفسه عند انتهاء تسجيل الحضور أو حين تقول "غادرت". إذا أردت، يمكنك جعل تسجيل الحضور هذا مخفيا والاحتفاظ به في ملفك فقط.',
    anladim: 'فهمت',
    gizliYap: 'اجعله مخفيا',
    arkadasEkle: 'إضافة أصدقاء (اختياري)',
    arkadasEkleSecili: 'إضافة أصدقاء ({{sayi}} محدد)',
    etiketiKaldir: 'إزالة الإشارة إلى {{ad}}',
    fotografEkle: 'إضافة صورة (اختياري)',
    fotografDegistir: 'تغيير الصورة',
    fotografCek: 'التقاط صورة',
    galeridenSec: 'اختيار من المعرض',
    kameraIzni: 'يلزم إذن الكاميرا لالتقاط صورة.',
    fotografYuklenemedi: 'تعذّر رفع الصورة؛ سُجّل حضورك مع ملاحظتك',
    etiketlenemedi: 'سُجّل حضورك، لكن تعذّرت الإشارة إلى أصدقائك.',
    gonder: 'تسجيل الحضور',
    gonderiliyor: 'جارٍ تسجيل الحضور...',
  },
  mekanDuzenle: {
    baslik: 'تصحيح المعلومات',
    aciklama: 'هل هناك خطأ؟ يذهب تصحيحك إلى مشرف؛ وبعد الموافقة يُحدَّث للجميع.',
    gonderildiBaslik: 'تم إرسال طلبك',
    gonderildiMetin: 'ستُحدَّث معلومات المكان عندما يراجعها مشرف ويوافق عليها.',
    bekleyenBaslik: 'لديك طلب معلق',
    bekleyenMetin: 'الطلب الذي أرسلته لهذا المكان لا يزال قيد المراجعة. عند البت فيه يمكنك إرسال تصحيح جديد.',
    adEtiket: 'اسم المكان',
    adYerTutucu: 'اسم المكان',
    mahalle: 'الحي',
    mahalleYerTutucu: 'مثال: Alaaddinbey',
    adres: 'العنوان',
    adresYerTutucu: 'الشارع، الرقم',
    il: 'المحافظة',
    ilYerTutucu: 'Bursa',
    ilce: 'المنطقة',
    ilceYerTutucu: 'Nilüfer',
    tur: 'النوع',
    kapakFotografi: 'صورة الغلاف',
    fotografiKaldir: 'إزالة الصورة',
    fotografEkle: 'إضافة صورة',
    fotografSecilemedi: 'تعذّر اختيار الصورة.',
    galeriIzni: 'يلزم إذن الصور للاختيار من المعرض.',
    oturumYok: 'لم يُعثر على الجلسة',
    zatenKapali: 'هذا المكان مُعلَّم بالفعل كمغلق نهائيا.',
    kapaliBaslik: 'هذا المكان مغلق نهائيا',
    kapaliAciklama: 'عند الموافقة، يُزال هذا المكان من القوائم والبحث. لا تُحذف تسجيلات الحضور التي تمت هنا.',
    onceDegistir: 'غيّر شيئا أولا.',
    talebiGonder: 'إرسال الطلب',
  },
  mekanEkle: {
    baslik: 'إضافة مكان جديد',
    adYerTutucu: 'اسم المكان',
    turuSec: 'اختر نوعا',
    adresYerTutucu: 'العنوان (اختياري)',
    adresSoru: 'هل هذا العنوان صحيح؟',
    adresAciklama: 'تم العثور عليه من موقعك. إذا كان خاطئا، يمكنك تعديل الحقل أعلاه.',
    dogru: 'صحيح',
    benzerBaslik: 'هل تقصد أحد هذه؟',
    konumAlinamadi: 'تعذّر الحصول على موقعك، حاول مجددا',
    adVeTurGerekli: 'اسم المكان ونوعه مطلوبان',
    ekle: 'إضافة',
    ekleniyor: 'جارٍ الإضافة...',
  },
  turGruplari: {
    'Yeme içme': 'طعام وشراب',
    Gece: 'الحياة الليلية',
    'Açık alan': 'في الهواء الطلق',
    Kültür: 'ثقافة',
    Spor: 'رياضة',
    Alışveriş: 'تسوق',
    Diğer: 'أخرى',
  },
  turler: {
    Kafe: 'مقهى',
    Kahveci: 'محل قهوة',
    'Çay evi': 'بيت شاي',
    Restoran: 'مطعم',
    Lokanta: 'مطعم شعبي',
    'Türk mutfağı': 'مطبخ تركي',
    Kebapçı: 'مطعم كباب',
    'Balık restoranı': 'مطعم أسماك',
    Ocakbaşı: 'مشويات',
    'Kahvaltı salonu': 'صالة فطور',
    Fırın: 'مخبز',
    'Fast food': 'وجبات سريعة',
    Burgerci: 'مطعم برغر',
    Pizzacı: 'بيتزا',
    Tatlıcı: 'محل حلويات',
    Dondurmacı: 'محل آيس كريم',
    Bar: 'بار',
    Pub: 'حانة',
    'Gece kulübü': 'نادٍ ليلي',
    Meyhane: 'خمارة',
    'Nargile kafe': 'مقهى أرجيلة',
    'Kokteyl barı': 'بار كوكتيل',
    Park: 'حديقة عامة',
    'Halk bahçesi': 'حديقة شعبية',
    'Doğal alan': 'منطقة طبيعية',
    Plaj: 'شاطئ',
    Meydan: 'ساحة',
    'Kamp alanı': 'مخيم',
    Göl: 'بحيرة',
    Müze: 'متحف',
    Sinema: 'سينما',
    Tiyatro: 'مسرح',
    'Sanat galerisi': 'معرض فني',
    Kütüphane: 'مكتبة عامة',
    'Tarihi yer': 'موقع تاريخي',
    'Konser salonu': 'قاعة حفلات',
    'Kültür merkezi': 'مركز ثقافي',
    'Spor salonu': 'صالة رياضية',
    Stadyum: 'ملعب',
    'Yüzme havuzu': 'مسبح',
    'Halı saha': 'ملعب كرة قدم',
    AVM: 'مركز تسوق',
    Market: 'سوبر ماركت',
    Bakkal: 'بقالة',
    'Giyim mağazası': 'متجر ملابس',
    Kitapçı: 'مكتبة',
    Kuyumcu: 'محل مجوهرات',
    Otel: 'فندق',
    Eczane: 'صيدلية',
    Hastane: 'مستشفى',
    Banka: 'بنك',
    Kuaför: 'صالون حلاقة',
    'Güzellik salonu': 'صالون تجميل',
    Üniversite: 'جامعة',
    'Canlı müzik': 'موسيقى حية',
  },
  kesfet: {
    baslik: 'تسجيل الحضور',
    harita: 'الخريطة',
    liste: 'القائمة',
    turSuzgeci: 'تصفية حسب النوع',
    turFiltresi: 'تصفية حسب النوع',
    turBulunamadi: 'لا أنواع لعرضها من حولك.',
    filtreyiKaldir: 'إزالة التصفية',
    tumunuSec: 'تحديد الكل',
    temizle: 'مسح',
    kaydet: 'حفظ',
    kaydetSayili: 'حفظ ({{sayi}})',
    tumu: 'الكل',
    sakin: 'هادئ',
    yogun: 'مزدحم',
    populer: 'رائج',
    yakinindakiMekanlar: 'الأماكن القريبة منك',
    sonuclar: 'النتائج',
    kisiBurada: '{{sayi}} أشخاص هنا',
    checkIn: 'تسجيل الحضور',
    konumuGor: 'عرض الموقع',
    checkInYap: 'سجّل حضورك هنا',
    mekanAra: 'البحث عن أماكن',
    kisi: '{{sayi}} أشخاص',
    taraniyor: 'جارٍ فحص ما حولك…',
    cevreGorunmuyor: 'لا نستطيع رؤية ما حولك',
    konumIzniAciklama: 'نحتاج إلى إذن الموقع لنعرض لك الأماكن القريبة. فعّله في إعدادات المتصفح وحاول مجددا.',
    konumuAc: 'فتح {{ad}}',
    konumuGorEtiketi: 'عرض {{ad}}',
    checkInEtiketi: 'تسجيل الحضور في {{ad}}',
    filtreyiKaldirEtiketi: 'إزالة تصفية {{tur}}',
    kisiBuradaEtiket: 'أشخاص هنا',
    suAnBuradasin: 'أنت هنا الآن',
    ayrildim: 'غادرت',
    araniyor: 'جارٍ البحث…',
    aramaBulunamadi: 'لم يُعثر على مكان لـ "{{arama}}". جرّب تغيير طريقة الكتابة.',
    sonucSayisi: '{{sayi}} نتائج',
    bosArama: 'لا نتائج لـ "{{arama}}" في هذه المحافظة.',
    bosFiltre: 'لا أماكن ضمن 500 م بهذه التصفية.',
    bosCevre: 'لا أماكن قريبة منك.',
    mekanEkle: 'لا تجد مكانا؟ أضفه',
    atif: 'بيانات الأماكن: Foursquare · الحي والمنطقة: © مساهمو OpenStreetMap',
  },
  checkInHaritasi: {
    geri: 'رجوع',
    haritaAcikla: 'اضغط على الخريطة للحصول على الاتجاهات',
    haritadaAc: 'الاتجاهات',
    secimBaslik: 'أي خريطة نفتح؟',
    appleHaritalar: 'خرائط Apple',
    googleHaritalar: 'خرائط Google',
    vazgec: 'إلغاء',
  },
  mekanSayfasi: {
    fotografEtiketi: 'صورة {{ad}}',
    menu: 'الخيارات',
    yolTarifi: 'الاتجاهات',
    buradaCheckIn: 'سجّل حضورك هنا',
    yaklas: 'اقترب لتسجيل الحضور · {{mesafe}}',
    buradasinAyril: 'أنت هنا · مغادرة',
    kapandi: 'هذا المكان مغلق نهائيا',
    kapandiAciklama: 'لم يعد بإمكانك تسجيل الحضور هنا ولا يظهر المكان في القوائم. تبقى ذكرياتك السابقة.',
    kisiBurada: 'أشخاص هنا',
    bugun: 'اليوم',
    haritadaGoster: 'عرض الموقع على الخريطة',
    checkInSayisi: '{{sayi}} تسجيلات حضور',
    kisiSayisi: '{{sayi}} أشخاص',
    ilcedekiYerler: 'الأماكن في {{ilce}}',
    siralamaYok: 'لا ترتيب',
    suAnBurada: 'هنا الآن',
    diger: 'آخرون',
    biri: 'شخص ما',
    suAn: 'الآن',
    liderlik: 'المتصدرون',
    sonCheckInler: 'الأحدث',
    liderlikBos: 'لا توجد تسجيلات حضور لعرضها هنا بعد.',
    sonBos: 'لا توجد تسجيلات حضور لعرضها هنا بعد.',
    fotograflar: 'الصور',
    fotografBos: 'لا صور هنا بعد.',
    fotografAc: 'تكبير الصورة',
    dahaFazlaFotograf: 'المزيد من الصور',
    puan: 'التقييم',
    puanlamaSayisi: '{{sayi}} تقييمات',
    puanYok: 'لا تقييم بعد',
    puanAzOy: 'يلزم 3 تقييمات على الأقل لإظهار درجة',
    puanKotu: 'سيئ',
    puanIyi: 'جيد',
    puanHarika: 'رائع',
    puanSoru: 'كيف وجدت هذا المكان؟',
    puanSart: 'سجّل حضورك هنا أولا لتقييمه.',
    puanGonder: 'إرسال',
    puanGuncelle: 'تحديث تقييمك',
    puanGonderiliyor: 'جارٍ الإرسال…',
    puanTesekkur: 'تم حفظ تقييمك.',
  },
  giris: {
    epostaYerTutucu: 'البريد الإلكتروني',
    sifreYerTutucu: 'كلمة المرور',
    gonder: 'تسجيل الدخول',
    gonderiliyor: 'جارٍ تسجيل الدخول…',
    kayitOl: 'إنشاء حساب جديد',
    hataEposta: 'أدخل بريدا إلكترونيا صالحا.',
    hataBos: 'أدخل بريدك الإلكتروني وكلمة المرور.',
    sifremiUnuttum: 'نسيت كلمة المرور؟',
  },
  sifreSifirla: {
    geri: 'رجوع',
    baslik: 'إعادة تعيين كلمة المرور',
    aciklama: 'أدخل بريد حسابك الإلكتروني وسنرسل لك رمزا من 6 أرقام.',
    epostaYerTutucu: 'البريد الإلكتروني',
    kodGonder: 'إرسال الرمز',
    gonderiliyor: 'جارٍ الإرسال…',
    hataEposta: 'أدخل بريدا إلكترونيا صالحا.',
    hataHesapYok: 'لم يُعثر على حساب بهذا البريد الإلكتروني.',
    kodBaslik: 'أدخل الرمز',
    kodAciklama: 'أرسلنا رمزا من 6 أرقام إلى {{eposta}}.',
    kodEtiketi: 'رمز التحقق',
    dogrula: 'تحقق',
    dogrulaniyor: 'جارٍ التحقق…',
    hataEksik: 'أدخل الرمز كاملا.',
    kodGelmedi: 'لم يصلك الرمز؟',
    spamNotu: 'إذا لم يكن في صندوق الوارد، فتحقق من مجلد الرسائل غير المرغوب فيها أيضا.',
    tekrarGonder: 'إعادة الإرسال',
    tekrarBekle: 'يمكنك إعادة الإرسال بعد {{saniye}} ث',
    tekrarGonderildi: 'تم إرسال رمز جديد.',
    hakKalmadi: 'طُلبت رموز كثيرة جدا لهذا العنوان. يمكنك المحاولة مجددا بعد ساعة.',
    yeniBaslik: 'حدد كلمة مرورك الجديدة',
    yeniAciklama: 'تم التحقق من الرمز. اختر الآن كلمة مرور جديدة.',
    sifreYerTutucu: 'كلمة المرور الجديدة ({{adet}} أحرف على الأقل)',
    sifreTekrarYerTutucu: 'كلمة المرور الجديدة (مرة أخرى)',
    kaydet: 'حفظ كلمة المرور',
    kaydediliyor: 'جارٍ الحفظ…',
    hataSifreKisa: 'يجب أن تتكون كلمة المرور من {{adet}} أحرف على الأقل.',
    hataSifreEslesmiyor: 'كلمتا المرور غير متطابقتين.',
  },
  hatalar: {
    genel: 'حدث خطأ ما. حاول مجددا بعد قليل.',
    kullaniciAdi30Gun: 'يمكنك تغيير اسم المستخدم مرة كل 30 يوما. بقي {{gun}} يوما.',
    vt: {
      aski_bitisi_gelecekte_olmali: 'يجب أن يكون انتهاء الإيقاف في المستقبل.',
      bir_moderatore_islem_uygulanamaz: 'لا يمكن تطبيق إجراء على مشرف.',
      bu_kisiye_su_an_mesaj_gonderemezsin: 'لا يمكنك مراسلة هذا الشخص حاليا.',
      bu_kullanici_adi_alinmis: 'اسم المستخدم هذا مأخوذ، جرّب غيره.',
      bu_kullanici_bulunamadi: 'لم يُعثر على هذا المستخدم.',
      bu_fotograf_sana_ait_degil: 'هذه الصورة ليست لك.',
      bu_il_listemizde_yok: 'هذه المحافظة ليست في قائمتنا.',
      bu_mekan_bulunamadi: 'لم يُعثر على هذا المكان.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'الطلب الذي أرسلته لهذا المكان لا يزال قيد المراجعة.',
      bu_mekan_kalici_olarak_kapandi: 'هذا المكان مغلق نهائيا.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'هذا المكان مُعلَّم بالفعل كمغلق.',
      bu_tur_listemizde_yok: 'هذا النوع ليس في قائمتنا.',
      en_az_bir_alan_doldurulmali: 'يجب تغيير معلومة واحدة على الأقل.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'بلغت الحد اليومي للتصحيحات (5). يمكنك المحاولة غدا.',
      hesabin_su_an_bu_islemi_yapamaz: 'لا يمكن لحسابك القيام بهذا حاليا.',
      bu_paylasim_bulunamadi: 'لم يُعثر على هذا المنشور.',
      not_en_fazla_500_karakter_olabilir: 'يمكن أن تتكون الملاحظة من 500 حرف كحد أقصى.',
      bu_mesaji_sikayet_edemezsin: 'لا يمكنك الإبلاغ عن هذه الرسالة.',
      bugunluk_istek_sinirina_ulastin: 'بلغت حد الطلبات لهذا اليوم.',
      check_in_bulunamadi: 'لم يُعثر على تسجيل الحضور.',
      cok_fazla_kimlik: 'أُرسلت معرّفات كثيرة جدا.',
      en_az_2_karakter_gerekli: 'اكتب حرفين على الأقل.',
      gecersiz_bulunurluk_degeri: 'قيمة توفر غير صالحة.',
      gecersiz_gorunurluk_degeri: 'قيمة ظهور غير صالحة.',
      gecersiz_platform: 'منصة غير صالحة.',
      gecersiz_sikayet_durumu: 'حالة بلاغ غير صالحة.',
      gecersiz_sikayet_hedefi: 'هدف بلاغ غير صالح.',
      gerekce_belirtilmeli: 'يجب ذكر سبب.',
      geri_cekilecek_istek_bulunamadi: 'لم يُعثر على طلب لسحبه.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'بلغت الحد اليومي لإضافة الأماكن (5). يمكنك المحاولة غدا.',
      hesabin_su_anda_kullanilamiyor: 'حسابك غير متاح حاليا.',
      hesabin_zaten_kullanilamaz_durumda: 'حسابك غير متاح بالفعل.',
      istegin_zaten_gonderilmis: 'تم إرسال طلبك بالفعل.',
      jeton_bos_olamaz: 'لا يمكن أن يكون رمز الإشعارات فارغا.',
      jeton_cok_uzun: 'رمز الإشعارات طويل جدا.',
      kendi_mesajini_sikayet_edemezsin: 'لا يمكنك الإبلاغ عن رسالتك.',
      kendine_islem_uygulayamazsin: 'لا يمكنك تطبيق إجراء على نفسك.',
      kendine_istek_gonderemezsin: 'لا يمكنك إرسال طلب إلى نفسك.',
      kendine_mesaj_gonderemezsin: 'لا يمكنك مراسلة نفسك.',
      kendini_engelleyemezsin: 'لا يمكنك حظر نفسك.',
      kendini_sikayet_edemezsin: 'لا يمكنك الإبلاغ عن نفسك.',
      kimlik_dogrulamasi_gerekli: 'يجب تسجيل الدخول لهذا.',
      konusma_bulunamadi: 'لم يُعثر على المحادثة.',
      kullanici_adi_kurallara_uymuyor: 'اسم المستخدم لا يتبع القواعد.',
      kullanici_belirtilmeli: 'يجب تحديد مستخدم.',
      mekan_bulunamadi: 'لم يُعثر على المكان.',
      gecersiz_puan: 'تقييم غير صالح.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'سجّل حضورك هنا أولا لتقييمه.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'أنت بعيد جدا عن المكان. لتسجيل الحضور يجب أن تكون ضمن نحو كيلومتر واحد.',
      mekana_yakin_olmalisin_200_m_icinde: 'لإضافة مكان يجب أن تكون ضمن نحو 200 متر منه.',
      mesaj_bos_olamaz: 'لا يمكن أن تكون الرسالة فارغة.',
      mesaj_bu_konusmada_bulunamadi: 'لم يُعثر على الرسالة في هذه المحادثة.',
      mesaj_cok_uzun: 'الرسالة طويلة جدا.',
      profil_bulunamadi: 'لم يُعثر على الملف.',
      sikayet_bulunamadi: 'لم يُعثر على البلاغ.',
      sikayet_sebebi_belirtilmeli: 'يجب ذكر سبب للبلاغ.',
      yanitlanacak_istek_bulunamadi: 'لم يُعثر على طلب للرد عليه.',
      yetkisiz: 'ليس لديك إذن لهذا.',
      zaten_bu_kullanici_adini_kullaniyorsun: 'أنت تستخدم اسم المستخدم هذا بالفعل.',
    },
    kod: {
      '23505': 'هذا السجل موجود بالفعل.',
      '57014': 'استغرقت العملية وقتا طويلا. حاول مجددا.',
      otp_expired: 'الرمز غير صالح أو منتهي الصلاحية. اطلب رمزا جديدا.',
      user_already_exists: 'يوجد حساب بهذا العنوان بالفعل. يمكنك تسجيل الدخول.',
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      over_request_rate_limit: 'حاولت مرات كثيرة جدا. انتظر قليلا وحاول مجددا.',
      over_sms_send_rate_limit: 'طُلبت رموز كثيرة جدا. انتظر قليلا وحاول مجددا.',
      weak_password: 'كلمة المرور ضعيفة جدا. اختر أقوى.',
      same_password: 'يجب أن تختلف كلمة المرور الجديدة عن القديمة.',
      signup_disabled: 'لا تُقبل التسجيلات الجديدة حاليا.',
      phone_provider_disabled: 'لا يمكن إرسال رمز إلى هذا الرقم حاليا. حاول لاحقا.',
    },
    metin: {
      sms_saglayici: 'لا يمكن إرسال رمز إلى هذا الرقم حاليا. حاول لاحقا.',
      sms_saglayici2: 'لا يمكن إرسال رمز إلى هذا الرقم حاليا. حاول لاحقا.',
      kod_gecersiz: 'الرمز غير صالح أو منتهي الصلاحية. اطلب رمزا جديدا.',
      zaten_kayitli: 'يوجد حساب بهذا العنوان بالفعل. يمكنك تسجيل الدخول.',
      giris_hatali: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      cok_sik: 'حاولت مرات كثيرة جدا. انتظر قليلا وحاول مجددا.',
      sifre_kisa: 'كلمة المرور قصيرة جدا.',
      sifre_ayni: 'يجب أن تختلف كلمة المرور الجديدة عن القديمة.',
      kayit_kapali: 'لا تُقبل التسجيلات الجديدة حاليا.',
      ag_yok: 'تعذّر الوصول إلى الإنترنت. تحقق من اتصالك وحاول مجددا.',
      oturum_dustu: 'انتهت جلستك. سجّل الدخول مجددا.',
    },
  },
} as const
