/**
 * Deutsche Texte. Spiegelt die Schluesselstruktur von `tr.ts` 1:1;
 * fehlende Schluessel fallen auf Tuerkisch zurueck, der Paritaetstest
 * (`__tests__/ceviri-tamlik.test.ts`) meldet jede Abweichung.
 */
export default {
  ortak: {
    devam: 'Weiter',
    iptal: 'Abbrechen',
    tumunuSec: 'Alle auswählen',
    temizle: 'Löschen',
    kaydet: 'Speichern',
    tekrarDene: 'Erneut versuchen',
    yukleniyor: 'Wird geladen…',
    birSorunOldu: 'Etwas ist schiefgelaufen.',
    agYok: 'Keine Internetverbindung, versuch es erneut',
    gonder: 'Senden',
    gonderiliyor: 'Wird gesendet…',
    tamam: 'Fertig',
    sira: 'Platz {{sira}}',
    sil: 'Löschen',
    vazgec: 'Abbrechen',
    geri: 'Zurück',
    kapat: 'Schließen',
    ara: 'Suchen',
    sonucYok: 'Keine Ergebnisse.',
  },
  karsilama: {
    baslik: 'Wer ist in deiner Nähe? ',
    baslikVurgu: 'Entdecke es.',
    aciklama: 'Check dich ein, lerne neue Leute kennen.\nEntdecke die beliebten Orte um dich herum.',
    kisiSayisi: '{{sayi}} Personen',
    disarida: '{{sayi}} Personen in deiner Nähe unterwegs',
    turKafe: 'Café',
    turRestoran: 'Restaurant',
    turBar: 'Bar',
    adim1Baslik: 'Check-in',
    adim1Aciklama: 'Sei dort sichtbar, wo du bist',
    adim2Baslik: 'Wer ist in der Nähe',
    adim2Aciklama: 'Entdecke Leute am selben Ort',
    adim3Baslik: 'Chatten',
    adim3Aciklama: 'Lerne neue Leute kennen',
    adim4Baslik: 'Beliebte Orte entdecken',
    adim4Aciklama: 'Sieh die angesagten Orte deiner Stadt',
    hesapOlustur: 'Konto erstellen',
    hesabinVarMi: 'Hast du schon ein Konto?',
    girisYap: 'Anmelden',
    haritaAtfi: 'Kartendaten © OpenStreetMap-Mitwirkende',
  },
  kayit: {
    baslik: 'Leg mit deiner E-Mail los',
    epostaEtiket: 'E-Mail-Adresse',
    epostaYerTutucu: 'name@beispiel.de',
    devam: 'Weiter',
    veya: 'oder',
    appleIle: 'Mit Apple fortfahren',
    googleIle: 'Mit Google fortfahren',
    hataEposta: 'Gib eine gültige E-Mail-Adresse ein.',
    hataEpostaKayitli: 'Mit dieser E-Mail gibt es bereits ein Konto. Du kannst dich mit deinem Passwort anmelden.',
    hataSaglayiciKapali: 'Diese Anmeldemethode ist gerade nicht verfügbar. Du kannst mit deiner E-Mail fortfahren.',
    telefonEtiket: 'Telefonnummer',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Code senden',
    gonderiliyor: 'Wird gesendet…',
    zatenHesap: 'Hast du schon ein Konto?',
    girisYap: 'Anmelden',
    hataTelefon: 'Gib eine gültige Telefonnummer ein.',
    hataZatenKayitli: 'Mit dieser Nummer gibt es bereits ein Konto. Du kannst dich mit deinem Passwort anmelden.',
  },
  profilOlustur: {
    baslik: 'Konto erstellen',
    adYerTutucu: 'Dein vollständiger Name',
    adHata: 'Gib deinen vollständigen Namen ein.',
    dogumEtiket: 'Geburtsdatum',
    dogumSec: 'Tag / Monat / Jahr',
    dogumHataGecersiz: 'Wähle dein Geburtsdatum.',
    dogumHataYas: 'Du musst mindestens 18 sein, um Slooin zu nutzen.',
    tarihGun: 'Tag',
    tarihAy: 'Monat',
    tarihYil: 'Jahr',
    tarihTamam: 'Fertig',
    aylar: {
      1: 'Januar',
      2: 'Februar',
      3: 'März',
      4: 'April',
      5: 'Mai',
      6: 'Juni',
      7: 'Juli',
      8: 'August',
      9: 'September',
      10: 'Oktober',
      11: 'November',
      12: 'Dezember',
    },
    kullaniciAdiYerTutucu: 'Benutzername',
    kullaniciAdiIpucu: 'Der Benutzername entspricht nicht dem geforderten Format.',
    kullaniciAdiKontrol: 'Wird geprüft…',
    kullaniciAdiMusait: 'Dieser Benutzername ist frei.',
    kullaniciAdiAlinmis: 'Dieser Benutzername ist vergeben, probier einen anderen.',
    sifreEtiket: 'Passwort',
    sifreYerTutucu: 'Mindestens {{adet}} Zeichen',
    tekrarEtiket: 'Passwort wiederholen',
    tekrarYerTutucu: 'Dasselbe Passwort noch einmal',
    sifrelerFarkli: 'Die Passwörter stimmen noch nicht überein.',
    sifreGoster: 'Passwort anzeigen',
    sifreGizle: 'Passwort verbergen',
    hataSifreKisa: 'Das Passwort muss mindestens {{adet}} Zeichen haben.',
    hataSifreUyusmuyor: 'Die Passwörter stimmen nicht überein. Prüfe beide.',
    adimSayaci: 'Schritt {{simdiki}} / {{toplam}}',
    adim1Baslik: 'Lern uns kennen',
    adim1Aciklama: 'Dein Name erscheint in deinem Profil. Dein Geburtsdatum wird niemandem gezeigt.',
    adEtiket: 'Vollständiger Name',
    adOrnek: 'z. B. Alex Müller',
    yasNotu: 'Slooin ist für Personen ab 18.',
    adim2Baslik: 'Wähle deinen Benutzernamen',
    adim2Aciklama: '3–20 Zeichen; darf Kleinbuchstaben, Ziffern, Punkte und Unterstriche enthalten.',
    kullaniciAdiEtiket: 'Dein Benutzername',
    adim3Baslik: 'Lege dein Passwort fest',
    adim3Aciklama: 'Mit diesem Passwort meldest du dich bei deinem Konto an.',
    sifreUygun: 'Das Passwort ist lang genug.',
    sifrelerAyni: 'Die Passwörter stimmen überein.',
    devam: 'Weiter',
    sozlesmeNotuOn: 'Mit dem Erstellen eines Kontos bestätigst du, dass du die ',
    sozlesmeKosullar: 'Nutzungsbedingungen',
    sozlesmeNotuOrta: ' akzeptierst und die ',
    sozlesmeGizlilik: 'Datenschutzerklärung',
    sozlesmeNotuSon: ' gelesen hast.',
    gonder: 'Konto erstellen',
    gonderiliyor: 'Wird erstellt…',
    oturumDustu: 'Deine Sitzung ist abgelaufen, melde dich erneut an.',
    beklenmeyenHata: 'Ein unerwarteter Fehler ist aufgetreten.',
  },
  bildirimler: {
    baslik: 'Mitteilungen',
    arkadaslikBolumu: 'Freundschaftsanfragen',
    etiketBolumu: 'Markierungsanfragen',
    arkadaslikMetni: 'möchte mit dir befreundet sein.',
    etiketMetni: 'möchte dich bei einem Check-in in {{mekan}} markieren.',
    kabul: 'Annehmen',
    onayla: 'Bestätigen',
    reddet: 'Ablehnen',
    bosBaslik: 'Nichts Neues',
    bosAciklama: 'Freundschaftsanfragen und Leute, die dich markieren wollen, erscheinen hier.',
  },
  kisiler: {
    baslik: 'Leute finden',
    yerTutucu: 'Benutzername oder Name',
    enAzIki: 'Gib mindestens 2 Zeichen ein.',
    bulunamadi: 'Niemand gefunden.',
    ipucu: 'Du kannst jemanden über Benutzername oder Name suchen.',
  },
  baglar: {
    baslik: 'Freunde',
    arkadasliktanCikar: 'Freund entfernen',
    bosArkadas: 'Noch keine Freunde',
    engelle: 'Blockieren',
  },
  mesajlar: {
    baslik: 'Nachrichten',
    bosBaslik: 'Noch keine Unterhaltungen',
    silinmisKullanici: 'Gelöschter Nutzer',
    gizle: 'Ausblenden',
    istekler: 'Anfragen',
    istekRozeti: 'Anfrage',
  },
  mesajIstekleri: {
    baslik: 'Anfragen',
    aciklama: 'Nachrichten von Leuten, die nicht deine Freunde sind, warten hier. Wenn du antwortest, wandert der Chat zu Nachrichten.',
    bosBaslik: 'Keine offenen Anfragen',
    bosAciklama: 'Wenn dir jemand schreibt, der nicht dein Freund ist, siehst du die Nachricht hier.',
    kabul: 'Annehmen',
    reddet: 'Ablehnen',
    geri: 'Nachrichten',
  },
  hesabiSil: {
    baslik: 'Konto löschen',
    uyari: 'Das lässt sich nicht rückgängig machen. Wenn du zurückkommen willst, musst du ein neues Konto von Grund auf erstellen.',
    ipucu: 'Dein Profil, deine Erinnerungen, Freundschaften und deine Chatliste werden gelöscht. Deine Nachrichten bleiben im Verlauf der anderen Person, dein Name wird aber nicht mehr angezeigt.',
    dondur: 'Konto lieber einfrieren',
    parolaEtiket: 'Gib zur Bestätigung dein Passwort ein',
    parolaYerTutucu: 'dein Passwort',
    parolaGerekli: 'Gib zur Bestätigung dein Passwort ein.',
    sil: 'Mein Konto endgültig löschen',
  },
  sohbet: {
    baslik: 'Chat',
    istekSeridi: 'Das ist eine Nachrichtenanfrage. Wenn du antwortest, wandert der Chat zu Nachrichten.',
    kabulEt: 'Annehmen',
    reddet: 'Ablehnen',
    mesajYok: 'Noch keine Nachrichten',
    yerTutucu: 'Nachricht schreiben...',
    kapaliKapi: 'Du kannst dieser Person gerade nicht schreiben.',
  },
  etkilesim: {
    profiliGor: 'Profil von {{ad}} ansehen',
    begen: 'Gefällt mir',
    begeniyiKaldir: 'Gefällt mir nicht mehr',
    yorumlar: 'Kommentare',
    yorumSayisi: '{{sayi}} Kommentare',
    yorumYaz: 'Kommentar schreiben…',
    gonder: 'Senden',
    paylas: 'Teilen',
    yorumSil: 'Kommentar löschen',
    yorumSilOnay: 'Diesen Kommentar löschen?',
    yorumSikayet: 'Melden',
    yorumSikayetOnay: 'Diesen Kommentar melden? Ein gemeldeter Kommentar wird sofort ausgeblendet und vom Moderationsteam geprüft.',
    yorumSikayetEdildi: 'Deine Meldung ist eingegangen und der Kommentar wurde ausgeblendet.',
    bosYorumBaslik: 'Noch keine Kommentare',
    bosYorumAciklama: 'Du kannst den ersten schreiben.',
    silinmisKullanici: 'Gelöschter Nutzer',
  },
  anaSayfa: {
    aramaYerTutucu: 'Suchen',
    suAnDisarida: 'Gerade unterwegs',
    disaridaSayi: '{{sayi}} Personen',
    disaridaDiger: 'Weitere',
    disaridaErisim: '{{ad}}, in {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'jetzt hier',
    bosBaslik: 'Dein Feed ist leer',
    bosAciklama: 'Check dich irgendwo ein oder finde Freunde; ihre Check-ins erscheinen hier.',
    kesfet: 'Orte entdecken',
    azOnce: 'gerade eben',
    dakika: 'vor {{sayi}} Min.',
    saat: 'vor {{sayi}} Std.',
    gun: 'vor {{sayi}} T.',
    silOnay: 'Diesen Check-in endgültig löschen?',
    silAciklama: 'Der Check-in, seine Notiz und sein Foto werden endgültig gelöscht. Er bleibt auch nicht in deinen Erinnerungen; das lässt sich nicht rückgängig machen.',
    silAriza: 'Der Check-in konnte nicht gelöscht werden.',
    haritadaGor: '{{ad}} auf der Karte ansehen',
    secenekler: 'Beitragsoptionen',
    fotografiBuyut: 'Foto vergrößern',
    duzenle: 'Bearbeiten',
    arkadasEtiketle: 'Freund markieren',
    duzenleBaslik: 'Beitrag bearbeiten',
    notEtiketi: 'Notiz',
    notYerTutucu: 'Notiz hinzufügen',
    etiketlenenler: 'Markiert',
    etiketiKaldirEtiketi: 'Markierung von {{ad}} entfernen',
    duzenleAriza: 'Der Beitrag konnte nicht aktualisiert werden.',
  },
  kullanici: {
    bulunamadi: 'Dieses Profil wurde nicht gefunden',
    aniSayisi: '{{sayi}} Erinnerungen',
    takipEt: 'Freund hinzufügen',
    istekBeklemede: 'Ausstehend',
    istegiGeriCek: 'Anfrage zurückziehen',
    bagiKopar: 'Freund entfernen',
    sohbetIste: 'Chat anfragen',
    istekGonderildi: 'Anfrage gesendet',
    sohbetAcik: 'Chat offen',
    mesajGonder: 'Nachricht senden',
    gelenIstekAciklama: 'Wenn du annimmst, seht ihr gegenseitig eure Check-ins und könnt euch schreiben.',
    kabulEt: 'Annehmen',
    reddet: 'Ablehnen',
    anilar: 'Erinnerungen',
    enSik: 'Am häufigsten',
    aniYok: 'Noch keine Erinnerungen',
    profilKapali: 'Dieses Profil ist privat',
    profilKapaliAciklama: 'Ihr müsst Freunde sein, damit du die Erinnerungen sehen kannst.',
    yerYok: 'Noch keine Orte',
    sikayetEt: 'Melden',
    engelle: 'Blockieren',
    engelleOnayi: 'Wenn du blockierst, seht ihr euch nirgends mehr und alle Nachrichten zwischen euch werden endgültig gelöscht. Das lässt sich nicht rückgängig machen.',
    engelleEvet: 'Ja, blockieren',
    vazgec: 'Abbrechen',
    geri: 'Zurück',
  },
  profilDuzenle: {
    baslik: 'Profil bearbeiten',
    adEtiket: 'Vollständiger Name',
    adYerTutucu: 'Dein vollständiger Name',
    adHata: 'Gib deinen vollständigen Namen ein.',
    kullaniciAdiEtiket: 'Benutzername',
    biyografiEtiket: 'Bio',
    biyografiYerTutucu: 'Erzähl ein wenig über dich',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'dein Benutzername',
    instagramIpucu: 'Du kannst auch einen Link einfügen. Wird nicht verifiziert; erscheint als Link in deinem Profil.',
    bolgeEtiket: 'Wo du wohnst',
    bolgeSecilmedi: 'Nicht ausgewählt',
    bolgeIpucu: 'Optional. Wenn du etwas wählst, erscheint es in deinem Profil.',
    bolgeIlSec: 'Provinz wählen',
    bolgeIlceSec: 'Bezirk wählen',
    bolgeKaldir: 'Region entfernen',
    instagramHata: 'Ein Instagram-Benutzername besteht aus Buchstaben, Ziffern, Punkten und Unterstrichen; er darf nicht mit einem Punkt beginnen oder enden.',
    kaydediliyor: 'Wird gespeichert…',
    kaydedildi: 'Dein Profil wurde aktualisiert.',
  },
  ayarlar: {
    baslik: 'Einstellungen',
    geri: 'Zurück',
    profilGizli: 'Privates Profil',
    profilGizliAciklama: 'Wenn aktiviert, sehen nur deine Freunde deine Erinnerungen und Check-ins. Name, Benutzername und Foto bleiben öffentlich, damit man dich finden und dir eine Freundschaftsanfrage schicken kann.',
    verilerimiIndir: 'Meine Daten herunterladen',
    verilerimiIndirHazirlaniyor: 'Wird vorbereitet…',
    verilerimiIndirHata: 'Die Daten konnten nicht vorbereitet werden. Versuch es erneut.',
    gizlilikMetni: 'Datenschutzerklärung',
    bolumGorunurluk: 'Datenschutzeinstellungen',
    aniGorunurlugu: 'Meine früheren Erinnerungen',
    etiketOnayi: 'Vor dem Markieren fragen',
    etiketOnayiAciklama: 'Wenn aus, können dich deine Freunde direkt markieren. Wenn an, wirst du zuerst gefragt; niemand sieht die Markierung, bis du zustimmst.',
    aramadaGorun: 'In der Suche anzeigen',
    aramadaGorunEtiket: 'Sichtbarkeit in der Suche',
    bolumKisiler: 'Personen',
    engellenenler: 'Blockiert',
    bolumHesapIslemleri: 'Konto',
    dondur: 'Mein Konto einfrieren',
    dondurAciklama: 'Deine Daten werden nicht gelöscht. Dein Konto wird bei der nächsten Anmeldung automatisch wieder aktiviert.',
    dondurEvet: 'Ja, einfrieren',
    vazgec: 'Abbrechen',
    hesabiSil: 'Mein Konto löschen',
    cikisYap: 'Abmelden',
    aniHerkeseAcik: 'Alle',
    aniTakipcilerim: 'Nur meine Follower',
    aniKimse: 'Niemand',
    secilmedi: 'Nicht ausgewählt',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'Neuer Benutzername',
    sonrakiDegisim: 'Du kannst ihn wieder ändern am: {{tarih}}',
  },
  aniGorunurlugu: {
    baslik: 'Meine früheren Erinnerungen',
    geri: 'Zurück',
    aciklama: 'Diese Wahl gilt für alle deine Erinnerungen; Erinnerungen aus einem versteckten Check-in bleiben davon unberührt und privat.',
  },
  engellenenler: {
    baslik: 'Blockiert',
    engeliKaldir: 'Blockierung aufheben',
    bosBaslik: 'Du hast niemanden blockiert',
    bosAciklama: 'Wenn du jemanden blockierst, erscheint die Person hier und du kannst es hier rückgängig machen.',
    geri: 'Zurück',
  },
  profil: {
    yerSayisi: 'Orte',
    duzenle: 'Profil bearbeiten',
    paylas: 'Teilen',
    paylasilamadi: 'Teilen konnte auf diesem Gerät nicht geöffnet werden.',
    sekmeAnilar: 'Erinnerungen',
    sekmeYerler: 'Am häufigsten',
    sekmeFotograflar: 'Fotos',
    fotografSayisi: 'Fotos',
    bosFotografBaslik: 'Noch keine Fotos',
    bosFotografAciklama: 'Wenn du beim Einchecken Fotos hinzufügst, sammeln sie sich hier.',
    bosArkadasBaslik: 'Noch keine Freunde',
    kezSayisi: '{{sayi}} Mal',
    bosYerBaslik: 'Du warst noch nirgends',
    bosYerAciklama: 'Mit jedem Check-in werden hier die Orte gereiht, die du am häufigsten besuchst.',
    ayarlar: 'Einstellungen',
    fotografEkle: 'Profilfoto hinzufügen',
    fotografiBuyut: 'Profilfoto vergrößern',
    fotografKaldir: 'Foto entfernen',
    fotografKaldirOnay: 'Dein Foto entfernen?',
    kapat: 'Schließen',
    aniSayisi: 'Erinnerungen',
    bagSayisi: 'Freunde',
    canliEtiket: 'Du bist gerade hier',
    ayril: 'Verlassen',
    canliSil: 'Löschen',
    canliSilOnay: 'Diesen Check-in endgültig löschen? Er bleibt auch nicht in deinen Erinnerungen.',
    bosCanliBaslik: 'Du bist gerade nirgends',
    bosCanliAciklama: 'Check dich dort ein, wo du bist, und sieh, wer in diesem Moment dort ist.',
    checkInYap: 'Irgendwo einchecken',
    anilarBaslik: 'Erinnerungen',
    bosAniBaslik: 'Noch keine Erinnerungen',
    bosAniAciklama: 'Deine Check-ins bleiben hier als Erinnerungen.',
    profilYok: 'Dein Profil ist noch nicht fertig',
    profilYokAciklama: 'Lege Namen und Benutzernamen fest und mach von hier aus weiter.',
    profilOlustur: 'Profil erstellen',
  },
  dogrula: {
    geri: 'Zurück',
    baslik: 'Bestätige deine E-Mail',
    aciklama: 'Wir haben einen 6-stelligen Code an {{eposta}} gesendet.',
    kodEtiketi: 'Bestätigungscode',
    gonder: 'Bestätigen',
    gonderiliyor: 'Wird geprüft…',
    kodGelmedi: 'Kein Code angekommen?',
    spamNotu: 'Wenn er nicht im Posteingang ist, schau auch im Spam-Ordner nach.',
    tekrarGonder: 'Erneut senden',
    tekrarBekle: 'Erneut senden in {{saniye}} s',
    tekrarGonderildi: 'Ein neuer Code wurde gesendet.',
    hakKalmadi: 'Für diese Adresse wurden zu viele Codes angefordert. In einer Stunde kannst du es erneut versuchen.',
    hataEksik: 'Gib den ganzen Code ein.',
    zatenKayitliBaslik: 'Mit dieser Adresse gibt es bereits ein Konto',
    zatenKayitliAciklama: 'Mit {{eposta}} wurde bereits ein Konto erstellt. Du kannst dich mit deinem Passwort anmelden.',
    girisYap: 'Anmelden',
    baskaNumara: 'Mit einer anderen Adresse fortfahren',
  },
  altGezinme: {
    anaSayfa: 'Start',
    bildirimler: 'Mitteilungen',
    mesajlar: 'Nachrichten',
    profil: 'Profil',
  },
  arkadasSecici: {
    baslik: 'Freunde markieren',
    bos: 'Du hast noch keine Freunde. Sobald du eine Freundschaftsanfrage sendest und sie angenommen wird, erscheinen sie hier und du kannst sie in deinen Check-ins markieren.',
    tamamSayili: 'Fertig ({{sayi}})',
  },
  harita: {
    cevre: 'Orte in deiner Nähe',
    kisiBurada: '{{ad}}, {{sayi}} Personen hier',
    buMekan: 'Dieser Ort, {{durum}}',
    buradasin: 'Du bist hier',
  },
  sikayet: {
    baslik: 'Melden',
    sebepSec: 'Wähle einen Grund',
    alindi: 'Deine Meldung ist eingegangen',
    tesekkur: 'Danke, dass du uns Bescheid gibst.',
    mesajBaglami: 'Bei der Prüfung werden auch die umliegenden Nachrichten für die Moderation geöffnet.',
    aciklamaYerTutucu: 'Möchtest du etwas ergänzen?',
    sebepler: {
      taciz: 'Belästigung oder Mobbing',
      uygunsuz_icerik: 'Unangemessener Inhalt',
      sahte_hesap: 'Gefälschtes Konto',
      spam: 'Spam oder Werbung',
      diger: 'Sonstiges',
    },
  },
  hesapDurumu: {
    askida: 'Dein Konto ist gesperrt',
    yasakli: 'Dein Konto wurde dauerhaft geschlossen',
    sebep: 'Grund: {{sebep}}',
    bitis: 'Endet: {{tarih}}',
    ipucu: 'In dieser Zeit ist dein Profil für andere nicht sichtbar und du kannst keine neuen Inhalte posten. Deine Daten wurden nicht gelöscht.',
    yenile: 'Aktualisieren',
    cikisYapilamadi: 'Abmelden nicht möglich',
  },
  checkIn: {
    baslik: 'Neuer Check-in',
    notYerTutucu: 'Notiz hinzufügen (optional)',
    ilkUyariBaslik: 'Was teilt dieser Check-in?',
    ilkUyariMetin: 'Wenn du dich eincheckst, werden der Ort, an dem du bist, und deine Notiz (falls vorhanden) für deine Freunde sichtbar. Er endet von selbst, wenn der Check-in abläuft oder sobald du „Ich bin weg“ sagst. Wenn du willst, kannst du diesen Check-in versteckt machen und nur in deinem eigenen Profil behalten.',
    anladim: 'Verstanden',
    gizliYap: 'Versteckt machen',
    arkadasEkle: 'Freunde hinzufügen (optional)',
    arkadasEkleSecili: 'Freunde hinzufügen ({{sayi}} ausgewählt)',
    etiketiKaldir: 'Markierung von {{ad}} entfernen',
    fotografEkle: 'Foto hinzufügen (optional)',
    fotografDegistir: 'Foto ändern',
    fotografCek: 'Foto aufnehmen',
    galeridenSec: 'Aus der Galerie wählen',
    kameraIzni: 'Zum Fotografieren wird die Kameraberechtigung benötigt.',
    fotografYuklenemedi: 'Das Foto konnte nicht hochgeladen werden; du wurdest mit deiner Notiz eingecheckt',
    etiketlenemedi: 'Du bist eingecheckt, aber deine Freunde konnten nicht markiert werden.',
    gonder: 'Einchecken',
    gonderiliyor: 'Wird eingecheckt...',
  },
  mekanDuzenle: {
    baslik: 'Angaben korrigieren',
    aciklama: 'Stimmt etwas nicht? Deine Korrektur geht an einen Moderator; nach der Freigabe wird sie für alle übernommen.',
    gonderildiBaslik: 'Deine Anfrage wurde gesendet',
    gonderildiMetin: 'Die Ortsangaben werden aktualisiert, sobald ein Moderator sie geprüft und freigegeben hat.',
    bekleyenBaslik: 'Du hast eine offene Anfrage',
    bekleyenMetin: 'Die Anfrage, die du für diesen Ort gesendet hast, wird noch geprüft. Sobald sie erledigt ist, kannst du eine neue Korrektur senden.',
    adEtiket: 'Name des Ortes',
    adYerTutucu: 'Name des Ortes',
    mahalle: 'Viertel',
    mahalleYerTutucu: 'z. B. Alaaddinbey',
    adres: 'Adresse',
    adresYerTutucu: 'Straße, Hausnummer',
    il: 'Provinz',
    ilYerTutucu: 'Bursa',
    ilce: 'Bezirk',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Typ',
    kapakFotografi: 'Titelfoto',
    fotografiKaldir: 'Foto entfernen',
    fotografEkle: 'Foto hinzufügen',
    fotografSecilemedi: 'Das Foto konnte nicht ausgewählt werden.',
    galeriIzni: 'Zum Auswählen aus der Galerie wird die Fotoberechtigung benötigt.',
    oturumYok: 'Sitzung nicht gefunden',
    zatenKapali: 'Dieser Ort ist bereits als dauerhaft geschlossen markiert.',
    kapaliBaslik: 'Dieser Ort ist dauerhaft geschlossen',
    kapaliAciklama: 'Nach Freigabe wird dieser Ort aus Listen und Suche entfernt. Hier gemachte Check-ins werden nicht gelöscht.',
    onceDegistir: 'Ändere zuerst etwas.',
    talebiGonder: 'Anfrage senden',
  },
  mekanEkle: {
    baslik: 'Neuen Ort hinzufügen',
    adYerTutucu: 'Name des Ortes',
    turuSec: 'Typ wählen',
    adresYerTutucu: 'Adresse (optional)',
    adresSoru: 'Stimmt diese Adresse?',
    adresAciklama: 'Anhand deines Standorts gefunden. Wenn sie falsch ist, kannst du das Feld oben bearbeiten.',
    dogru: 'Stimmt',
    benzerBaslik: 'Meintest du einen davon?',
    konumAlinamadi: 'Standort konnte nicht ermittelt werden, versuch es erneut',
    adVeTurGerekli: 'Name und Typ des Ortes sind erforderlich',
    ekle: 'Hinzufügen',
    ekleniyor: 'Wird hinzugefügt...',
  },
  turGruplari: {
    'Yeme içme': 'Essen & Trinken',
    Gece: 'Nachtleben',
    'Açık alan': 'Im Freien',
    Kültür: 'Kultur',
    Spor: 'Sport',
    Alışveriş: 'Einkaufen',
    Diğer: 'Sonstiges',
  },
  turler: {
    Kafe: 'Café',
    Kahveci: 'Kaffeehaus',
    'Çay evi': 'Teehaus',
    Restoran: 'Restaurant',
    Lokanta: 'Gasthaus',
    'Türk mutfağı': 'Türkische Küche',
    Kebapçı: 'Kebabhaus',
    'Balık restoranı': 'Fischrestaurant',
    Ocakbaşı: 'Grillhaus',
    'Kahvaltı salonu': 'Frühstückslokal',
    Fırın: 'Bäckerei',
    'Fast food': 'Fast Food',
    Burgerci: 'Burgerladen',
    Pizzacı: 'Pizzeria',
    Tatlıcı: 'Konditorei',
    Dondurmacı: 'Eisdiele',
    Bar: 'Bar',
    Pub: 'Pub',
    'Gece kulübü': 'Nachtclub',
    Meyhane: 'Taverne',
    'Nargile kafe': 'Shisha-Lounge',
    'Kokteyl barı': 'Cocktailbar',
    Park: 'Park',
    'Halk bahçesi': 'Volksgarten',
    'Doğal alan': 'Naturgebiet',
    Plaj: 'Strand',
    Meydan: 'Platz',
    'Kamp alanı': 'Campingplatz',
    Göl: 'See',
    Müze: 'Museum',
    Sinema: 'Kino',
    Tiyatro: 'Theater',
    'Sanat galerisi': 'Kunstgalerie',
    Kütüphane: 'Bibliothek',
    'Tarihi yer': 'Historische Stätte',
    'Konser salonu': 'Konzertsaal',
    'Kültür merkezi': 'Kulturzentrum',
    'Spor salonu': 'Fitnessstudio',
    Stadyum: 'Stadion',
    'Yüzme havuzu': 'Schwimmbad',
    'Halı saha': 'Fußballplatz',
    AVM: 'Einkaufszentrum',
    Market: 'Supermarkt',
    Bakkal: 'Lebensmittelladen',
    'Giyim mağazası': 'Bekleidungsgeschäft',
    Kitapçı: 'Buchhandlung',
    Kuyumcu: 'Juwelier',
    Otel: 'Hotel',
    Eczane: 'Apotheke',
    Hastane: 'Krankenhaus',
    Banka: 'Bank',
    Kuaför: 'Friseur',
    'Güzellik salonu': 'Kosmetiksalon',
    Üniversite: 'Universität',
    'Canlı müzik': 'Livemusik',
  },
  kesfet: {
    baslik: 'Check-in',
    harita: 'Karte',
    liste: 'Liste',
    turSuzgeci: 'Typfilter',
    turFiltresi: 'Typfilter',
    turBulunamadi: 'In deiner Nähe gibt es keine Typen zum Anzeigen.',
    filtreyiKaldir: 'Filter entfernen',
    tumunuSec: 'Alle auswählen',
    temizle: 'Löschen',
    kaydet: 'Speichern',
    kaydetSayili: 'Speichern ({{sayi}})',
    tumu: 'Alle',
    sakin: 'Ruhig',
    yogun: 'Voll',
    populer: 'Beliebt',
    yakinindakiMekanlar: 'Orte in deiner Nähe',
    sonuclar: 'Ergebnisse',
    kisiBurada: '{{sayi}} Personen hier',
    checkIn: 'Check-in',
    konumuGor: 'Standort ansehen',
    checkInYap: 'Hier einchecken',
    mekanAra: 'Orte suchen',
    kisi: '{{sayi}} Personen',
    taraniyor: 'Deine Umgebung wird durchsucht…',
    cevreGorunmuyor: 'Wir sehen deine Umgebung nicht',
    konumIzniAciklama: 'Wir brauchen die Standortberechtigung, um dir Orte in der Nähe zu zeigen. Aktiviere sie in den Browsereinstellungen und versuch es erneut.',
    konumuAc: '{{ad}} öffnen',
    konumuGorEtiketi: '{{ad}} ansehen',
    checkInEtiketi: 'In {{ad}} einchecken',
    filtreyiKaldirEtiketi: 'Filter {{tur}} entfernen',
    kisiBuradaEtiket: 'Personen hier',
    suAnBuradasin: 'Du bist gerade hier',
    ayrildim: 'Ich bin weg',
    araniyor: 'Wird gesucht…',
    aramaBulunamadi: 'Kein Ort für „{{arama}}“ gefunden. Versuch eine andere Schreibweise.',
    sonucSayisi: '{{sayi}} Ergebnisse',
    bosArama: 'Keine Ergebnisse für „{{arama}}“ in dieser Provinz.',
    bosFiltre: 'Mit diesem Filter gibt es keine Orte im Umkreis von 500 m.',
    bosCevre: 'Keine Orte in deiner Nähe.',
    mekanEkle: 'Ort nicht gefunden? Füge ihn hinzu',
    atif: 'Ortsdaten: Foursquare · Viertel und Bezirk: © OpenStreetMap-Mitwirkende',
  },
  checkInHaritasi: {
    geri: 'Zurück',
    haritaAcikla: 'Tippe auf die Karte für die Wegbeschreibung',
    haritadaAc: 'Wegbeschreibung',
    secimBaslik: 'Welche Karte sollen wir öffnen?',
    appleHaritalar: 'Apple Karten',
    googleHaritalar: 'Google Maps',
    vazgec: 'Abbrechen',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Foto von {{ad}}',
    menu: 'Optionen',
    yolTarifi: 'Wegbeschreibung',
    buradaCheckIn: 'Hier einchecken',
    yaklas: 'Näher kommen zum Einchecken · {{mesafe}}',
    buradasinAyril: 'Du bist hier · Verlassen',
    kapandi: 'Dieser Ort ist dauerhaft geschlossen',
    kapandiAciklama: 'Du kannst dich hier nicht mehr einchecken und der Ort wird nicht mehr in Listen gezeigt. Deine früheren Erinnerungen bleiben.',
    kisiBurada: 'Personen hier',
    bugun: 'Heute',
    haritadaGoster: 'Standort auf der Karte zeigen',
    checkInSayisi: '{{sayi}} Check-ins',
    kisiSayisi: '{{sayi}} Personen',
    ilcedekiYerler: 'Orte in {{ilce}}',
    siralamaYok: 'Kein Ranking',
    suAnBurada: 'Jetzt hier',
    diger: 'Weitere',
    biri: 'Jemand',
    suAn: 'jetzt',
    liderlik: 'Rangliste',
    sonCheckInler: 'Zuletzt',
    liderlikBos: 'Hier gibt es noch keine Check-ins zum Anzeigen.',
    sonBos: 'Hier gibt es noch keine Check-ins zum Anzeigen.',
    fotograflar: 'Fotos',
    fotografBos: 'Hier gibt es noch keine Fotos.',
    fotografAc: 'Foto vergrößern',
    dahaFazlaFotograf: 'Mehr Fotos',
    puan: 'Bewertung',
    puanlamaSayisi: '{{sayi}} Bewertungen',
    puanYok: 'Noch keine Bewertung',
    puanAzOy: 'Für eine Punktzahl sind mindestens 3 Bewertungen nötig',
    puanKotu: 'Schlecht',
    puanIyi: 'Gut',
    puanHarika: 'Super',
    puanSoru: 'Wie fandest du diesen Ort?',
    puanSart: 'Check dich zuerst hier ein, um zu bewerten.',
    puanGonder: 'Absenden',
    puanGuncelle: 'Bewertung ändern',
    puanGonderiliyor: 'Wird gesendet…',
    puanTesekkur: 'Deine Bewertung wurde gespeichert.',
  },
  giris: {
    epostaYerTutucu: 'E-Mail-Adresse',
    sifreYerTutucu: 'Passwort',
    gonder: 'Anmelden',
    gonderiliyor: 'Anmeldung läuft…',
    kayitOl: 'Neues Konto erstellen',
    hataEposta: 'Gib eine gültige E-Mail-Adresse ein.',
    hataBos: 'Gib deine E-Mail-Adresse und dein Passwort ein.',
    sifremiUnuttum: 'Passwort vergessen?',
  },
  sifreSifirla: {
    geri: 'Zurück',
    baslik: 'Passwort zurücksetzen',
    aciklama: 'Gib die E-Mail-Adresse deines Kontos ein und wir senden dir einen 6-stelligen Code.',
    epostaYerTutucu: 'E-Mail-Adresse',
    kodGonder: 'Code senden',
    gonderiliyor: 'Wird gesendet…',
    hataEposta: 'Gib eine gültige E-Mail-Adresse ein.',
    hataHesapYok: 'Mit dieser E-Mail-Adresse wurde kein Konto gefunden.',
    kodBaslik: 'Gib den Code ein',
    kodAciklama: 'Wir haben einen 6-stelligen Code an {{eposta}} gesendet.',
    kodEtiketi: 'Bestätigungscode',
    dogrula: 'Bestätigen',
    dogrulaniyor: 'Wird geprüft…',
    hataEksik: 'Gib den ganzen Code ein.',
    kodGelmedi: 'Kein Code angekommen?',
    spamNotu: 'Wenn er nicht im Posteingang ist, schau auch im Spam-Ordner nach.',
    tekrarGonder: 'Erneut senden',
    tekrarBekle: 'Erneut senden in {{saniye}} s',
    tekrarGonderildi: 'Ein neuer Code wurde gesendet.',
    hakKalmadi: 'Für diese Adresse wurden zu viele Codes angefordert. In einer Stunde kannst du es erneut versuchen.',
    yeniBaslik: 'Lege dein neues Passwort fest',
    yeniAciklama: 'Der Code wurde bestätigt. Wähle jetzt ein neues Passwort.',
    sifreYerTutucu: 'Neues Passwort (mindestens {{adet}} Zeichen)',
    sifreTekrarYerTutucu: 'Neues Passwort (noch einmal)',
    kaydet: 'Passwort speichern',
    kaydediliyor: 'Wird gespeichert…',
    hataSifreKisa: 'Das Passwort muss mindestens {{adet}} Zeichen haben.',
    hataSifreEslesmiyor: 'Die Passwörter stimmen nicht überein.',
  },
  hatalar: {
    genel: 'Etwas ist schiefgelaufen. Versuch es gleich noch einmal.',
    kullaniciAdi30Gun: 'Du kannst deinen Benutzernamen alle 30 Tage ändern. Noch {{gun}} Tage.',
    vt: {
      aski_bitisi_gelecekte_olmali: 'Das Ende der Sperre muss in der Zukunft liegen.',
      bir_moderatore_islem_uygulanamaz: 'Auf einen Moderator können keine Maßnahmen angewendet werden.',
      bu_kisiye_su_an_mesaj_gonderemezsin: 'Du kannst dieser Person gerade nicht schreiben.',
      bu_kullanici_adi_alinmis: 'Dieser Benutzername ist vergeben, probier einen anderen.',
      bu_kullanici_bulunamadi: 'Dieser Nutzer wurde nicht gefunden.',
      bu_fotograf_sana_ait_degil: 'Dieses Foto gehört nicht dir.',
      bu_il_listemizde_yok: 'Diese Provinz ist nicht in unserer Liste.',
      bu_mekan_bulunamadi: 'Dieser Ort wurde nicht gefunden.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'Die Anfrage, die du für diesen Ort gesendet hast, wird noch geprüft.',
      bu_mekan_kalici_olarak_kapandi: 'Dieser Ort ist dauerhaft geschlossen.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'Dieser Ort ist bereits als geschlossen markiert.',
      bu_tur_listemizde_yok: 'Dieser Typ ist nicht in unserer Liste.',
      en_az_bir_alan_doldurulmali: 'Du musst mindestens eine Angabe ändern.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'Du hast das Tageslimit für Korrekturen (5) erreicht. Morgen kannst du es erneut versuchen.',
      hesabin_su_an_bu_islemi_yapamaz: 'Dein Konto kann das gerade nicht tun.',
      bu_paylasim_bulunamadi: 'Dieser Beitrag wurde nicht gefunden.',
      not_en_fazla_500_karakter_olabilir: 'Die Notiz darf höchstens 500 Zeichen haben.',
      bu_mesaji_sikayet_edemezsin: 'Du kannst diese Nachricht nicht melden.',
      bugunluk_istek_sinirina_ulastin: 'Du hast das Anfragelimit für heute erreicht.',
      check_in_bulunamadi: 'Check-in nicht gefunden.',
      cok_fazla_kimlik: 'Zu viele Kennungen gesendet.',
      en_az_2_karakter_gerekli: 'Gib mindestens 2 Zeichen ein.',
      gecersiz_bulunurluk_degeri: 'Ungültiger Verfügbarkeitswert.',
      gecersiz_gorunurluk_degeri: 'Ungültiger Sichtbarkeitswert.',
      gecersiz_platform: 'Ungültige Plattform.',
      gecersiz_sikayet_durumu: 'Ungültiger Meldestatus.',
      gecersiz_sikayet_hedefi: 'Ungültiges Meldeziel.',
      gerekce_belirtilmeli: 'Du musst einen Grund angeben.',
      geri_cekilecek_istek_bulunamadi: 'Keine Anfrage zum Zurückziehen gefunden.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'Du hast das Tageslimit für neue Orte (5) erreicht. Morgen kannst du es erneut versuchen.',
      hesabin_su_anda_kullanilamiyor: 'Dein Konto ist gerade nicht verfügbar.',
      hesabin_zaten_kullanilamaz_durumda: 'Dein Konto ist bereits nicht verfügbar.',
      istegin_zaten_gonderilmis: 'Deine Anfrage wurde bereits gesendet.',
      jeton_bos_olamaz: 'Das Mitteilungstoken darf nicht leer sein.',
      jeton_cok_uzun: 'Das Mitteilungstoken ist zu lang.',
      kendi_mesajini_sikayet_edemezsin: 'Du kannst deine eigene Nachricht nicht melden.',
      kendine_islem_uygulayamazsin: 'Du kannst keine Maßnahme auf dich selbst anwenden.',
      kendine_istek_gonderemezsin: 'Du kannst dir selbst keine Anfrage senden.',
      kendine_mesaj_gonderemezsin: 'Du kannst dir selbst nicht schreiben.',
      kendini_engelleyemezsin: 'Du kannst dich nicht selbst blockieren.',
      kendini_sikayet_edemezsin: 'Du kannst dich nicht selbst melden.',
      kimlik_dogrulamasi_gerekli: 'Dafür musst du angemeldet sein.',
      konusma_bulunamadi: 'Unterhaltung nicht gefunden.',
      kullanici_adi_kurallara_uymuyor: 'Der Benutzername entspricht nicht den Regeln.',
      kullanici_belirtilmeli: 'Ein Nutzer muss angegeben werden.',
      mekan_bulunamadi: 'Ort nicht gefunden.',
      gecersiz_puan: 'Ungültige Bewertung.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'Check dich zuerst hier ein, um zu bewerten.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'Du bist zu weit vom Ort entfernt. Zum Einchecken musst du im Umkreis von etwa 1 Kilometer sein.',
      mekana_yakin_olmalisin_200_m_icinde: 'Um einen Ort hinzuzufügen, musst du im Umkreis von etwa 200 Metern sein.',
      mesaj_bos_olamaz: 'Die Nachricht darf nicht leer sein.',
      mesaj_bu_konusmada_bulunamadi: 'Die Nachricht wurde in dieser Unterhaltung nicht gefunden.',
      mesaj_cok_uzun: 'Die Nachricht ist zu lang.',
      profil_bulunamadi: 'Profil nicht gefunden.',
      sikayet_bulunamadi: 'Meldung nicht gefunden.',
      sikayet_sebebi_belirtilmeli: 'Du musst einen Grund für die Meldung angeben.',
      yanitlanacak_istek_bulunamadi: 'Keine Anfrage zum Beantworten gefunden.',
      yetkisiz: 'Dafür hast du keine Berechtigung.',
      zaten_bu_kullanici_adini_kullaniyorsun: 'Du verwendest diesen Benutzernamen bereits.',
    },
    kod: {
      '23505': 'Dieser Eintrag existiert bereits.',
      '57014': 'Zeitüberschreitung. Versuch es erneut.',
      otp_expired: 'Der Code ist ungültig oder abgelaufen. Fordere einen neuen an.',
      user_already_exists: 'Mit dieser Adresse gibt es bereits ein Konto. Du kannst dich anmelden.',
      invalid_credentials: 'E-Mail-Adresse oder Passwort falsch.',
      over_request_rate_limit: 'Du hast es zu oft versucht. Warte kurz und versuch es erneut.',
      over_sms_send_rate_limit: 'Zu viele Codes angefordert. Warte kurz und versuch es erneut.',
      weak_password: 'Das Passwort ist zu schwach. Wähle ein stärkeres.',
      same_password: 'Das neue Passwort muss sich vom alten unterscheiden.',
      signup_disabled: 'Neue Registrierungen werden gerade nicht angenommen.',
      phone_provider_disabled: 'An diese Nummer kann gerade kein Code gesendet werden. Versuch es später.',
    },
    metin: {
      sms_saglayici: 'An diese Nummer kann gerade kein Code gesendet werden. Versuch es später.',
      sms_saglayici2: 'An diese Nummer kann gerade kein Code gesendet werden. Versuch es später.',
      kod_gecersiz: 'Der Code ist ungültig oder abgelaufen. Fordere einen neuen an.',
      zaten_kayitli: 'Mit dieser Adresse gibt es bereits ein Konto. Du kannst dich anmelden.',
      giris_hatali: 'E-Mail-Adresse oder Passwort falsch.',
      cok_sik: 'Du hast es zu oft versucht. Warte kurz und versuch es erneut.',
      sifre_kisa: 'Das Passwort ist zu kurz.',
      sifre_ayni: 'Das neue Passwort muss sich vom alten unterscheiden.',
      kayit_kapali: 'Neue Registrierungen werden gerade nicht angenommen.',
      ag_yok: 'Keine Verbindung zum Internet. Prüfe deine Verbindung und versuch es erneut.',
      oturum_dustu: 'Deine Sitzung ist abgelaufen. Melde dich erneut an.',
    },
  },
} as const
