/**
 * English strings.
 *
 * Turkish (`tr.ts`) is the source language; this file mirrors its key
 * structure one-to-one. A key missing here falls back to Turkish, and
 * `__tests__/ceviri-tamlik.test.ts` fails when any language drifts
 * from the Turkish key set (i18n round, 2026-09-13).
 *
 * Venue TYPE keys (`turler`, `turGruplari`) are the Turkish database
 * values on purpose - the value column is what the user sees.
 */
export default {
  ortak: {
    devam: 'Continue',
    iptal: 'Cancel',
    tumunuSec: 'Select all',
    temizle: 'Clear',
    kaydet: 'Save',
    tekrarDene: 'Try again',
    yukleniyor: 'Loading…',
    birSorunOldu: 'Something went wrong.',
    agYok: 'No internet connection, try again',
    gonder: 'Send',
    gonderiliyor: 'Sending…',
    tamam: 'Done',
    sira: 'Rank {{sira}}',
    sil: 'Delete',
    vazgec: 'Cancel',
    geri: 'Back',
    kapat: 'Close',
    ara: 'Search',
    sonucYok: 'No results.',
  },
  karsilama: {
    baslik: "See who's nearby, ",
    baslikVurgu: 'explore.',
    aciklama: 'Check in, meet new people.\nDiscover the popular spots around you.',
    kisiSayisi: '{{sayi}} people',
    disarida: '{{sayi}} people out nearby',
    turKafe: 'Café',
    turRestoran: 'Restaurant',
    turBar: 'Bar',
    adim1Baslik: 'Check In',
    adim1Aciklama: 'Be seen at the place you are',
    adim2Baslik: "Who's nearby",
    adim2Aciklama: 'Discover people at the same place',
    adim3Baslik: 'Chat',
    adim3Aciklama: 'Meet new people',
    adim4Baslik: 'Discover popular places',
    adim4Aciklama: 'See the trending spots in your city',
    hesapOlustur: 'Create account',
    hesabinVarMi: 'Already have an account?',
    girisYap: 'Sign in',
    haritaAtfi: 'Map data © OpenStreetMap contributors',
  },
  kayit: {
    baslik: 'Get started with your email',
    epostaEtiket: 'Email address',
    epostaYerTutucu: 'name@example.com',
    devam: 'Continue',
    veya: 'or',
    appleIle: 'Continue with Apple',
    googleIle: 'Continue with Google',
    hataEposta: 'Enter a valid email address.',
    hataEpostaKayitli: 'There is already an account with this email. You can sign in with your password.',
    hataSaglayiciKapali: 'This sign-in method is not available right now. You can continue with your email.',
    telefonEtiket: 'Phone number',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Send code',
    gonderiliyor: 'Sending…',
    zatenHesap: 'Already have an account?',
    girisYap: 'Sign in',
    hataTelefon: 'Enter a valid phone number.',
    hataZatenKayitli: 'There is already an account with this number. You can sign in with your password.',
  },
  profilOlustur: {
    baslik: 'Create account',
    adYerTutucu: 'Your full name',
    adHata: 'Enter your full name.',
    dogumEtiket: 'Date of birth',
    dogumSec: 'Day / Month / Year',
    dogumHataGecersiz: 'Select your date of birth.',
    dogumHataYas: 'You must be at least 18 to use Slooin.',
    tarihGun: 'Day',
    tarihAy: 'Month',
    tarihYil: 'Year',
    tarihTamam: 'Done',
    aylar: {
      1: 'January',
      2: 'February',
      3: 'March',
      4: 'April',
      5: 'May',
      6: 'June',
      7: 'July',
      8: 'August',
      9: 'September',
      10: 'October',
      11: 'November',
      12: 'December',
    },
    kullaniciAdiYerTutucu: 'Username',
    kullaniciAdiIpucu: 'The username does not match the required format.',
    kullaniciAdiKontrol: 'Checking…',
    kullaniciAdiMusait: 'This username is available.',
    kullaniciAdiAlinmis: 'This username is taken, try another one.',
    sifreEtiket: 'Password',
    sifreYerTutucu: 'At least {{adet}} characters',
    tekrarEtiket: 'Repeat password',
    tekrarYerTutucu: 'The same password again',
    sifrelerFarkli: 'The passwords do not match yet.',
    sifreGoster: 'Show password',
    sifreGizle: 'Hide password',
    hataSifreKisa: 'The password must be at least {{adet}} characters.',
    hataSifreUyusmuyor: 'The passwords do not match. Check both.',
    adimSayaci: 'Step {{simdiki}} / {{toplam}}',
    adim1Baslik: "Let's get to know you",
    adim1Aciklama: 'Your name appears on your profile. Your date of birth is never shown to anyone.',
    adEtiket: 'Full name',
    adOrnek: 'e.g. Alex Taylor',
    yasNotu: 'Slooin is for ages 18 and over.',
    adim2Baslik: 'Choose your username',
    adim2Aciklama: '3-20 characters; may contain lowercase letters, digits, dots and underscores.',
    kullaniciAdiEtiket: 'Your username',
    adim3Baslik: 'Set your password',
    adim3Aciklama: "You'll sign in to your account with this password.",
    sifreUygun: 'The password is long enough.',
    sifrelerAyni: 'The passwords match.',
    devam: 'Continue',
    sozlesmeNotuOn: 'By creating an account you confirm that you accept the ',
    sozlesmeKosullar: 'Terms of Use',
    sozlesmeNotuOrta: ' and have read the ',
    sozlesmeGizlilik: 'Privacy Policy',
    sozlesmeNotuSon: '.',
    gonder: 'Create account',
    gonderiliyor: 'Creating…',
    oturumDustu: 'Your session has expired, sign in again.',
    beklenmeyenHata: 'An unexpected error occurred.',
  },
  bildirimler: {
    baslik: 'Notifications',
    arkadaslikBolumu: 'Friend requests',
    etiketBolumu: 'Tag requests',
    arkadaslikMetni: 'wants to be your friend.',
    etiketMetni: 'wants to tag you in a check-in at {{mekan}}.',
    kabul: 'Accept',
    onayla: 'Approve',
    reddet: 'Decline',
    bosBaslik: 'Nothing new',
    bosAciklama: 'Friend requests and people who want to tag you appear here.',
  },
  kisiler: {
    baslik: 'Find people',
    yerTutucu: 'Username or name',
    enAzIki: 'Type at least 2 characters.',
    bulunamadi: 'No one found.',
    ipucu: 'You can search for someone you know by username or name.',
  },
  baglar: {
    baslik: 'Friends',
    arkadasliktanCikar: 'Remove friend',
    bosArkadas: 'No friends yet',
    engelle: 'Block',
  },
  mesajlar: {
    baslik: 'Messages',
    bosBaslik: 'No conversations yet',
    silinmisKullanici: 'Deleted user',
    gizle: 'Hide',
    istekler: 'Requests',
    istekRozeti: 'Request',
  },
  mesajIstekleri: {
    baslik: 'Requests',
    aciklama: 'Messages from people who are not your friends wait here. If you reply, the chat moves to Messages.',
    bosBaslik: 'No pending requests',
    bosAciklama: "If someone who isn't your friend writes to you, you'll see the message here.",
    kabul: 'Accept',
    reddet: 'Decline',
    geri: 'Messages',
  },
  hesabiSil: {
    baslik: 'Delete your account',
    uyari: 'This cannot be undone. If you want to come back, you will need to create a new account from scratch.',
    ipucu: 'Your profile, memories, friendships and conversation list are deleted. Your messages remain in the other person’s history, but your name is no longer shown.',
    dondur: 'Freeze my account instead',
    parolaEtiket: 'Enter your password to confirm',
    parolaYerTutucu: 'your password',
    parolaGerekli: 'Enter your password to confirm.',
    sil: 'Permanently delete my account',
  },
  sohbet: {
    baslik: 'Chat',
    istekSeridi: 'This is a message request. If you reply, the chat moves to Messages.',
    kabulEt: 'Accept',
    reddet: 'Decline',
    mesajYok: 'No messages yet',
    yerTutucu: 'Write a message...',
    kapaliKapi: "You can't message this person right now.",
  },
  etkilesim: {
    profiliGor: "View {{ad}}'s profile",
    begen: 'Like',
    begeniyiKaldir: 'Unlike',
    yorumlar: 'Comments',
    yorumSayisi: '{{sayi}} comments',
    yorumYaz: 'Write a comment…',
    gonder: 'Send',
    paylas: 'Share',
    yorumSil: 'Delete comment',
    yorumSilOnay: 'Delete this comment?',
    yorumSikayet: 'Report',
    yorumSikayetOnay: 'Report this comment? A reported comment is hidden immediately and reviewed by the moderation team.',
    yorumSikayetEdildi: 'Your report was received and the comment was hidden.',
    bosYorumBaslik: 'No comments yet',
    bosYorumAciklama: 'You can write the first one.',
    silinmisKullanici: 'Deleted user',
  },
  anaSayfa: {
    aramaYerTutucu: 'Search',
    suAnDisarida: 'Out right now',
    disaridaSayi: '{{sayi}} people',
    disaridaDiger: 'Other',
    disaridaErisim: '{{ad}}, at {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'here right now',
    bosBaslik: 'Your feed is empty',
    bosAciklama: 'Check in somewhere or make some friends; their check-ins will show up here.',
    kesfet: 'Explore places',
    azOnce: 'just now',
    dakika: '{{sayi}} min ago',
    saat: '{{sayi}} h ago',
    gun: '{{sayi}} d ago',
    silOnay: 'Permanently delete this check-in?',
    silAciklama: 'The check-in, its note and photo are permanently deleted. It will not remain in your memories either; this cannot be undone.',
    silAriza: 'The check-in could not be deleted.',
    haritadaGor: 'See {{ad}} on the map',
    secenekler: 'Post options',
    fotografiBuyut: 'Enlarge photo',
    duzenle: 'Edit',
    arkadasEtiketle: 'Tag a friend',
    duzenleBaslik: 'Edit post',
    notEtiketi: 'Note',
    notYerTutucu: 'Add a note',
    etiketlenenler: 'Tagged',
    etiketiKaldirEtiketi: 'Remove tag {{ad}}',
    duzenleAriza: 'The post could not be updated.',
  },
  kullanici: {
    bulunamadi: 'This profile was not found',
    takipEt: 'Add friend',
    istekBeklemede: 'Pending',
    istegiGeriCek: 'Withdraw request',
    bagiKopar: 'Remove friend',
    gelenIstekAciklama: "If you accept, you can see each other's check-ins and message each other.",
    kabulEt: 'Accept',
    reddet: 'Decline',
    anilar: 'Memories',
    enSik: 'Most visited',
    aniYok: 'No memories yet',
    profilKapali: 'This profile is private',
    profilKapaliAciklama: 'You need to be friends to see their memories.',
    yerYok: 'No places yet',
    sikayetEt: 'Report',
    engelle: 'Block',
    engelleOnayi: "If you block them, you won't see each other anywhere and all messages between you are permanently deleted. This cannot be undone.",
    engelleEvet: 'Yes, block',
    vazgec: 'Cancel',
    geri: 'Back',
    mesajYaz: 'Message',
    arkadassin: 'Friends',
    paylas: 'Share profile',
    paylasMetni: '{{ad}} on Slooin: {{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'Edit profile',
    adEtiket: 'Full name',
    adYerTutucu: 'Your full name',
    adHata: 'Enter your full name.',
    kullaniciAdiEtiket: 'Username',
    biyografiEtiket: 'Bio',
    biyografiYerTutucu: 'Tell a little about yourself',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'your username',
    instagramIpucu: 'You can also paste a link. Not verified; shown as a link on your profile.',
    bolgeEtiket: 'Where you live',
    bolgeSecilmedi: 'Not selected',
    bolgeIpucu: 'Optional. If you choose one, it appears on your profile.',
    bolgeIlSec: 'Select province',
    bolgeIlceSec: 'Select district',
    bolgeKaldir: 'Remove region',
    instagramHata: 'An Instagram username consists of letters, digits, dots and underscores; it cannot start or end with a dot.',
    kaydediliyor: 'Saving…',
    kaydedildi: 'Your profile was updated.',
  },
  ayarlar: {
    baslik: 'Settings',
    geri: 'Back',
    profilGizli: 'Private profile',
    profilGizliAciklama: 'When on, your memories and check-ins are visible only to your friends. Your name, username and photo stay public so people can find you and send a friend request.',
    verilerimiIndir: 'Download my data',
    verilerimiIndirHazirlaniyor: 'Preparing…',
    verilerimiIndirHata: 'The data could not be prepared. Try again.',
    gizlilikMetni: 'Privacy policy',
    bolumGorunurluk: 'Privacy settings',
    aniGorunurlugu: 'My past memories',
    etiketOnayi: 'Ask me before tagging',
    etiketOnayiAciklama: 'When off, your friends can tag you directly. When on, you are asked first; no one sees the tag until you approve.',
    aramadaGorun: 'Show me in search',
    aramadaGorunEtiket: 'Search visibility',
    bolumKisiler: 'People',
    engellenenler: 'Blocked',
    bolumHesapIslemleri: 'Account',
    dondur: 'Freeze my account',
    dondurAciklama: 'Your data is not deleted. Your account is reactivated automatically the next time you sign in.',
    dondurEvet: 'Yes, freeze',
    vazgec: 'Cancel',
    hesabiSil: 'Delete my account',
    cikisYap: 'Sign out',
    aniHerkeseAcik: 'Everyone',
    aniTakipcilerim: 'Only my followers',
    aniKimse: 'No one',
    secilmedi: 'Not selected',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'New username',
    sonrakiDegisim: 'You can change it again on: {{tarih}}',
  },
  aniGorunurlugu: {
    baslik: 'My past memories',
    geri: 'Back',
    aciklama: 'This choice applies to all your memories, but memories that came from a hidden check-in are not affected and stay private.',
  },
  engellenenler: {
    baslik: 'Blocked',
    engeliKaldir: 'Unblock',
    bosBaslik: "You haven't blocked anyone",
    bosAciklama: 'If you block someone, they appear here and you can undo it from here.',
    geri: 'Back',
  },
  profil: {
    yerSayisi: 'Places',
    duzenle: 'Edit profile',
    paylas: 'Share',
    paylasilamadi: 'Sharing could not be opened on this device.',
    sekmeAnilar: 'Memories',
    sekmeYerler: 'Most visited',
    sekmeFotograflar: 'Photos',
    fotografSayisi: 'Photos',
    bosFotografBaslik: 'No photos yet',
    bosFotografAciklama: 'If you add photos while checking in, they all gather here.',
    bosArkadasBaslik: 'No friends yet',
    kezSayisi: '{{sayi}} times',
    bosYerBaslik: "You haven't been anywhere yet",
    bosYerAciklama: 'As you check in, the places you visit most are ranked here.',
    ayarlar: 'Settings',
    fotografEkle: 'Add profile photo',
    fotografiBuyut: 'Enlarge profile photo',
    fotografKaldir: 'Remove photo',
    fotografKaldirOnay: 'Remove your photo?',
    kapat: 'Close',
    aniSayisi: 'Memories',
    bagSayisi: 'Friends',
    canliEtiket: "You're here now",
    ayril: 'Leave',
    canliSil: 'Delete',
    canliSilOnay: 'Permanently delete this check-in? It will not remain in your memories either.',
    bosCanliBaslik: "You're not anywhere right now",
    bosCanliAciklama: 'Check in where you are and see the people who are there at that very moment.',
    checkInYap: 'Check in somewhere',
    anilarBaslik: 'Memories',
    bosAniBaslik: 'No memories yet',
    bosAniAciklama: 'Your check-ins stay here as memories.',
    profilYok: 'Your profile is not ready yet',
    profilYokAciklama: 'Set your name and username, then continue from here.',
    profilOlustur: 'Create your profile',
  },
  dogrula: {
    geri: 'Back',
    baslik: 'Verify your email',
    aciklama: 'We sent a 6-digit code to {{eposta}}.',
    kodEtiketi: 'Verification code',
    gonder: 'Verify',
    gonderiliyor: 'Verifying…',
    kodGelmedi: "Didn't get the code?",
    spamNotu: "If it's not in your inbox, check your spam folder too.",
    tekrarGonder: 'Resend',
    tekrarBekle: 'You can resend in {{saniye}} s',
    tekrarGonderildi: 'A new code was sent.',
    hakKalmadi: 'Too many codes were requested for this address. You can try again in an hour.',
    hataEksik: 'Enter the whole code.',
    zatenKayitliBaslik: 'There is already an account with this address',
    zatenKayitliAciklama: 'An account was already created with {{eposta}}. You can sign in with your password.',
    girisYap: 'Sign in',
    baskaNumara: 'Continue with another address',
  },
  altGezinme: {
    anaSayfa: 'Home',
    bildirimler: 'Notifications',
    mesajlar: 'Messages',
    profil: 'Profile',
  },
  arkadasSecici: {
    baslik: 'Tag your friends',
    bos: "You don't have any friends yet. Once you send a friend request and it's accepted, they appear here and you can tag them in your check-ins.",
    tamamSayili: 'Done ({{sayi}})',
  },
  harita: {
    cevre: 'Places around you',
    kisiBurada: '{{ad}}, {{sayi}} people here',
    buMekan: 'This place, {{durum}}',
    buradasin: 'You are here',
  },
  sikayet: {
    baslik: 'Report',
    sebepSec: 'Choose a reason',
    alindi: 'Your report was received',
    tesekkur: 'Thank you for letting us know.',
    mesajBaglami: 'During review, the messages around this one are also opened to moderation.',
    aciklamaYerTutucu: 'Anything you want to add?',
    sebepler: {
      taciz: 'Harassment or bullying',
      uygunsuz_icerik: 'Inappropriate content',
      sahte_hesap: 'Fake account',
      spam: 'Spam or advertising',
      diger: 'Other',
    },
  },
  hesapDurumu: {
    askida: 'Your account is suspended',
    yasakli: 'Your account has been permanently closed',
    sebep: 'Reason: {{sebep}}',
    bitis: 'Ends: {{tarih}}',
    ipucu: 'During this time your profile is not visible to others and you cannot post new content. Your data has not been deleted.',
    yenile: 'Refresh',
    cikisYapilamadi: 'Could not sign out',
  },
  checkIn: {
    baslik: 'New check-in',
    notYerTutucu: 'Add a note (optional)',
    ilkUyariBaslik: 'What does this check-in share?',
    ilkUyariMetin: 'When you check in, the place you are at and your note (if any) become visible to your friends. It closes by itself when the check-in expires or the moment you say "I left". If you like, you can make this check-in hidden and keep it only on your own profile.',
    anladim: 'Got it',
    gizliYap: 'Make hidden',
    arkadasEkle: 'Add friends (optional)',
    arkadasEkleSecili: 'Add friends ({{sayi}} selected)',
    etiketiKaldir: 'Remove tag {{ad}}',
    fotografEkle: 'Add photo (optional)',
    fotografDegistir: 'Change photo',
    fotografCek: 'Take a photo',
    galeridenSec: 'Choose from gallery',
    kameraIzni: 'Camera permission is needed to take a photo.',
    fotografYuklenemedi: 'The photo could not be uploaded; you checked in with your note',
    etiketlenemedi: 'You checked in, but your friends could not be tagged.',
    gonder: 'Check in',
    gonderiliyor: 'Checking in...',
  },
  mekanDuzenle: {
    baslik: 'Fix the details',
    aciklama: 'Is something wrong? Your correction goes to a moderator; once approved, it is updated for everyone.',
    gonderildiBaslik: 'Your request was sent',
    gonderildiMetin: 'The place details will be updated once a moderator reviews and approves.',
    bekleyenBaslik: 'You have a pending request',
    bekleyenMetin: 'The request you sent for this place is still under review. You can send a new correction once it is resolved.',
    adEtiket: 'Place name',
    adYerTutucu: 'Name of the place',
    mahalle: 'Neighbourhood',
    mahalleYerTutucu: 'e.g. Alaaddinbey',
    adres: 'Address',
    adresYerTutucu: 'Street, number',
    il: 'Province',
    ilYerTutucu: 'Bursa',
    ilce: 'District',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Type',
    kapakFotografi: 'Cover photo',
    fotografiKaldir: 'Remove photo',
    fotografEkle: 'Add photo',
    fotografSecilemedi: 'The photo could not be selected.',
    galeriIzni: 'Photo permission is needed to choose from the gallery.',
    oturumYok: 'Session not found',
    zatenKapali: 'This place is already marked as permanently closed.',
    kapaliBaslik: 'This place is permanently closed',
    kapaliAciklama: 'If approved, this place is removed from lists and search. Check-ins made here are not deleted.',
    onceDegistir: 'Change something first.',
    talebiGonder: 'Send request',
  },
  mekanEkle: {
    baslik: 'Add a new place',
    adYerTutucu: 'Place name',
    turuSec: 'Choose a type',
    adresYerTutucu: 'Address (optional)',
    adresSoru: 'Is this address correct?',
    adresAciklama: 'Found from your location. If it is wrong, you can edit the field above.',
    dogru: 'Correct',
    benzerBaslik: 'Did you mean one of these?',
    konumAlinamadi: 'Could not get your location, try again',
    adVeTurGerekli: 'Place name and type are required',
    ekle: 'Add',
    ekleniyor: 'Adding...',
  },
  turGruplari: {
    'Yeme içme': 'Food & drink',
    Gece: 'Nightlife',
    'Açık alan': 'Outdoors',
    Kültür: 'Culture',
    Spor: 'Sports',
    Alışveriş: 'Shopping',
    Diğer: 'Other',
  },
  turler: {
    Kafe: 'Café',
    Kahveci: 'Coffee shop',
    'Çay evi': 'Tea house',
    Restoran: 'Restaurant',
    Lokanta: 'Diner',
    'Türk mutfağı': 'Turkish cuisine',
    Kebapçı: 'Kebab house',
    'Balık restoranı': 'Seafood restaurant',
    Ocakbaşı: 'Grill house',
    'Kahvaltı salonu': 'Breakfast place',
    Fırın: 'Bakery',
    'Fast food': 'Fast food',
    Burgerci: 'Burger joint',
    Pizzacı: 'Pizzeria',
    Tatlıcı: 'Dessert shop',
    Dondurmacı: 'Ice cream shop',
    Bar: 'Bar',
    Pub: 'Pub',
    'Gece kulübü': 'Nightclub',
    Meyhane: 'Tavern',
    'Nargile kafe': 'Hookah lounge',
    'Kokteyl barı': 'Cocktail bar',
    Park: 'Park',
    'Halk bahçesi': 'Public garden',
    'Doğal alan': 'Nature area',
    Plaj: 'Beach',
    Meydan: 'Square',
    'Kamp alanı': 'Campsite',
    Göl: 'Lake',
    Müze: 'Museum',
    Sinema: 'Cinema',
    Tiyatro: 'Theatre',
    'Sanat galerisi': 'Art gallery',
    Kütüphane: 'Library',
    'Tarihi yer': 'Historic site',
    'Konser salonu': 'Concert hall',
    'Kültür merkezi': 'Cultural centre',
    'Spor salonu': 'Gym',
    Stadyum: 'Stadium',
    'Yüzme havuzu': 'Swimming pool',
    'Halı saha': 'Football pitch',
    AVM: 'Shopping mall',
    Market: 'Supermarket',
    Bakkal: 'Grocery',
    'Giyim mağazası': 'Clothing store',
    Kitapçı: 'Bookshop',
    Kuyumcu: 'Jeweller',
    Otel: 'Hotel',
    Eczane: 'Pharmacy',
    Hastane: 'Hospital',
    Banka: 'Bank',
    Kuaför: 'Hair salon',
    'Güzellik salonu': 'Beauty salon',
    Üniversite: 'University',
    'Canlı müzik': 'Live music',
  },
  kesfet: {
    baslik: 'Check-in',
    harita: 'Map',
    liste: 'List',
    turSuzgeci: 'Type filter',
    turFiltresi: 'Type filter',
    turBulunamadi: 'No types to show around you.',
    filtreyiKaldir: 'Remove filter',
    tumunuSec: 'Select all',
    temizle: 'Clear',
    kaydet: 'Save',
    kaydetSayili: 'Save ({{sayi}})',
    tumu: 'All',
    sakin: 'Quiet',
    yogun: 'Busy',
    populer: 'Popular',
    yakinindakiMekanlar: 'Places Near You',
    sonuclar: 'Results',
    kisiBurada: '{{sayi}} people here',
    checkIn: 'Check-in',
    konumuGor: 'View location',
    checkInYap: 'Check in here',
    mekanAra: 'Search places',
    kisi: '{{sayi}} people',
    taraniyor: 'Scanning around you…',
    cevreGorunmuyor: "We can't see around you",
    konumIzniAciklama: 'We need location permission to show the places near you. Turn it on in your browser settings and try again.',
    konumuAc: 'Open {{ad}}',
    konumuGorEtiketi: 'View {{ad}}',
    checkInEtiketi: 'Check in at {{ad}}',
    filtreyiKaldirEtiketi: 'Remove the {{tur}} filter',
    kisiBuradaEtiket: 'people here',
    suAnBuradasin: "You're here now",
    ayrildim: 'I left',
    araniyor: 'Searching…',
    aramaBulunamadi: 'No place found for “{{arama}}”. Try changing the spelling.',
    sonucSayisi: '{{sayi}} results',
    bosArama: 'No results for "{{arama}}" in this province.',
    bosFiltre: 'No places within 500 m with this filter.',
    bosCevre: 'No places near you.',
    mekanEkle: "Can't find a place? Add it",
    atif: 'Place data: Foursquare · Neighbourhood and district: © OpenStreetMap contributors',
  },
  checkInHaritasi: {
    geri: 'Back',
    haritaAcikla: 'Tap the map to get directions',
    haritadaAc: 'Get directions',
    secimBaslik: 'Which map should we open?',
    appleHaritalar: 'Apple Maps',
    googleHaritalar: 'Google Maps',
    vazgec: 'Cancel',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Photo of {{ad}}',
    menu: 'Options',
    yolTarifi: 'Get directions',
    buradaCheckIn: 'Check in here',
    yaklas: 'Get closer to check in · {{mesafe}}',
    buradasinAyril: "You're here · Leave",
    kapandi: 'This place is permanently closed',
    kapandiAciklama: 'You can no longer check in here and the place is not shown in lists. Your past memories remain.',
    kisiBurada: 'people here',
    bugun: 'Today',
    haritadaGoster: 'Show location on the map',
    checkInSayisi: '{{sayi}} check-ins',
    kisiSayisi: '{{sayi}} people',
    ilcedekiYerler: 'places in {{ilce}}',
    siralamaYok: 'No ranking',
    suAnBurada: 'Here now',
    diger: 'Other',
    biri: 'Someone',
    suAn: 'now',
    liderlik: 'Leaders',
    sonCheckInler: 'Recent',
    liderlikBos: 'No check-ins to show here yet.',
    sonBos: 'No check-ins to show here yet.',
    fotograflar: 'Photos',
    fotografBos: 'No photos here yet.',
    fotografAc: 'Enlarge photo',
    dahaFazlaFotograf: 'More photos',
    puan: 'Rating',
    puanlamaSayisi: '{{sayi}} ratings',
    puanYok: 'No rating yet',
    puanAzOy: 'At least 3 ratings are needed for a score',
    puanKotu: 'Bad',
    puanIyi: 'Good',
    puanHarika: 'Great',
    puanSoru: 'How did you find this place?',
    puanSart: 'Check in here first to rate it.',
    puanGonder: 'Submit',
    puanGuncelle: 'Update your rating',
    puanGonderiliyor: 'Sending…',
    puanTesekkur: 'Your rating was saved.',
  },
  giris: {
    epostaYerTutucu: 'Email address',
    sifreYerTutucu: 'Password',
    gonder: 'Sign in',
    gonderiliyor: 'Signing in…',
    kayitOl: 'Create a new account',
    hataEposta: 'Enter a valid email address.',
    hataBos: 'Enter your email address and password.',
    sifremiUnuttum: 'Forgot your password?',
  },
  sifreSifirla: {
    geri: 'Back',
    baslik: 'Reset your password',
    aciklama: "Enter your account's email address and we'll send you a 6-digit code.",
    epostaYerTutucu: 'Email address',
    kodGonder: 'Send code',
    gonderiliyor: 'Sending…',
    hataEposta: 'Enter a valid email address.',
    hataHesapYok: 'No account was found with this email address.',
    kodBaslik: 'Enter the code',
    kodAciklama: 'We sent a 6-digit code to {{eposta}}.',
    kodEtiketi: 'Verification code',
    dogrula: 'Verify',
    dogrulaniyor: 'Verifying…',
    hataEksik: 'Enter the whole code.',
    kodGelmedi: "Didn't get the code?",
    spamNotu: "If it's not in your inbox, check your spam folder too.",
    tekrarGonder: 'Resend',
    tekrarBekle: 'You can resend in {{saniye}} s',
    tekrarGonderildi: 'A new code was sent.',
    hakKalmadi: 'Too many codes were requested for this address. You can try again in an hour.',
    yeniBaslik: 'Set your new password',
    yeniAciklama: 'The code was verified. Now choose a new password.',
    sifreYerTutucu: 'New password (at least {{adet}} characters)',
    sifreTekrarYerTutucu: 'New password (again)',
    kaydet: 'Save password',
    kaydediliyor: 'Saving…',
    hataSifreKisa: 'The password must be at least {{adet}} characters.',
    hataSifreEslesmiyor: 'The passwords do not match.',
  },
  hatalar: {
    genel: 'Something went wrong. Try again in a bit.',
    kullaniciAdi30Gun: 'You can change your username once every 30 days. {{gun}} days left.',
    vt: {
      aski_bitisi_gelecekte_olmali: 'The suspension end must be in the future.',
      bir_moderatore_islem_uygulanamaz: 'Actions cannot be applied to a moderator.',
      bu_kisiye_su_an_mesaj_gonderemezsin: "You can't message this person right now.",
      bu_kullanici_adi_alinmis: 'This username is taken, try another one.',
      bu_kullanici_bulunamadi: 'This user was not found.',
      bu_fotograf_sana_ait_degil: 'This photo does not belong to you.',
      bu_il_listemizde_yok: 'This province is not in our list.',
      bu_mekan_bulunamadi: 'This place was not found.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'The request you sent for this place is still under review.',
      bu_mekan_kalici_olarak_kapandi: 'This place is permanently closed.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'This place is already marked as closed.',
      bu_tur_listemizde_yok: 'This type is not in our list.',
      en_az_bir_alan_doldurulmali: 'You need to change at least one detail.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'You reached the daily correction limit (5). You can try again tomorrow.',
      hesabin_su_an_bu_islemi_yapamaz: 'Your account cannot do this right now.',
      bu_paylasim_bulunamadi: 'This post was not found.',
      not_en_fazla_500_karakter_olabilir: 'The note can be at most 500 characters.',
      bu_mesaji_sikayet_edemezsin: "You can't report this message.",
      bugunluk_istek_sinirina_ulastin: "You reached today's request limit.",
      check_in_bulunamadi: 'Check-in not found.',
      cok_fazla_kimlik: 'Too many identifiers were sent.',
      en_az_2_karakter_gerekli: 'Type at least 2 characters.',
      gecersiz_bulunurluk_degeri: 'Invalid availability value.',
      gecersiz_gorunurluk_degeri: 'Invalid visibility value.',
      gecersiz_platform: 'Invalid platform.',
      gecersiz_sikayet_durumu: 'Invalid report status.',
      gecersiz_sikayet_hedefi: 'Invalid report target.',
      gerekce_belirtilmeli: 'You need to give a reason.',
      geri_cekilecek_istek_bulunamadi: 'No request to withdraw was found.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'You reached the daily limit for adding places (5). You can try again tomorrow.',
      hesabin_su_anda_kullanilamiyor: 'Your account is not available right now.',
      hesabin_zaten_kullanilamaz_durumda: 'Your account is already unavailable.',
      istegin_zaten_gonderilmis: 'Your request was already sent.',
      jeton_bos_olamaz: 'The notification token cannot be empty.',
      jeton_cok_uzun: 'The notification token is too long.',
      kendi_mesajini_sikayet_edemezsin: "You can't report your own message.",
      kendine_islem_uygulayamazsin: "You can't apply an action to yourself.",
      kendine_istek_gonderemezsin: "You can't send a request to yourself.",
      kendine_mesaj_gonderemezsin: "You can't message yourself.",
      kendini_engelleyemezsin: "You can't block yourself.",
      kendini_sikayet_edemezsin: "You can't report yourself.",
      kimlik_dogrulamasi_gerekli: 'You need to be signed in for this.',
      konusma_bulunamadi: 'Conversation not found.',
      kullanici_adi_kurallara_uymuyor: 'The username does not follow the rules.',
      kullanici_belirtilmeli: 'A user must be specified.',
      mekan_bulunamadi: 'Place not found.',
      gecersiz_puan: 'Invalid rating.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'Check in here first to rate it.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'You are too far from the place. To check in you need to be within about 1 kilometre.',
      mekana_yakin_olmalisin_200_m_icinde: 'To add a place you need to be within about 200 metres of it.',
      mesaj_bos_olamaz: 'The message cannot be empty.',
      mesaj_bu_konusmada_bulunamadi: 'The message was not found in this conversation.',
      mesaj_cok_uzun: 'The message is too long.',
      profil_bulunamadi: 'Profile not found.',
      sikayet_bulunamadi: 'Report not found.',
      sikayet_sebebi_belirtilmeli: 'You need to give a reason for the report.',
      yanitlanacak_istek_bulunamadi: 'No request to answer was found.',
      yetkisiz: "You don't have permission for this.",
      zaten_bu_kullanici_adini_kullaniyorsun: 'You are already using this username.',
    },
    kod: {
      '23505': 'This record already exists.',
      '57014': 'The operation timed out. Try again.',
      otp_expired: 'The code is invalid or expired. Request a new one.',
      user_already_exists: 'There is already an account with this address. You can sign in.',
      invalid_credentials: 'Wrong email address or password.',
      over_request_rate_limit: 'You tried too often. Wait a bit and try again.',
      over_sms_send_rate_limit: 'Too many codes were requested. Wait a bit and try again.',
      weak_password: 'The password is too weak. Choose a stronger one.',
      same_password: 'The new password must be different from the old one.',
      signup_disabled: 'New sign-ups are not accepted right now.',
      phone_provider_disabled: 'A code cannot be sent to this number right now. Try again later.',
    },
    metin: {
      sms_saglayici: 'A code cannot be sent to this number right now. Try again later.',
      sms_saglayici2: 'A code cannot be sent to this number right now. Try again later.',
      kod_gecersiz: 'The code is invalid or expired. Request a new one.',
      zaten_kayitli: 'There is already an account with this address. You can sign in.',
      giris_hatali: 'Wrong email address or password.',
      cok_sik: 'You tried too often. Wait a bit and try again.',
      sifre_kisa: 'The password is too short.',
      sifre_ayni: 'The new password must be different from the old one.',
      kayit_kapali: 'New sign-ups are not accepted right now.',
      ag_yok: 'Could not reach the internet. Check your connection and try again.',
      oturum_dustu: 'Your session has expired. Sign in again.',
    },
  },
} as const
