/**
 * Textos en espanol. Refleja 1:1 la estructura de claves de `tr.ts`;
 * una clave ausente cae al turco y el test de paridad
 * (`__tests__/ceviri-tamlik.test.ts`) senala cualquier desvio.
 */
export default {
  // HUKUKI EKRANLAR (i18n E asamasi, 2026-09-13): basliklar ve
  // "Turkce metin esastir" notu. Belgelerin kendisi lib/hukuki/ altinda.
  hukuki: {
    gizlilikBaslik: 'Aviso de privacidad',
    kosullarBaslik: 'Condiciones de uso',
    sonGuncelleme: 'Última actualización: {{tarih}}',
    ustunlukNotu: 'El texto vinculante de este documento es la versión en turco; esta traducción es solo informativa.',
  },

  ortak: {
    devam: 'Continuar',
    iptal: 'Cancelar',
    tumunuSec: 'Seleccionar todo',
    temizle: 'Limpiar',
    kaydet: 'Guardar',
    tekrarDene: 'Intentar de nuevo',
    yukleniyor: 'Cargando…',
    birSorunOldu: 'Algo salió mal.',
    agYok: 'Sin conexión a internet, inténtalo de nuevo',
    gonder: 'Enviar',
    gonderiliyor: 'Enviando…',
    tamam: 'Listo',
    sira: 'Puesto {{sira}}',
    sil: 'Eliminar',
    vazgec: 'Cancelar',
    geri: 'Atrás',
    kapat: 'Cerrar',
    ara: 'Buscar',
    sonucYok: 'Sin resultados.',
  },
  karsilama: {
    baslik: 'Mira quién está cerca, ',
    baslikVurgu: 'explora.',
    aciklama: 'Haz check-in, conoce gente nueva.\nDescubre los lugares populares a tu alrededor.',
    kisiSayisi: '{{sayi}} personas',
    disarida: '{{sayi}} personas cerca de ti',
    turKafe: 'Café',
    turRestoran: 'Restaurante',
    turBar: 'Bar',
    adim1Baslik: 'Haz check-in',
    adim1Aciklama: 'Hazte visible en el lugar donde estás',
    adim2Baslik: 'Quién está cerca',
    adim2Aciklama: 'Descubre a la gente del mismo lugar',
    adim3Baslik: 'Chatea',
    adim3Aciklama: 'Conoce gente nueva',
    adim4Baslik: 'Descubre lugares populares',
    adim4Aciklama: 'Mira los sitios de moda de tu ciudad',
    hesapOlustur: 'Crear cuenta',
    hesabinVarMi: '¿Ya tienes cuenta?',
    girisYap: 'Iniciar sesión',
    haritaAtfi: 'Datos del mapa © colaboradores de OpenStreetMap',
  },
  kayit: {
    baslik: 'Empieza con tu correo',
    epostaEtiket: 'Correo electrónico',
    epostaYerTutucu: 'nombre@ejemplo.com',
    devam: 'Continuar',
    veya: 'o',
    appleIle: 'Continuar con Apple',
    googleIle: 'Continuar con Google',
    hataEposta: 'Introduce un correo válido.',
    hataEpostaKayitli: 'Ya hay una cuenta con este correo. Puedes iniciar sesión con tu contraseña.',
    hataSaglayiciKapali: 'Este método de acceso no está disponible ahora. Puedes continuar con tu correo.',
    telefonEtiket: 'Número de teléfono',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Enviar código',
    gonderiliyor: 'Enviando…',
    zatenHesap: '¿Ya tienes cuenta?',
    girisYap: 'Iniciar sesión',
    hataTelefon: 'Introduce un número de teléfono válido.',
    hataZatenKayitli: 'Ya hay una cuenta con este número. Puedes iniciar sesión con tu contraseña.',
  },
  profilOlustur: {
    baslik: 'Crear cuenta',
    adYerTutucu: 'Tu nombre completo',
    adHata: 'Introduce tu nombre completo.',
    dogumEtiket: 'Fecha de nacimiento',
    dogumSec: 'Día / Mes / Año',
    dogumHataGecersiz: 'Selecciona tu fecha de nacimiento.',
    dogumHataYas: 'Debes tener al menos 18 años para usar Slooin.',
    tarihGun: 'Día',
    tarihAy: 'Mes',
    tarihYil: 'Año',
    tarihTamam: 'Listo',
    aylar: {
      1: 'Enero',
      2: 'Febrero',
      3: 'Marzo',
      4: 'Abril',
      5: 'Mayo',
      6: 'Junio',
      7: 'Julio',
      8: 'Agosto',
      9: 'Septiembre',
      10: 'Octubre',
      11: 'Noviembre',
      12: 'Diciembre',
    },
    kullaniciAdiYerTutucu: 'Nombre de usuario',
    kullaniciAdiIpucu: 'El nombre de usuario no cumple el formato requerido.',
    kullaniciAdiKontrol: 'Comprobando…',
    kullaniciAdiMusait: 'Este nombre de usuario está disponible.',
    kullaniciAdiAlinmis: 'Este nombre de usuario ya está en uso, prueba otro.',
    sifreEtiket: 'Contraseña',
    sifreYerTutucu: 'Al menos {{adet}} caracteres',
    tekrarEtiket: 'Repetir contraseña',
    tekrarYerTutucu: 'La misma contraseña otra vez',
    sifrelerFarkli: 'Las contraseñas aún no coinciden.',
    sifreGoster: 'Mostrar contraseña',
    sifreGizle: 'Ocultar contraseña',
    hataSifreKisa: 'La contraseña debe tener al menos {{adet}} caracteres.',
    hataSifreUyusmuyor: 'Las contraseñas no coinciden. Revisa ambas.',
    adimSayaci: 'Paso {{simdiki}} / {{toplam}}',
    adim1Baslik: 'Vamos a conocerte',
    adim1Aciklama: 'Tu nombre aparece en tu perfil. Tu fecha de nacimiento nunca se muestra a nadie.',
    adEtiket: 'Nombre completo',
    adOrnek: 'p. ej. Ana García',
    yasNotu: 'Slooin es para mayores de 18 años.',
    adim2Baslik: 'Elige tu nombre de usuario',
    adim2Aciklama: 'De 3 a 20 caracteres; puede incluir minúsculas, dígitos, puntos y guiones bajos.',
    kullaniciAdiEtiket: 'Tu nombre de usuario',
    // BOLGE ADIMI (kullanicinin istegi 2026-09-18): ulke -> il -> ilce; ZORUNLU, ayarlardan gizlenebilir.
    adim3Baslik: 'Dónde vives',
    adim3Aciklama: 'Nunca se muestra en tu perfil; solo se guarda con tu cuenta.',
    bolgeUlkeEtiket: 'País',
    bolgeUlkeSec: 'Elegir país',
    bolgeIlEtiket: 'Provincia y distrito',
    bolgeIlSec: 'Elegir provincia',
    bolgeIlceSec: 'Elegir distrito',
    bolgeYalnizcaUlke: 'No hay lista de provincias/distritos para este país; solo se guarda el país.',
    bolgeHata: 'Elige tu provincia y distrito.',

    adim4Baslik: 'Crea tu contraseña',
    adim4Aciklama: 'Iniciarás sesión con esta contraseña.',
    sifreUygun: 'La contraseña tiene la longitud suficiente.',
    sifrelerAyni: 'Las contraseñas coinciden.',
    devam: 'Continuar',
    sozlesmeNotuOn: 'Al crear una cuenta confirmas que aceptas los ',
    sozlesmeKosullar: 'Términos de uso',
    sozlesmeNotuOrta: ' y que has leído la ',
    sozlesmeGizlilik: 'Política de privacidad',
    sozlesmeNotuSon: '.',
    gonder: 'Crear cuenta',
    gonderiliyor: 'Creando…',
    oturumDustu: 'Tu sesión ha caducado, inicia sesión de nuevo.',
    beklenmeyenHata: 'Se produjo un error inesperado.',
  },
  bildirimler: {
    baslik: 'Notificaciones',
    arkadaslikBolumu: 'Solicitudes de amistad',
    etiketBolumu: 'Solicitudes de etiqueta',
    arkadaslikMetni: 'quiere ser tu amigo.',
    etiketMetni: 'quiere etiquetarte en un check-in en {{mekan}}.',
    kabul: 'Aceptar',
    onayla: 'Aprobar',
    reddet: 'Rechazar',
    bosBaslik: 'Nada nuevo',
    bosAciklama: 'Las solicitudes de amistad y las personas que quieren etiquetarte aparecen aquí.',
  },
  kisiler: {
    baslik: 'Buscar personas',
    yerTutucu: 'Nombre de usuario o nombre',
    enAzIki: 'Escribe al menos 2 caracteres.',
    bulunamadi: 'No se encontró a nadie.',
    ipucu: 'Puedes buscar a alguien por su nombre de usuario o su nombre.',
  },
  arkadaslar: {
    baslik: 'Mis amigos',
    ara: 'Buscar por nombre o usuario',
    sayi: '{{sayi}} amigos',
    profiliGor: 'Ver perfil',
    mesajGonder: 'Enviar mensaje',
    davetBaslik: 'Descubre con tus amigos',
    davetMetin: 'Invita a tus amigos a Slooin.',
    davetDugme: 'Invitar amigos',
    davetMesaji: 'Únete a mí en Slooin 👋',
  },
  baglar: {
    baslik: 'Amigos',
    arkadasliktanCikar: 'Eliminar amigo',
    bosArkadas: 'Aún no tienes amigos',
    engelle: 'Bloquear',
  },
  mesajlar: {
    baslik: 'Mensajes',
    bosBaslik: 'Aún no hay conversaciones',
    silinmisKullanici: 'Usuario eliminado',
    sil: 'Eliminar',
    istekler: 'Solicitudes',
    istekRozeti: 'Solicitud',
    silBaslik: 'Eliminar conversación',
  },
  mesajIstekleri: {
    baslik: 'Solicitudes',
    aciklama: 'Los mensajes de personas que no son tus amigos esperan aquí. Si respondes, el chat pasa a Mensajes.',
    bosBaslik: 'No hay solicitudes pendientes',
    bosAciklama: 'Si alguien que no es tu amigo te escribe, verás el mensaje aquí.',
    kabul: 'Aceptar',
    reddet: 'Rechazar',
    geri: 'Mensajes',
  },
  hesabiSil: {
    baslik: 'Eliminar cuenta',
    soru: '¿Seguro que quieres eliminar tu cuenta?',
    uyari: 'Esto no se puede deshacer. Si quieres volver, tendrás que crear una cuenta nueva.',
    araSoru: '¿Solo necesitas un descanso?',
    dondur: 'Congelar mi cuenta',
    dogrulaBaslik: 'Verifica tu identidad',
    dogrulaAciklama: 'Verifica tu cuenta para continuar con la eliminación.',
    epostaEtiket: 'Tu correo electrónico',
    kodNot: 'Se enviará un código de 6 dígitos a esta dirección.',
    gizliAppleAdresi: 'El código de 6 dígitos se reenvía al correo vinculado a tu cuenta de Apple.',
    kodGonder: 'Enviar código de confirmación',
    kodGonderildi: 'Código enviado; válido durante 10 minutos.',
    kodYerTutucu: 'Código de 6 dígitos',
    kodEksik: 'Introduce los 6 dígitos del código.',
    tekrarGonder: 'Reenviar código',
    epostaYok: 'Tu cuenta no tiene correo electrónico. Escribe a destek@slooin.com.',
    appleIleDogrula: 'Confirmar con Apple',
    googleIleDogrula: 'Confirmar con Google',
    sil: 'Eliminar mi cuenta definitivamente',
  },
  sohbet: {
    baslik: 'Chat',
    istekSeridi: 'Esta es una solicitud de mensaje. Si respondes, el chat pasa a Mensajes.',
    kabulEt: 'Aceptar',
    reddet: 'Rechazar',
    mesajYok: 'Aún no hay mensajes',
    yerTutucu: 'Escribe un mensaje...',
    kapaliKapi: 'Ahora mismo no puedes escribir a esta persona.',
    teslimEdildi: 'Entregado',
    bugun: 'Hoy',
    dun: 'Ayer',
  },
  etkilesim: {
    profiliGor: 'Ver el perfil de {{ad}}',
    begen: 'Me gusta',
    begeniyiKaldir: 'Ya no me gusta',
    yorumlar: 'Comentarios',
    yorumSayisi: '{{sayi}} comentarios',
    yorumYaz: 'Escribe un comentario…',
    gonder: 'Enviar',
    paylas: 'Compartir',
    yorumSil: 'Eliminar comentario',
    yorumSilOnay: '¿Eliminar este comentario?',
    yorumSikayet: 'Denunciar',
    yorumSikayetOnay: '¿Denunciar este comentario? Un comentario denunciado se oculta de inmediato y lo revisa el equipo de moderación.',
    yorumSikayetEdildi: 'Tu denuncia se ha recibido y el comentario se ha ocultado.',
    bosYorumBaslik: 'Aún no hay comentarios',
    bosYorumAciklama: 'Puedes escribir el primero.',
    silinmisKullanici: 'Usuario eliminado',
  },
  anaSayfa: {
    birlikte: 'Con',
    aramaYerTutucu: 'Buscar',
    suAnDisarida: 'Fuera ahora mismo',
    disaridaSayi: '{{sayi}} personas',
    disaridaDiger: 'Otros',
    disaridaErisim: '{{ad}}, en {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'aquí ahora',
    bosBaslik: 'Tu feed está vacío',
    bosAciklama: 'Haz check-in en algún sitio o haz amigos; sus check-ins aparecerán aquí.',
    kesfet: 'Explorar lugares',
    azOnce: 'ahora mismo',
    dakika: 'hace {{sayi}} min',
    saat: 'hace {{sayi}} h',
    gun: 'hace {{sayi}} d',
    silOnay: '¿Eliminar este check-in definitivamente?',
    silAciklama: 'El check-in, su nota y su foto se eliminan definitivamente. Tampoco quedará en tus recuerdos; esto no se puede deshacer.',
    silAriza: 'No se pudo eliminar el check-in.',
    haritadaGor: 'Ver {{ad}} en el mapa',
    secenekler: 'Opciones de la publicación',
    fotografiBuyut: 'Ampliar foto',
    duzenle: 'Editar',
    arkadasEtiketle: 'Etiquetar a un amigo',
    duzenleBaslik: 'Editar publicación',
    notEtiketi: 'Nota',
    notYerTutucu: 'Añadir una nota',
    etiketlenenler: 'Etiquetados',
    etiketiKaldirEtiketi: 'Quitar la etiqueta de {{ad}}',
    duzenleAriza: 'No se pudo actualizar la publicación.',
  },
  kullanici: {
    bulunamadi: 'No se encontró este perfil',
    takipEt: 'Añadir amigo',
    istekBeklemede: 'Pendiente',
    istegiGeriCek: 'Retirar solicitud',
    geriCekOnayi: '¿Quieres retirar tu solicitud de amistad?',
    geriCekEvet: 'Sí, retirar',
    bagiKopar: 'Eliminar amigo',
    gelenIstekAciklama: 'Si aceptas, podréis ver los check-ins del otro y escribiros.',
    kabulEt: 'Aceptar',
    reddet: 'Rechazar',
    anilar: 'Recuerdos',
    enSik: 'Más visitados',
    aniYok: 'Aún no hay recuerdos',
    profilKapali: 'Este perfil es privado',
    profilKapaliAciklama: 'Tenéis que ser amigos para ver sus recuerdos.',
    yerYok: 'Aún no hay lugares',
    fotografYok: 'Aún no hay fotos',
    arkadasYok: 'Aún no tiene amigos',
    secenekler: 'Opciones de perfil',
    sikayetEt: 'Denunciar',
    sikayetEttinNotu: 'Denunciaste a este usuario',
    sikayetEttinAciklama: 'Tu denuncia está en revisión. No puedes volver a denunciar al mismo usuario.',
    engelle: 'Bloquear',
    engelleOnayi: 'Si bloqueas, no os veréis en ningún sitio y todos los mensajes entre vosotros se eliminarán definitivamente. Esto no se puede deshacer.',
    engelleEvet: 'Sí, bloquear',
    vazgec: 'Cancelar',
    geri: 'Atrás',
    fotografiAc: 'Abrir foto',
    mesajYaz: 'Mensaje',
    arkadassin: 'Amigos',
    paylas: 'Compartir perfil',
    paylasMetni: '{{ad}} en Slooin: @{{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'Editar perfil',
    adEtiket: 'Nombre completo',
    adYerTutucu: 'Tu nombre completo',
    adHata: 'Introduce tu nombre completo.',
    kullaniciAdiEtiket: 'Nombre de usuario',
    biyografiEtiket: 'Biografía',
    biyografiYerTutucu: 'Cuenta algo sobre ti',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'tu nombre de usuario',
    instagramIpucu: 'También puedes pegar un enlace. No se verifica; aparece como enlace en tu perfil.',
    instagramHata: 'Un nombre de usuario de Instagram se compone de letras, dígitos, puntos y guiones bajos; no puede empezar ni terminar con un punto.',
    kaydediliyor: 'Guardando…',
    kaydedildi: 'Tu perfil se ha actualizado.',
  },
  ayarlar: {
    baslik: 'Ajustes',
    geri: 'Atrás',
    profilGizli: 'Perfil privado',
    profilGizliAciklama: 'Si está activado, solo tus amigos ven tus recuerdos y check-ins. Tu nombre, nombre de usuario y foto siguen siendo públicos para que puedan encontrarte y enviarte una solicitud de amistad.',
    verilerimiIndir: 'Descargar mis datos',
    verilerimiIndirHazirlaniyor: 'Preparando…',
    verilerimiIndirHata: 'No se pudieron preparar los datos. Inténtalo de nuevo.',
    gizlilikMetni: 'Política de privacidad',
    bolumGorunurluk: 'Ajustes de privacidad',
    etiketOnayi: 'Preguntarme antes de etiquetar',
    etiketOnayiAciklama: 'Si está desactivado, tus amigos pueden etiquetarte directamente. Si está activado, se te pregunta primero; nadie ve la etiqueta hasta que la apruebes.',
    aramadaGorun: 'Mostrarme en la búsqueda',
    aramadaGorunEtiket: 'Visibilidad en la búsqueda',
    bolumKisiler: 'Personas',
    engellenenler: 'Bloqueados',
    bolumHesapIslemleri: 'Cuenta',
    dondur: 'Congelar mi cuenta',
    dondurAciklama: 'Tus datos no se eliminan. Tu cuenta se reactiva automáticamente la próxima vez que inicies sesión.',
    dondurEvet: 'Sí, congelar',
    vazgec: 'Cancelar',
    hesabiSil: 'Eliminar mi cuenta',
    cikisYap: 'Cerrar sesión',
    cikisOnayBaslik: '¿Cerrar sesión?',
    cikisOnayAciklama: 'Cerrarás la sesión de tu cuenta. Puedes volver a iniciar sesión cuando quieras.',
    secilmedi: 'Sin seleccionar',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'Nuevo nombre de usuario',
    sonrakiDegisim: 'Podrás cambiarlo de nuevo el: {{tarih}}',
  },
  engellenenler: {
    baslik: 'Personas bloqueadas',
    engeliKaldir: 'Desbloquear',
    bosBaslik: 'No has bloqueado a nadie',
    bosAciklama: 'Si bloqueas a alguien, aparece aquí y puedes deshacerlo desde aquí.',
    geri: 'Atrás',
    altBaslik: 'Las personas bloqueadas no pueden enviarte mensajes ni solicitudes de amistad.',
    engellendi: 'Bloqueado',
  },
  profil: {
    yerSayisi: 'Lugares',
    duzenle: 'Editar perfil',
    paylas: 'Compartir',
    paylasMetni: 'Agrégame en Slooin 👋',
    paylasilamadi: 'No se pudo abrir la función de compartir en este dispositivo.',
    sekmeAnilar: 'Recuerdos',
    sekmeYerler: 'Más visitados',
    sekmeFotograflar: 'Fotos',
    fotografSayisi: 'Fotos',
    bosFotografBaslik: 'Aún no hay fotos',
    bosFotografAciklama: 'Si añades fotos al hacer check-in, se reúnen todas aquí.',
    bosArkadasBaslik: 'Aún no tienes amigos',
    kezSayisi: '{{sayi}} veces',
    bosYerBaslik: 'Aún no has estado en ningún sitio',
    bosYerAciklama: 'A medida que hagas check-in, aquí se ordenan los lugares que más visitas.',
    ayarlar: 'Ajustes',
    fotografEkle: 'Añadir foto de perfil',
    fotografiBuyut: 'Ampliar foto de perfil',
    fotografKaldir: 'Quitar foto',
    fotografKaldirOnay: '¿Quitar tu foto?',
    kapat: 'Cerrar',
    aniSayisi: 'Recuerdos',
    bagSayisi: 'Amigos',
    canliEtiket: 'Estás aquí ahora',
    ayril: 'Salir',
    canliSil: 'Eliminar',
    canliSilOnay: '¿Eliminar este check-in definitivamente? Tampoco quedará en tus recuerdos.',
    bosCanliBaslik: 'Ahora mismo no estás en ningún sitio',
    bosCanliAciklama: 'Haz check-in donde estés y mira quién está allí en ese preciso momento.',
    checkInYap: 'Hacer check-in en algún sitio',
    anilarBaslik: 'Recuerdos',
    bosAniBaslik: 'Aún no hay recuerdos',
    bosAniAciklama: 'Tus check-ins quedan aquí como recuerdos.',
    profilYok: 'Tu perfil aún no está listo',
    profilYokAciklama: 'Define tu nombre y tu nombre de usuario y continúa desde aquí.',
    profilOlustur: 'Crear tu perfil',
  },
  dogrula: {
    geri: 'Atrás',
    baslik: 'Verifica tu correo',
    aciklama: 'Hemos enviado un código de 6 dígitos a {{eposta}}.',
    kodEtiketi: 'Código de verificación',
    gonder: 'Verificar',
    gonderiliyor: 'Verificando…',
    kodGelmedi: '¿No te llegó el código?',
    spamNotu: 'Si no está en tu bandeja de entrada, revisa también la carpeta de spam.',
    tekrarGonder: 'Reenviar',
    tekrarBekle: 'Puedes reenviar en {{saniye}} s',
    tekrarGonderildi: 'Se ha enviado un nuevo código.',
    hakKalmadi: 'Se han solicitado demasiados códigos para esta dirección. Podrás intentarlo de nuevo en una hora.',
    hataEksik: 'Introduce el código completo.',
    zatenKayitliBaslik: 'Ya hay una cuenta con esta dirección',
    zatenKayitliAciklama: 'Ya se creó una cuenta con {{eposta}}. Puedes iniciar sesión con tu contraseña.',
    girisYap: 'Iniciar sesión',
    baskaNumara: 'Continuar con otra dirección',
  },
  altGezinme: {
    anaSayfa: 'Inicio',
    bildirimler: 'Notificaciones',
    mesajlar: 'Mensajes',
    profil: 'Perfil',
  },
  // HESAP VE GUVENLIK (kullanicinin referans gorselleri 2026-09-18).
  // GIZLILIK VE ETKILESIM (kullanicinin referans gorselleri 2026-09-18).
  gizlilikEtkilesim: {
    bolum: 'Privacidad e interacción',
    gizlilik: 'Privacidad',
    gizlilikAciklama: 'Perfil, etiquetas y bloqueados',
    konum: 'Ubicación y check-in',
    konumAciklama: 'Permiso de ubicación y visibilidad en el lugar',
    bildirimler: 'Notificaciones',
    bildirimlerAciklama: 'Mensajes, amigos y recuerdos',
    gizlilikAlt: 'Tú decides qué compartes y con quién.',
    kartBaslik: 'Tú pones los límites de lo que compartes',
    kartMetin: 'Cada opción dice claramente qué será visible.',
    gorunurlugun: 'Tu visibilidad',
    profilGorunurlugu: 'Visibilidad del perfil',
    profilGorunurluguAciklama: 'Tus recuerdos y check-ins',
    herkeseAcik: 'Público',
    sadeceArkadaslar: 'Solo amigos',
    aramaGorunurlugu: 'Visibilidad en la búsqueda',
    aramaGorunurluguAciklama: 'Te pueden encontrar por tu nombre de usuario',
    acik: 'Activada',
    kapali: 'Desactivada',
    sosyalIzinlerin: 'Permisos sociales',
    etiketler: 'Etiquetas',
    etiketlerAciklama: 'Aprobación y etiquetas pendientes',
    onayli: 'Con aprobación',
    otomatik: 'Automático',
    mesajIzinleri: 'Permisos de mensajes',
    mesajIzinleriAciklama: '¿Quién puede enviarte mensajes?',
    herkes: 'Todos',
    arkadaslar: 'Amigos',
    engellenenKisiler: 'Personas bloqueadas',
    engellenenAciklama: 'Ver y gestionar bloqueos',
    konumAlt: 'Permiso de ubicación y cómo apareces en los lugares.',
    konumIzni: 'Permiso de ubicación',
    konumIzniAciklama: 'Necesario para lugares cercanos y check-in',
    izinVerildi: 'Concedido',
    izinYok: 'No concedido',
    ayarlariAc: 'Abrir ajustes',
    mekandaGorunurluk: 'Visibilidad en el lugar',
    mekandaGorunurlukAciklama: 'Quién te ve en el lugar al hacer check-in',
    kimse: 'Nadie',
    mesajIzinleriAlt: 'Elige quién puede enviarte mensajes nuevos.',
    herkesAciklama: 'También quienes no son tus amigos pueden enviarte una solicitud.',
    yalnizcaArkadaslarim: 'Solo mis amigos',
    yalnizcaArkadaslarimAciklama: 'Solo tus amigos pueden iniciar conversaciones nuevas.',
    hicKimse: 'Nadie',
    hicKimseAciklama: 'No recibir solicitudes de mensaje nuevas.',
    etiketOnayBaslik: 'Aprobar las etiquetas primero',
    etiketOnayAciklama: 'Cuando tus amigos te etiquetan, la etiqueta no se ve hasta que la apruebes.',
    bekleyenEtiketler: 'Etiquetas pendientes',
    bekleyenEtiketlerAciklama: 'Aprobar o rechazar',
    bekleyenYok: 'No hay etiquetas pendientes.',
    profilGorunurluguAlt: 'Elige quién puede ver tus recuerdos y check-ins.',
    profilAcikAciklama: 'Tus recuerdos y check-ins son visibles para todos.',
    profilArkadasAciklama: 'Solo tus amigos los ven. Tu nombre, usuario y foto siguen siendo públicos.',
    aramaGorunurluguAlt: 'Elige si se te puede encontrar en la búsqueda de personas.',
    aramaAcikAciklama: 'Apareces al buscar tu nombre de usuario o tu nombre.',
    aramaKapaliAciklama: 'No apareces en la búsqueda; solo te encuentran con tu enlace.',
    etiketlerAlt: 'Gestiona cómo te etiquetan tus amigos.',
    mekanHerkesAciklama: 'Todos en el lugar te ven.',
    mekanArkadasAciklama: 'Solo tus amigos te ven.',
    mekanKimseAciklama: 'No apareces en el lugar; el check-in va igual a tus recuerdos.',
    konumErisimi: 'Acceso a la ubicación',
    uygulamayiKullanirken: 'Al usar la app',
    izinSorulmadi: 'Aún no solicitado',
    konumIzniYonet: 'Gestionar el permiso de ubicación',
    konumIzniYol: 'Puedes cambiar el permiso en Ajustes → Slooin → Ubicación de tu teléfono.',
    anladim: 'Entendido',
  },
  hesapGuvenlik: {
    satirBaslik: 'Cuenta y seguridad',
    satirAciklama: 'Correo, contraseña y sesiones activas',
    bolumHesabin: 'Tu cuenta',
    baslik: 'Cuenta y seguridad',
    altBaslik: 'Gestiona tus datos de acceso y la seguridad de tu cuenta.',
    girisBilgilerin: 'Datos de acceso',
    epostaAdresi: 'Correo electrónico',
    sifreyiDegistir: 'Cambiar contraseña',
    sifreAciklama: 'Usa una contraseña exclusiva para tu cuenta',
    guvenlik: 'Seguridad',
    acikOturumlar: 'Sesiones activas',
    acikOturumlarAciklama: 'Gestiona los dispositivos con sesión iniciada',
    cihazSayisi: '{{sayi}} dispositivos',
    koruBaslik: 'Protege tu cuenta',
    koruMetin: 'No compartas tu contraseña ni tus códigos de verificación con nadie.',
    epostaAlt: 'La dirección con la que accedes a tu cuenta.',
    mevcutAdres: 'Dirección actual',
    yeniAdres: 'Tu nuevo correo',
    yeniAdresYerTutucu: 'nombre@ejemplo.com',
    epostaNot: 'Primero te pediremos verificar tu dirección actual y después la nueva. Tu dirección de acceso no cambia hasta verificar la nueva.',
    devamEt: 'Continuar',
    epostaGecersiz: 'Escribe un correo válido.',
    epostaAyni: 'Esa ya es tu dirección actual.',
    mevcutKodBaslik: 'Verifica tu dirección actual',
    yeniKodBaslik: 'Verifica tu nueva dirección',
    kodMetin: 'Enviamos un código de 6 dígitos a {{eposta}}.',
    kodYerTutucu: 'Código de 6 dígitos',
    dogrula: 'Verificar',
    tekrarGonder: 'Reenviar código',
    kodEksik: 'Escribe el código de 6 dígitos.',
    epostaDegisti: 'Tu correo se ha actualizado.',
    sifreAlt: 'Elige una contraseña fuerte y exclusiva para tu cuenta.',
    mevcutSifre: 'Contraseña actual',
    yeniSifre: 'Nueva contraseña',
    yeniSifreTekrar: 'Repite la nueva contraseña',
    sifreIpucu: 'Usa al menos 12 caracteres. Elige una contraseña larga que solo uses en Slooin.',
    sifreGuncelle: 'Actualizar contraseña',
    sifremiUnuttum: 'Olvidé mi contraseña',
    sifreNot: 'Al cambiar tu contraseña se cierran las sesiones en otros dispositivos.',
    sifreKisa: 'La nueva contraseña debe tener al menos 12 caracteres.',
    sifreEslesmiyor: 'Las nuevas contraseñas no coinciden.',
    mevcutSifreYanlis: 'Tu contraseña actual es incorrecta.',
    sifreDegisti: 'Contraseña actualizada. Se cerraron las sesiones en otros dispositivos.',
    digerCihazlarKapatilamadi: 'Contraseña actualizada, pero no se pudieron cerrar otros dispositivos.',
    oturumlarAlt: 'Revisa los dispositivos donde tu cuenta está abierta.',
    buCihaz: 'Este dispositivo',
    sonEtkinlik: 'Última actividad: {{zaman}}',
    digerCihazlardanCik: 'Cerrar las otras sesiones',
    cihazBilinmeyen: 'Dispositivo desconocido',
    oturumKapatildi: 'Sesión cerrada.',
    digerleriKapatildi: 'Se cerraron las sesiones en otros dispositivos.',
    suAndaKullaniliyor: 'En uso ahora',
    kapat: 'Cerrar',
    oturumNot: 'Si ves un dispositivo que no reconoces, cierra su sesión y cambia tu contraseña.',
  },
  arkadasSecici: {
    baslik: 'Etiqueta a tus amigos',
    bos: 'Aún no tienes amigos. Cuando envíes una solicitud de amistad y la acepten, aparecerán aquí y podrás etiquetarlos en tus check-ins.',
    tamamSayili: 'Listo ({{sayi}})',
  },
  harita: {
    cevre: 'Lugares a tu alrededor',
    kisiBurada: '{{ad}}, {{sayi}} personas aquí',
    buMekan: 'Este lugar, {{durum}}',
    buradasin: 'Estás aquí',
    kumeEtiketi: '{{sayi}} lugares, toca para acercar',
    konumaDon: 'Volver a mi ubicación',
    adEtiketi: 'Etiqueta {{ad}}',
  },
  sikayet: {
    sebepSec: 'Elige un motivo',
    mesajBaglami: 'Durante la revisión, los mensajes cercanos a este también se abren a moderación.',
    baslik: 'Denunciar',
    kahramanBaslik: 'Cuéntanos qué pasó',
    altBaslikHesap: '¿Por qué denuncias esta cuenta?',
    altBaslikMesaj: '¿Por qué denuncias este mensaje?',
    ekAciklama: 'Información adicional',
    istegeBagli: 'Opcional',
    aciklamaYerTutucu: 'Puedes describir brevemente lo ocurrido.',
    aciklamaIpucu: 'Lo que compartas nos ayuda a evaluarlo.',
    fotografEkle: 'Añadir foto',
    fotografDegistir: 'Cambiar foto',
    fotografKaldir: 'Quitar foto',
    fotografCek: 'Hacer foto',
    galeridenSec: 'Elegir de la galería',
    kameraIzni: 'Se necesita permiso de cámara para hacer una foto.',
    fotografYuklenemedi: 'No se pudo subir la foto, inténtalo de nuevo.',
    gonder: 'Enviar denuncia',
    alindi: 'Denuncia recibida',
    tesekkur: 'Gracias por avisarnos.\nTu denuncia se ha enviado para su revisión.',
    engelleSoru: '¿Quieres bloquear esta cuenta?',
    engelleAciklama: 'Puedes impedir que te envíe mensajes e interactúe contigo.',
    hesabiEngelle: 'Bloquear cuenta',
    engellendi: 'Cuenta bloqueada',
    tamam: 'Listo',
    sebepler: {
      taciz: 'Acoso o intimidación',
      uygunsuz_icerik: 'Contenido inapropiado',
      sahte_hesap: 'Cuenta falsa',
      spam: 'Spam o publicidad',
      diger: 'Otro',
    },
  },
  hesapDurumu: {
    askida: 'Tu cuenta está suspendida',
    yasakli: 'Tu cuenta se ha cerrado definitivamente',
    sebep: 'Motivo: {{sebep}}',
    bitis: 'Termina: {{tarih}}',
    ipucu: 'Durante este tiempo tu perfil no es visible para los demás y no puedes publicar contenido nuevo. Tus datos no se han eliminado.',
    yenile: 'Actualizar',
    cikisYapilamadi: 'No se pudo cerrar la sesión',
  },
  checkIn: {
    baslik: 'Nuevo check-in',
    degistir: 'Cambiar',
    istegeBagli: 'Añadir nota, foto o amigos es opcional.',
    notEtiket: 'Tu nota',
    notYerTutucu: 'Escribe algo sobre este momento...',
    fotografEtiket: 'Foto',
    fotografEkle: 'Añadir foto',
    fotografKaldir: 'Quitar foto',
    arkadasEtiketle: 'Etiquetar amigos',
    kimlerle: '¿Con quién estás?',
    birlikte: 'Con',
    ekle: 'Añadir',
    etiketiKaldir: 'Quitar etiqueta de {{ad}}',
    fotografCek: 'Tomar foto',
    galeridenSec: 'Elegir de la galería',
    kameraIzni: 'Se necesita permiso de cámara para tomar una foto.',
    fotografYuklenemedi: 'No se pudo subir la foto; check-in hecho con tu nota',
    etiketlenemedi: 'Check-in hecho, pero no se pudo etiquetar a tus amigos.',
    gorunurlukNotu: 'La visibilidad sigue tu configuración de privacidad.',
    gonder: 'Compartir check-in',
    gonderiliyor: 'Compartiendo...',
  },
  mekanDuzenle: {
    baslik: 'Corregir la información',
    aciklama: '¿Hay algo mal? Tu corrección va a un moderador; cuando se apruebe, se actualiza para todos.',
    gonderildiBaslik: 'Tu solicitud se ha enviado',
    gonderildiMetin: 'La información del lugar se actualizará cuando un moderador la revise y la apruebe.',
    bekleyenBaslik: 'Tienes una solicitud pendiente',
    bekleyenMetin: 'La solicitud que enviaste para este lugar aún está en revisión. Cuando se resuelva, podrás enviar una nueva corrección.',
    adEtiket: 'Nombre del lugar',
    adYerTutucu: 'Nombre del lugar',
    mahalle: 'Barrio',
    mahalleYerTutucu: 'p. ej. Alaaddinbey',
    adres: 'Dirección',
    adresYerTutucu: 'Calle, número',
    il: 'Provincia',
    ilYerTutucu: 'Bursa',
    ilce: 'Distrito',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Tipo',
    kapakFotografi: 'Foto de portada',
    fotografiKaldir: 'Quitar foto',
    fotografEkle: 'Añadir foto',
    fotografSecilemedi: 'No se pudo seleccionar la foto.',
    galeriIzni: 'Se necesita el permiso de fotos para elegir de la galería.',
    oturumYok: 'Sesión no encontrada',
    zatenKapali: 'Este lugar ya está marcado como cerrado definitivamente.',
    kapaliBaslik: 'Este lugar cerró definitivamente',
    kapaliAciklama: 'Si se aprueba, este lugar se retira de las listas y la búsqueda. Los check-ins hechos aquí no se eliminan.',
    onceDegistir: 'Cambia algo primero.',
    talebiGonder: 'Enviar solicitud',
  },
  mekanEkle: {
    baslik: 'Añadir un lugar nuevo',
    adYerTutucu: 'Nombre del lugar',
    turuSec: 'Elige un tipo',
    adresYerTutucu: 'Dirección (opcional)',
    adresSoru: '¿Es correcta esta dirección?',
    adresAciklama: 'Obtenida a partir de tu ubicación. Si es incorrecta, puedes editar el campo de arriba.',
    dogru: 'Correcta',
    benzerBaslik: '¿Te refieres a alguno de estos?',
    konumAlinamadi: 'No se pudo obtener tu ubicación, inténtalo de nuevo',
    adVeTurGerekli: 'El nombre y el tipo del lugar son obligatorios',
    ekle: 'Añadir',
    ekleniyor: 'Añadiendo...',
  },
  turGruplari: {
    'Yeme içme': 'Comida y bebida',
    Gece: 'Vida nocturna',
    'Açık alan': 'Al aire libre',
    Kültür: 'Cultura',
    Spor: 'Deporte',
    Alışveriş: 'Compras',
    Diğer: 'Otros',
  },
  turler: {
    Kafe: 'Café',
    Kahveci: 'Cafetería de especialidad',
    'Çay evi': 'Casa de té',
    Restoran: 'Restaurante',
    Lokanta: 'Casa de comidas',
    'Türk mutfağı': 'Cocina turca',
    Kebapçı: 'Kebab',
    'Balık restoranı': 'Restaurante de pescado',
    Ocakbaşı: 'Parrilla',
    'Kahvaltı salonu': 'Desayunos',
    Fırın: 'Panadería',
    'Fast food': 'Comida rápida',
    Burgerci: 'Hamburguesería',
    Pizzacı: 'Pizzería',
    Tatlıcı: 'Pastelería',
    Dondurmacı: 'Heladería',
    Bar: 'Bar',
    Pub: 'Pub',
    'Gece kulübü': 'Discoteca',
    Meyhane: 'Taberna',
    'Nargile kafe': 'Salón de shisha',
    'Kokteyl barı': 'Coctelería',
    Park: 'Parque',
    'Halk bahçesi': 'Jardín público',
    'Doğal alan': 'Espacio natural',
    Plaj: 'Playa',
    Meydan: 'Plaza',
    'Kamp alanı': 'Camping',
    Göl: 'Lago',
    Müze: 'Museo',
    Sinema: 'Cine',
    Tiyatro: 'Teatro',
    'Sanat galerisi': 'Galería de arte',
    Kütüphane: 'Biblioteca',
    'Tarihi yer': 'Lugar histórico',
    'Konser salonu': 'Sala de conciertos',
    'Kültür merkezi': 'Centro cultural',
    'Spor salonu': 'Gimnasio',
    Stadyum: 'Estadio',
    'Yüzme havuzu': 'Piscina',
    'Halı saha': 'Campo de fútbol',
    AVM: 'Centro comercial',
    Market: 'Supermercado',
    Bakkal: 'Tienda de barrio',
    'Giyim mağazası': 'Tienda de ropa',
    Kitapçı: 'Librería',
    Kuyumcu: 'Joyería',
    Otel: 'Hotel',
    Eczane: 'Farmacia',
    Hastane: 'Hospital',
    Banka: 'Banco',
    Kuaför: 'Peluquería',
    'Güzellik salonu': 'Salón de belleza',
    Üniversite: 'Universidad',
    'Canlı müzik': 'Música en vivo',
  },
  kesfet: {
    baslik: 'Check-in',
    harita: 'Mapa',
    liste: 'Lista',
    turSuzgeci: 'Filtro por tipo',
    turFiltresi: 'Filtro por tipo',
    turBulunamadi: 'No hay tipos que mostrar a tu alrededor.',
    filtreyiKaldir: 'Quitar filtro',
    tumunuSec: 'Seleccionar todo',
    temizle: 'Limpiar',
    kaydet: 'Guardar',
    kaydetSayili: 'Guardar ({{sayi}})',
    tumu: 'Todos',
    sakin: 'Tranquilo',
    yogun: 'Lleno',
    populer: 'Popular',
    yakinindakiMekanlar: 'Lugares cerca de ti',
    mesafeyeGore: 'Por distancia',
    mesafeSec: 'Elegir distancia',
    mesafeIcinde: 'A menos de {{mesafe}}',
    mesafeTumu: 'A menos de 1 km (todos)',
    digerMekanlar: 'Mostrar otros lugares',
    paneliKapat: 'Cerrar la lista',
    yolTarifi: 'Cómo llegar',
    sonuclar: 'Resultados',
    kisiBurada: '{{sayi}} personas aquí',
    checkIn: 'Check-in',
    konumuGor: 'Ver ubicación',
    checkInYap: 'Hacer check-in aquí',
    mekanAra: 'Buscar lugares',
    kisi: '{{sayi}} personas',
    taraniyor: 'Explorando tu entorno…',
    cevreGorunmuyor: 'No vemos tu entorno',
    konumIzniAciklama: 'Necesitamos el permiso de ubicación para mostrarte los lugares cercanos. Actívalo en los ajustes del navegador e inténtalo de nuevo.',
    konumuAc: 'Abrir {{ad}}',
    konumuGorEtiketi: 'Ver {{ad}}',
    checkInEtiketi: 'Hacer check-in en {{ad}}',
    filtreyiKaldirEtiketi: 'Quitar el filtro {{tur}}',
    kisiBuradaEtiket: 'personas aquí',
    suAnBuradasin: 'Estás aquí ahora',
    ayrildim: 'Me fui',
    araniyor: 'Buscando…',
    aramaBulunamadi: 'No se encontró ningún lugar para «{{arama}}». Prueba a cambiar la ortografía.',
    sonucSayisi: '{{sayi}} resultados',
    bosArama: 'Sin resultados para «{{arama}}» en esta provincia.',
    bosFiltre: 'No hay lugares a menos de 500 m con este filtro.',
    bosCevre: 'No hay lugares cerca de ti.',
    mekanEkle: '¿No encuentras un lugar? Añádelo',
    atif: 'Datos de lugares: Foursquare · Barrio y distrito: © colaboradores de OpenStreetMap',
  },
  checkInHaritasi: {
    geri: 'Atrás',
    haritaAcikla: 'Toca el mapa para obtener indicaciones',
    haritadaAc: 'Cómo llegar',
    secimBaslik: '¿Qué mapa abrimos?',
    appleHaritalar: 'Apple Maps',
    googleHaritalar: 'Google Maps',
    vazgec: 'Cancelar',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Foto de {{ad}}',
    menu: 'Opciones',
    yolTarifi: 'Cómo llegar',
    buradaCheckIn: 'Hacer check-in aquí',
    yaklas: 'Acércate para hacer check-in · {{mesafe}}',
    buradasinAyril: 'Estás aquí · Salir',
    kapandi: 'Este lugar cerró definitivamente',
    kapandiAciklama: 'Ya no puedes hacer check-in aquí y el lugar no se muestra en las listas. Tus recuerdos anteriores se conservan.',
    kisiBurada: 'personas aquí',
    bugun: 'Hoy',
    haritadaGoster: 'Mostrar la ubicación en el mapa',
    checkInSayisi: '{{sayi}} check-ins',
    kisiSayisi: '{{sayi}} personas',
    ilcedekiYerler: 'lugares en {{ilce}}',
    siralamaYok: 'Sin clasificación',
    suAnBurada: 'Aquí ahora',
    diger: 'Otros',
    biri: 'Alguien',
    suAn: 'ahora',
    liderlik: 'Ranking',
    sonCheckInler: 'Recientes',
    liderlikBos: 'Aún no hay check-ins que mostrar aquí.',
    sonBos: 'Aún no hay check-ins que mostrar aquí.',
    fotograflar: 'Fotos',
    fotografBos: 'Aún no hay fotos aquí.',
    fotografAc: 'Ampliar foto',
    dahaFazlaFotograf: 'Más fotos',
    puan: 'Valoración',
    puanlamaSayisi: '{{sayi}} valoraciones',
    puanYok: 'Aún sin valoración',
    puanAzOy: 'Se necesitan al menos 3 valoraciones para una puntuación',
    puanKotu: 'Malo',
    puanIyi: 'Bueno',
    puanHarika: 'Genial',
    puanSoru: '¿Qué te pareció este lugar?',
    puanSart: 'Haz check-in aquí primero para valorarlo.',
    puanGonder: 'Enviar',
    puanGuncelle: 'Actualizar tu valoración',
    puanGonderiliyor: 'Enviando…',
    puanTesekkur: 'Tu valoración se ha guardado.',
  },
  giris: {
    epostaYerTutucu: 'Correo electrónico',
    sifreYerTutucu: 'Contraseña',
    gonder: 'Iniciar sesión',
    gonderiliyor: 'Iniciando sesión…',
    kayitOl: 'Crear una cuenta nueva',
    hataEposta: 'Introduce un correo válido.',
    hataBos: 'Introduce tu correo y tu contraseña.',
    sifremiUnuttum: '¿Olvidaste tu contraseña?',
  },
  sifreSifirla: {
    geri: 'Atrás',
    baslik: 'Restablece tu contraseña',
    aciklama: 'Introduce el correo de tu cuenta y te enviaremos un código de 6 dígitos.',
    epostaYerTutucu: 'Correo electrónico',
    kodGonder: 'Enviar código',
    gonderiliyor: 'Enviando…',
    hataEposta: 'Introduce un correo válido.',
    hataHesapYok: 'No se encontró ninguna cuenta con este correo.',
    kodBaslik: 'Introduce el código',
    kodAciklama: 'Hemos enviado un código de 6 dígitos a {{eposta}}.',
    kodEtiketi: 'Código de verificación',
    dogrula: 'Verificar',
    dogrulaniyor: 'Verificando…',
    hataEksik: 'Introduce el código completo.',
    kodGelmedi: '¿No te llegó el código?',
    spamNotu: 'Si no está en tu bandeja de entrada, revisa también la carpeta de spam.',
    tekrarGonder: 'Reenviar',
    tekrarBekle: 'Puedes reenviar en {{saniye}} s',
    tekrarGonderildi: 'Se ha enviado un nuevo código.',
    hakKalmadi: 'Se han solicitado demasiados códigos para esta dirección. Podrás intentarlo de nuevo en una hora.',
    yeniBaslik: 'Define tu nueva contraseña',
    yeniAciklama: 'El código se ha verificado. Ahora elige una contraseña nueva.',
    sifreYerTutucu: 'Nueva contraseña (al menos {{adet}} caracteres)',
    sifreTekrarYerTutucu: 'Nueva contraseña (otra vez)',
    kaydet: 'Guardar contraseña',
    kaydediliyor: 'Guardando…',
    hataSifreKisa: 'La contraseña debe tener al menos {{adet}} caracteres.',
    hataSifreEslesmiyor: 'Las contraseñas no coinciden.',
  },
  hatalar: {
    genel: 'Algo salió mal. Inténtalo de nuevo en un momento.',
    kullaniciAdi30Gun: 'Puedes cambiar tu nombre de usuario una vez cada 30 días. Quedan {{gun}} días.',
    vt: {
      parola_yanlis: 'Contraseña incorrecta.',
      su_anda_dogrulanamadi: 'No se pudo verificar ahora, inténtalo en un momento.',
      silme_su_anda_tamamlanamadi: 'La eliminación no se pudo completar ahora, inténtalo de nuevo.',
      giris_taze_degil: 'El código de confirmación no se verificó o ha caducado; envíalo de nuevo.',
      silme_onayi_gerekli: 'Verifica el código de confirmación antes de eliminar.',
      aski_bitisi_gelecekte_olmali: 'El fin de la suspensión debe estar en el futuro.',
      bir_moderatore_islem_uygulanamaz: 'No se pueden aplicar acciones a un moderador.',
      bu_kisiye_su_an_mesaj_gonderemezsin: 'Ahora mismo no puedes escribir a esta persona.',
      bu_kullanici_adi_alinmis: 'Este nombre de usuario ya está en uso, prueba otro.',
      bu_kullanici_bulunamadi: 'No se encontró este usuario.',
      bu_fotograf_sana_ait_degil: 'Esta foto no te pertenece.',
      bu_il_listemizde_yok: 'Esta provincia no está en nuestra lista.',
      bu_mekan_bulunamadi: 'No se encontró este lugar.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'La solicitud que enviaste para este lugar aún está en revisión.',
      bu_mekan_kalici_olarak_kapandi: 'Este lugar cerró definitivamente.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'Este lugar ya está marcado como cerrado.',
      bu_tur_listemizde_yok: 'Este tipo no está en nuestra lista.',
      en_az_bir_alan_doldurulmali: 'Debes cambiar al menos un dato.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'Alcanzaste el límite diario de correcciones (5). Podrás intentarlo mañana.',
      hesabin_su_an_bu_islemi_yapamaz: 'Tu cuenta no puede hacer esto ahora mismo.',
      bu_paylasim_bulunamadi: 'No se encontró esta publicación.',
      not_en_fazla_500_karakter_olabilir: 'La nota puede tener como máximo 500 caracteres.',
      bu_mesaji_sikayet_edemezsin: 'No puedes denunciar este mensaje.',
      bugunluk_istek_sinirina_ulastin: 'Alcanzaste el límite de solicitudes de hoy.',
      check_in_bulunamadi: 'Check-in no encontrado.',
      cok_fazla_kimlik: 'Se enviaron demasiados identificadores.',
      en_az_2_karakter_gerekli: 'Escribe al menos 2 caracteres.',
      gecersiz_bulunurluk_degeri: 'Valor de disponibilidad no válido.',
      gecersiz_gorunurluk_degeri: 'Valor de visibilidad no válido.',
      gecersiz_platform: 'Plataforma no válida.',
      gecersiz_sikayet_durumu: 'Estado de denuncia no válido.',
      gecersiz_sikayet_hedefi: 'Objetivo de denuncia no válido.',
      gerekce_belirtilmeli: 'Debes indicar un motivo.',
      geri_cekilecek_istek_bulunamadi: 'No se encontró ninguna solicitud que retirar.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'Alcanzaste el límite diario de lugares añadidos (5). Podrás intentarlo mañana.',
      hesabin_su_anda_kullanilamiyor: 'Tu cuenta no está disponible ahora mismo.',
      hesabin_zaten_kullanilamaz_durumda: 'Tu cuenta ya no está disponible.',
      istegin_zaten_gonderilmis: 'Tu solicitud ya se envió.',
      jeton_bos_olamaz: 'El token de notificación no puede estar vacío.',
      jeton_cok_uzun: 'El token de notificación es demasiado largo.',
      kendi_mesajini_sikayet_edemezsin: 'No puedes denunciar tu propio mensaje.',
      kendine_islem_uygulayamazsin: 'No puedes aplicarte una acción a ti mismo.',
      kendine_istek_gonderemezsin: 'No puedes enviarte una solicitud a ti mismo.',
      kendine_mesaj_gonderemezsin: 'No puedes escribirte a ti mismo.',
      kendini_engelleyemezsin: 'No puedes bloquearte a ti mismo.',
      kendini_sikayet_edemezsin: 'No puedes denunciarte a ti mismo.',
      kimlik_dogrulamasi_gerekli: 'Debes iniciar sesión para esto.',
      konusma_bulunamadi: 'Conversación no encontrada.',
      kullanici_adi_kurallara_uymuyor: 'El nombre de usuario no cumple las reglas.',
      kullanici_belirtilmeli: 'Debe indicarse un usuario.',
      mekan_bulunamadi: 'Lugar no encontrado.',
      gecersiz_puan: 'Valoración no válida.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'Haz check-in aquí primero para valorarlo.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'Estás demasiado lejos del lugar. Para hacer check-in debes estar a menos de 1 kilómetro aproximadamente.',
      mekana_yakin_olmalisin_200_m_icinde: 'Para añadir un lugar debes estar a menos de unos 200 metros de él.',
      mesaj_bos_olamaz: 'El mensaje no puede estar vacío.',
      mesaj_bu_konusmada_bulunamadi: 'El mensaje no se encontró en esta conversación.',
      mesaj_cok_uzun: 'El mensaje es demasiado largo.',
      profil_bulunamadi: 'Perfil no encontrado.',
      sikayet_bulunamadi: 'Denuncia no encontrada.',
      sikayet_sebebi_belirtilmeli: 'Debes indicar un motivo para la denuncia.',
      yanitlanacak_istek_bulunamadi: 'No se encontró ninguna solicitud que responder.',
      yetkisiz: 'No tienes permiso para esto.',
      zaten_bu_kullanici_adini_kullaniyorsun: 'Ya estás usando este nombre de usuario.',
    },
    kod: {
      '23505': 'Este registro ya existe.',
      '57014': 'La operación tardó demasiado. Inténtalo de nuevo.',
      otp_expired: 'El código no es válido o ha caducado. Solicita uno nuevo.',
      user_already_exists: 'Ya hay una cuenta con esta dirección. Puedes iniciar sesión.',
      invalid_credentials: 'Correo o contraseña incorrectos.',
      over_request_rate_limit: 'Lo intentaste demasiadas veces. Espera un poco e inténtalo de nuevo.',
      over_sms_send_rate_limit: 'Se solicitaron demasiados códigos. Espera un poco e inténtalo de nuevo.',
      weak_password: 'La contraseña es demasiado débil. Elige una más segura.',
      same_password: 'La nueva contraseña debe ser distinta de la anterior.',
      signup_disabled: 'Ahora mismo no se aceptan registros nuevos.',
      phone_provider_disabled: 'Ahora mismo no se puede enviar un código a este número. Inténtalo más tarde.',
    },
    metin: {
      sms_saglayici: 'Ahora mismo no se puede enviar un código a este número. Inténtalo más tarde.',
      sms_saglayici2: 'Ahora mismo no se puede enviar un código a este número. Inténtalo más tarde.',
      kod_gecersiz: 'El código no es válido o ha caducado. Solicita uno nuevo.',
      zaten_kayitli: 'Ya hay una cuenta con esta dirección. Puedes iniciar sesión.',
      giris_hatali: 'Correo o contraseña incorrectos.',
      cok_sik: 'Lo intentaste demasiadas veces. Espera un poco e inténtalo de nuevo.',
      sifre_kisa: 'La contraseña es demasiado corta.',
      sifre_ayni: 'La nueva contraseña debe ser distinta de la anterior.',
      kayit_kapali: 'Ahora mismo no se aceptan registros nuevos.',
      ag_yok: 'No se pudo conectar a internet. Revisa tu conexión e inténtalo de nuevo.',
      oturum_dustu: 'Tu sesión ha caducado. Inicia sesión de nuevo.',
    },
  },

  bildirimAyarlari: {
    altBaslik: "¿Cuándo y para qué quieres que te avisemos?",
    anlik: "Notificaciones push",
    anlikAciklama: "Notificaciones de Slooin en tu teléfono.",
    insanlar: "Personas e interacción",
    arkadaslik: "Solicitudes de amistad",
    arkadaslikAciklama: "Nuevas solicitudes y amistades aceptadas.",
    mesajlar: "Mensajes",
    mesajlarAciklama: "Mensajes nuevos y solicitudes de mensaje.",
    etiketler: "Etiquetas",
    etiketlerAciklama: "Solicitudes y aprobaciones de etiquetas.",
    kesif: "Descubrir y recuerdos",
    aniHatirlatma: "Recordatorios de recuerdos",
    aniHatirlatmaAciklama: "Revive tus buenos momentos.",
    sessiz: "Horas de silencio",
    geceSessiz: "Silenciar por la noche",
    geceSessizAciklama: "Sin notificaciones push entre las 22:00 y las 08:00.",
    sessizNot: "Las horas de silencio siguen la hora local de tu dispositivo. Las notificaciones dentro de la app y los mensajes no leídos se conservan.",
    cihazAyarlari: "Ajustes de notificaciones del dispositivo",
    izinYonet: "Gestionar permiso de notificaciones",
    izinYol: "Puedes permitir o desactivar las notificaciones en Ajustes → Notificaciones → Slooin de tu teléfono.",
  },

  uygulama: {
    bolum: "Aplicación",
    gorunum: "Apariencia",
    gorunumAciklama: "Preferencias de tema y movimiento",
    tema: "Tema",
    temaSistem: "Igual que el sistema",
    temaSistemAciklama: "Sigue la apariencia de tu dispositivo.",
    temaAcik: "Claro",
    temaAcikAciklama: "Aspecto luminoso y sencillo.",
    temaKoyu: "Oscuro",
    temaKoyuAciklama: "Aspecto más suave con poca luz.",
    yardim: "Centro de ayuda",
    yardimAciklama: "Encuentra respuestas o informa de un problema",
    yardimAlt: "Resolvamos juntos tus dudas.",
    sikSorulanlar: "Preguntas frecuentes",
    sorunBildir: "Informar de un problema",
    sorunKonu: "Informe de problema en Slooin",
    soru1: "¿Cómo funciona un perfil privado?",
    cevap1: "Con el perfil privado, tus recuerdos y check-ins solo los ven tus amigos. Tu nombre, nombre de usuario y foto de perfil siguen siendo públicos para que puedan encontrarte y enviarte una solicitud de amistad. Agregar un perfil privado requiere solicitud; en un perfil público se agrega directamente. Cámbialo en Ajustes → Privacidad → Visibilidad del perfil.",
    soru2: "¿Se comparte mi ubicación todo el tiempo?",
    cevap2: "No. Tu ubicación solo se comparte al hacer check-in. El check-in se convierte en recuerdo tras una hora o cuando tocas \"Salir\"; en ese momento se borran tus coordenadas y solo queda el lugar. Al buscar lugares, la ubicación del dispositivo se envía al servidor pero no se guarda.",
    soru3: "¿Cómo bloqueo a alguien?",
    cevap3: "Abre el perfil de la persona y toca Bloquear en el menú superior derecho. La persona bloqueada no puede enviarte mensajes ni solicitudes de amistad, y la conversación entre ambos se elimina en los dos lados. Puedes desbloquear en Ajustes → Privacidad → Personas bloqueadas.",
    soru4: "¿Cuál es la diferencia entre congelar y eliminar la cuenta?",
    cevap4: "Congelar es temporal: tu perfil deja de verse, tus datos se conservan y la cuenta se reactiva sola al volver a iniciar sesión. Eliminar es permanente: la cuenta y los datos no se pueden recuperar; tus mensajes y denuncias se anonimizan. Ambas opciones están en Ajustes → Gestión de la cuenta.",
    hakkinda: "Acerca de Slooin",
    hakkindaAciklama: "Normas de la comunidad e información legal",
    hakkindaAlt: "Las normas y documentos que, entre todos, hacen de Slooin un buen lugar.",
    birlikteDahaIyi: "Mejor juntos",
    toplulukKurallari: "Normas de la comunidad",
    toplulukAciklama: "Un espacio respetuoso y seguro",
    gizlilikPolitikasi: "Política de privacidad",
    gizlilikPolitikasiAciklama: "Cómo se tratan tus datos",
    kullanimKosullari: "Condiciones de uso",
    kullanimKosullariAciklama: "Reglas de uso",
    surum: "Slooin {{surum}}",
  },

  toplulukKurallari: {
    baslik: "Normas de la comunidad",
    giris: "Slooin existe para conocer gente nueva en lugares reales. Que sea seguro depende de que todos sigan estas normas.",
    k1b: "Sé respetuoso",
    k1m: "Los insultos, el acoso, las amenazas y el discurso de odio están prohibidos. Nadie está obligado a continuar una conversación que no quiere.",
    k2b: "Sé auténtico",
    k2m: "No te hagas pasar por otra persona, no crees cuentas falsas ni uses la foto de otra persona como foto de perfil.",
    k3b: "Respeta la privacidad de los demás",
    k3m: "No compartas la foto, la ubicación ni los datos personales de alguien sin su consentimiento. La persona etiquetada puede quitar la etiqueta.",
    k4b: "Queda con seguridad",
    k4m: "Queda con personas que acabas de conocer en lugares concurridos y públicos. Si no te sientes seguro, vete, bloquea a la persona y denúnciala.",
    k5b: "No compartas contenido engañoso",
    k5m: "Los check-ins falsos, la información incorrecta de lugares, la publicidad y el spam están prohibidos. Las correcciones de lugares pasan por aprobación de un moderador.",
    k6b: "Sé mayor de 18 años",
    k6m: "Slooin es solo para mayores de 18 años. Las cuentas que declaran una edad falsa se cierran.",
    kapanis: "Las cuentas que incumplen las normas pueden recibir una advertencia, ser suspendidas o cerrarse de forma permanente. Cuando veas un problema, denúncialo; cada denuncia la revisa un moderador.",
  },

  hesapYonetimi: {
    bolum: "Acciones de la cuenta",
    satirBaslik: "Gestión de la cuenta",
    satirAciklama: "Opciones de congelar y eliminar",
    baslik: "Gestión de la cuenta",
    altBaslik: "Haz una pausa en tu cuenta o ciérrala definitivamente.",
    dondur: "Congelar cuenta",
    dondurAciklama: "Puedes volver cuando quieras",
    sil: "Eliminar cuenta",
    silAciklama: "Solicitar eliminación permanente",
    kartBaslik: "Conserva tus recuerdos",
    kartMetin: "Antes de continuar puedes descargar una copia de tus datos.",
  },
} as const
