/**
 * Textes francais. Reflete 1:1 la structure de cles de `tr.ts` ;
 * une cle absente retombe sur le turc et le test de parite
 * (`__tests__/ceviri-tamlik.test.ts`) signale tout ecart.
 */
export default {
  // HUKUKI EKRANLAR (i18n E asamasi, 2026-09-13): basliklar ve
  // "Turkce metin esastir" notu. Belgelerin kendisi lib/hukuki/ altinda.
  hukuki: {
    gizlilikBaslik: 'Notice de confidentialité',
    kosullarBaslik: "Conditions d'utilisation",
    sonGuncelleme: 'Dernière mise à jour : {{tarih}}',
    ustunlukNotu: "Le texte faisant foi est la version turque de ce document ; cette traduction est fournie à titre d'information.",
  },

  ortak: {
    devam: 'Continuer',
    iptal: 'Annuler',
    tumunuSec: 'Tout sélectionner',
    temizle: 'Effacer',
    kaydet: 'Enregistrer',
    tekrarDene: 'Réessayer',
    yukleniyor: 'Chargement…',
    birSorunOldu: 'Un problème est survenu.',
    agYok: 'Pas de connexion internet, réessaie',
    gonder: 'Envoyer',
    gonderiliyor: 'Envoi…',
    tamam: 'OK',
    sira: 'Rang {{sira}}',
    sil: 'Supprimer',
    vazgec: 'Annuler',
    geri: 'Retour',
    kapat: 'Fermer',
    ara: 'Rechercher',
    sonucYok: 'Aucun résultat.',
  },
  karsilama: {
    baslik: 'Vois qui est près de toi, ',
    baslikVurgu: 'explore.',
    aciklama: 'Fais un check-in, rencontre de nouvelles personnes.\nDécouvre les lieux populaires autour de toi.',
    kisiSayisi: '{{sayi}} personnes',
    disarida: '{{sayi}} personnes sorties près de toi',
    turKafe: 'Café',
    turRestoran: 'Restaurant',
    turBar: 'Bar',
    adim1Baslik: 'Fais un check-in',
    adim1Aciklama: 'Sois visible là où tu es',
    adim2Baslik: 'Qui est près de toi',
    adim2Aciklama: 'Découvre les gens au même endroit',
    adim3Baslik: 'Discute',
    adim3Aciklama: 'Rencontre de nouvelles personnes',
    adim4Baslik: 'Découvre les lieux populaires',
    adim4Aciklama: 'Vois les endroits tendance de ta ville',
    hesapOlustur: 'Créer un compte',
    hesabinVarMi: 'Tu as déjà un compte ?',
    girisYap: 'Se connecter',
    haritaAtfi: 'Données cartographiques © contributeurs OpenStreetMap',
  },
  kayit: {
    baslik: 'Commence avec ton e-mail',
    epostaEtiket: 'Adresse e-mail',
    epostaYerTutucu: 'nom@exemple.com',
    devam: 'Continuer',
    veya: 'ou',
    appleIle: 'Continuer avec Apple',
    googleIle: 'Continuer avec Google',
    hataEposta: 'Saisis une adresse e-mail valide.',
    hataEpostaKayitli: 'Un compte existe déjà avec cet e-mail. Tu peux te connecter avec ton mot de passe.',
    hataSaglayiciKapali: "Cette méthode de connexion n'est pas disponible pour le moment. Tu peux continuer avec ton e-mail.",
    telefonEtiket: 'Numéro de téléphone',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Envoyer le code',
    gonderiliyor: 'Envoi…',
    zatenHesap: 'Tu as déjà un compte ?',
    girisYap: 'Se connecter',
    hataTelefon: 'Saisis un numéro de téléphone valide.',
    hataZatenKayitli: 'Un compte existe déjà avec ce numéro. Tu peux te connecter avec ton mot de passe.',
  },
  profilOlustur: {
    baslik: 'Créer un compte',
    adYerTutucu: 'Ton nom complet',
    adHata: 'Saisis ton nom complet.',
    dogumEtiket: 'Date de naissance',
    dogumSec: 'Jour / Mois / Année',
    dogumHataGecersiz: 'Sélectionne ta date de naissance.',
    dogumHataYas: 'Tu dois avoir au moins 18 ans pour utiliser Slooin.',
    tarihGun: 'Jour',
    tarihAy: 'Mois',
    tarihYil: 'Année',
    tarihTamam: 'OK',
    aylar: {
      1: 'Janvier',
      2: 'Février',
      3: 'Mars',
      4: 'Avril',
      5: 'Mai',
      6: 'Juin',
      7: 'Juillet',
      8: 'Août',
      9: 'Septembre',
      10: 'Octobre',
      11: 'Novembre',
      12: 'Décembre',
    },
    kullaniciAdiYerTutucu: "Nom d'utilisateur",
    kullaniciAdiIpucu: "Le nom d'utilisateur ne respecte pas le format demandé.",
    kullaniciAdiKontrol: 'Vérification…',
    kullaniciAdiMusait: "Ce nom d'utilisateur est disponible.",
    kullaniciAdiAlinmis: "Ce nom d'utilisateur est pris, essaie-en un autre.",
    sifreEtiket: 'Mot de passe',
    sifreYerTutucu: 'Au moins {{adet}} caractères',
    tekrarEtiket: 'Répéter le mot de passe',
    tekrarYerTutucu: 'Le même mot de passe encore une fois',
    sifrelerFarkli: 'Les mots de passe ne correspondent pas encore.',
    sifreGoster: 'Afficher le mot de passe',
    sifreGizle: 'Masquer le mot de passe',
    hataSifreKisa: 'Le mot de passe doit contenir au moins {{adet}} caractères.',
    hataSifreUyusmuyor: 'Les mots de passe ne correspondent pas. Vérifie les deux.',
    adimSayaci: 'Étape {{simdiki}} / {{toplam}}',
    adim1Baslik: 'Faisons connaissance',
    adim1Aciklama: "Ton nom apparaît sur ton profil. Ta date de naissance n'est jamais montrée à personne.",
    adEtiket: 'Nom complet',
    adOrnek: 'ex. Léa Martin',
    yasNotu: 'Slooin est réservé aux 18 ans et plus.',
    adim2Baslik: "Choisis ton nom d'utilisateur",
    adim2Aciklama: '3 à 20 caractères ; peut contenir des minuscules, des chiffres, des points et des tirets bas.',
    kullaniciAdiEtiket: "Ton nom d'utilisateur",
    adim3Baslik: 'Définis ton mot de passe',
    adim3Aciklama: 'Tu te connecteras à ton compte avec ce mot de passe.',
    sifreUygun: 'Le mot de passe est assez long.',
    sifrelerAyni: 'Les mots de passe correspondent.',
    devam: 'Continuer',
    sozlesmeNotuOn: 'En créant un compte, tu confirmes accepter les ',
    sozlesmeKosullar: "Conditions d'utilisation",
    sozlesmeNotuOrta: ' et avoir lu la ',
    sozlesmeGizlilik: 'Politique de confidentialité',
    sozlesmeNotuSon: '.',
    gonder: 'Créer un compte',
    gonderiliyor: 'Création…',
    oturumDustu: 'Ta session a expiré, reconnecte-toi.',
    beklenmeyenHata: "Une erreur inattendue s'est produite.",
  },
  bildirimler: {
    baslik: 'Notifications',
    arkadaslikBolumu: "Demandes d'amitié",
    etiketBolumu: 'Demandes de tag',
    arkadaslikMetni: 'veut devenir ton ami.',
    etiketMetni: 'veut te taguer dans un check-in à {{mekan}}.',
    kabul: 'Accepter',
    onayla: 'Approuver',
    reddet: 'Refuser',
    bosBaslik: 'Rien de nouveau',
    bosAciklama: "Les demandes d'amitié et les personnes qui veulent te taguer apparaissent ici.",
  },
  kisiler: {
    baslik: 'Trouver des gens',
    yerTutucu: "Nom d'utilisateur ou nom",
    enAzIki: 'Saisis au moins 2 caractères.',
    bulunamadi: 'Personne trouvé.',
    ipucu: "Tu peux chercher quelqu'un par son nom d'utilisateur ou son nom.",
  },
  baglar: {
    baslik: 'Amis',
    arkadasliktanCikar: 'Retirer des amis',
    bosArkadas: "Pas encore d'amis",
    engelle: 'Bloquer',
  },
  mesajlar: {
    baslik: 'Messages',
    bosBaslik: 'Pas encore de conversation',
    silinmisKullanici: 'Utilisateur supprimé',
    gizle: 'Masquer',
    istekler: 'Demandes',
    istekRozeti: 'Demande',
  },
  mesajIstekleri: {
    baslik: 'Demandes',
    aciklama: 'Les messages de personnes qui ne sont pas tes amis attendent ici. Si tu réponds, la discussion passe dans Messages.',
    bosBaslik: 'Aucune demande en attente',
    bosAciklama: "Si quelqu'un qui n'est pas ton ami t'écrit, tu verras le message ici.",
    kabul: 'Accepter',
    reddet: 'Refuser',
    geri: 'Messages',
  },
  hesabiSil: {
    baslik: 'Supprimer ton compte',
    uyari: "C'est irréversible. Si tu veux revenir, tu devras créer un nouveau compte depuis le début.",
    ipucu: "Ton profil, tes souvenirs, tes amitiés et ta liste de conversations sont supprimés. Tes messages restent dans l'historique de l'autre personne, mais ton nom n'est plus affiché.",
    dondur: 'Plutôt geler mon compte',
    parolaEtiket: 'Saisis ton mot de passe pour confirmer',
    parolaYerTutucu: 'ton mot de passe',
    parolaGerekli: 'Saisis ton mot de passe pour confirmer.',
    sil: 'Supprimer définitivement mon compte',
  },
  sohbet: {
    baslik: 'Discussion',
    istekSeridi: "C'est une demande de message. Si tu réponds, la discussion passe dans Messages.",
    kabulEt: 'Accepter',
    reddet: 'Refuser',
    mesajYok: 'Pas encore de messages',
    yerTutucu: 'Écris un message...',
    kapaliKapi: 'Tu ne peux pas écrire à cette personne pour le moment.',
  },
  etkilesim: {
    profiliGor: 'Voir le profil de {{ad}}',
    begen: "J'aime",
    begeniyiKaldir: "Je n'aime plus",
    yorumlar: 'Commentaires',
    yorumSayisi: '{{sayi}} commentaires',
    yorumYaz: 'Écris un commentaire…',
    gonder: 'Envoyer',
    paylas: 'Partager',
    yorumSil: 'Supprimer le commentaire',
    yorumSilOnay: 'Supprimer ce commentaire ?',
    yorumSikayet: 'Signaler',
    yorumSikayetOnay: "Signaler ce commentaire ? Un commentaire signalé est masqué immédiatement et examiné par l'équipe de modération.",
    yorumSikayetEdildi: 'Ton signalement a été reçu et le commentaire a été masqué.',
    bosYorumBaslik: 'Pas encore de commentaires',
    bosYorumAciklama: 'Tu peux écrire le premier.',
    silinmisKullanici: 'Utilisateur supprimé',
  },
  anaSayfa: {
    aramaYerTutucu: 'Rechercher',
    suAnDisarida: 'Sortis en ce moment',
    disaridaSayi: '{{sayi}} personnes',
    disaridaDiger: 'Autres',
    disaridaErisim: '{{ad}}, à {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'ici en ce moment',
    bosBaslik: 'Ton fil est vide',
    bosAciklama: "Fais un check-in quelque part ou fais-toi des amis ; leurs check-ins apparaîtront ici.",
    kesfet: 'Explorer les lieux',
    azOnce: "à l'instant",
    dakika: 'il y a {{sayi}} min',
    saat: 'il y a {{sayi}} h',
    gun: 'il y a {{sayi}} j',
    silOnay: 'Supprimer définitivement ce check-in ?',
    silAciklama: "Le check-in, sa note et sa photo sont supprimés définitivement. Il ne restera pas non plus dans tes souvenirs ; c'est irréversible.",
    silAriza: "Le check-in n'a pas pu être supprimé.",
    haritadaGor: 'Voir {{ad}} sur la carte',
    secenekler: 'Options de la publication',
    fotografiBuyut: 'Agrandir la photo',
    duzenle: 'Modifier',
    arkadasEtiketle: 'Taguer un ami',
    duzenleBaslik: 'Modifier la publication',
    notEtiketi: 'Note',
    notYerTutucu: 'Ajouter une note',
    etiketlenenler: 'Tagués',
    etiketiKaldirEtiketi: 'Retirer le tag de {{ad}}',
    duzenleAriza: "La publication n'a pas pu être mise à jour.",
  },
  kullanici: {
    bulunamadi: 'Ce profil est introuvable',
    takipEt: 'Ajouter en ami',
    istekBeklemede: 'En attente',
    istegiGeriCek: 'Retirer la demande',
    bagiKopar: 'Retirer des amis',
    gelenIstekAciklama: "Si tu acceptes, vous pourrez voir les check-ins l'un de l'autre et vous écrire.",
    kabulEt: 'Accepter',
    reddet: 'Refuser',
    anilar: 'Souvenirs',
    enSik: 'Les plus visités',
    aniYok: 'Pas encore de souvenirs',
    profilKapali: 'Ce profil est privé',
    profilKapaliAciklama: 'Vous devez être amis pour voir ses souvenirs.',
    yerYok: 'Pas encore de lieux',
    sikayetEt: 'Signaler',
    engelle: 'Bloquer',
    engelleOnayi: "Si tu bloques, vous ne vous verrez plus nulle part et tous les messages entre vous seront supprimés définitivement. C'est irréversible.",
    engelleEvet: 'Oui, bloquer',
    vazgec: 'Annuler',
    geri: 'Retour',
    mesajYaz: 'Message',
    arkadassin: 'Amis',
    paylas: 'Partager le profil',
    paylasMetni: '{{ad}} sur Slooin : {{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'Modifier le profil',
    adEtiket: 'Nom complet',
    adYerTutucu: 'Ton nom complet',
    adHata: 'Saisis ton nom complet.',
    kullaniciAdiEtiket: "Nom d'utilisateur",
    biyografiEtiket: 'Bio',
    biyografiYerTutucu: 'Parle un peu de toi',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: "ton nom d'utilisateur",
    instagramIpucu: 'Tu peux aussi coller un lien. Non vérifié ; affiché comme lien sur ton profil.',
    bolgeEtiket: 'Où tu habites',
    bolgeSecilmedi: 'Non sélectionné',
    bolgeIpucu: 'Facultatif. Si tu en choisis un, il apparaît sur ton profil.',
    bolgeIlSec: 'Choisir la province',
    bolgeIlceSec: 'Choisir le district',
    bolgeKaldir: 'Retirer la région',
    instagramHata: "Un nom d'utilisateur Instagram se compose de lettres, de chiffres, de points et de tirets bas ; il ne peut ni commencer ni finir par un point.",
    kaydediliyor: 'Enregistrement…',
    kaydedildi: 'Ton profil a été mis à jour.',
  },
  ayarlar: {
    baslik: 'Réglages',
    geri: 'Retour',
    profilGizli: 'Profil privé',
    profilGizliAciklama: "Quand c'est activé, seuls tes amis voient tes souvenirs et tes check-ins. Ton nom, ton nom d'utilisateur et ta photo restent publics pour qu'on puisse te trouver et t'envoyer une demande d'amitié.",
    verilerimiIndir: 'Télécharger mes données',
    verilerimiIndirHazirlaniyor: 'Préparation…',
    verilerimiIndirHata: "Les données n'ont pas pu être préparées. Réessaie.",
    gizlilikMetni: 'Politique de confidentialité',
    bolumGorunurluk: 'Réglages de confidentialité',
    aniGorunurlugu: 'Mes souvenirs passés',
    etiketOnayi: 'Me demander avant de me taguer',
    etiketOnayiAciklama: "Quand c'est désactivé, tes amis peuvent te taguer directement. Quand c'est activé, on te demande d'abord ; personne ne voit le tag avant ton approbation.",
    aramadaGorun: 'Me montrer dans la recherche',
    aramadaGorunEtiket: 'Visibilité dans la recherche',
    bolumKisiler: 'Personnes',
    engellenenler: 'Bloqués',
    bolumHesapIslemleri: 'Compte',
    dondur: 'Geler mon compte',
    dondurAciklama: 'Tes données ne sont pas supprimées. Ton compte est réactivé automatiquement à ta prochaine connexion.',
    dondurEvet: 'Oui, geler',
    vazgec: 'Annuler',
    hesabiSil: 'Supprimer mon compte',
    cikisYap: 'Se déconnecter',
    aniHerkeseAcik: 'Tout le monde',
    aniTakipcilerim: 'Seulement mes abonnés',
    aniKimse: 'Personne',
    secilmedi: 'Non sélectionné',
  },
  kullaniciAdiEkrani: {
    yerTutucu: "Nouveau nom d'utilisateur",
    sonrakiDegisim: 'Tu pourras le changer à nouveau le : {{tarih}}',
  },
  aniGorunurlugu: {
    baslik: 'Mes souvenirs passés',
    geri: 'Retour',
    aciklama: "Ce choix s'applique à tous tes souvenirs, mais les souvenirs issus d'un check-in masqué ne sont pas concernés et restent privés.",
  },
  engellenenler: {
    baslik: 'Bloqués',
    engeliKaldir: 'Débloquer',
    bosBaslik: "Tu n'as bloqué personne",
    bosAciklama: "Si tu bloques quelqu'un, il apparaît ici et tu peux annuler depuis ici.",
    geri: 'Retour',
  },
  profil: {
    yerSayisi: 'Lieux',
    duzenle: 'Modifier le profil',
    paylas: 'Partager',
    paylasilamadi: "Le partage n'a pas pu s'ouvrir sur cet appareil.",
    sekmeAnilar: 'Souvenirs',
    sekmeYerler: 'Les plus visités',
    sekmeFotograflar: 'Photos',
    fotografSayisi: 'Photos',
    bosFotografBaslik: 'Pas encore de photos',
    bosFotografAciklama: 'Si tu ajoutes des photos en faisant un check-in, elles se rassemblent toutes ici.',
    bosArkadasBaslik: "Pas encore d'amis",
    kezSayisi: '{{sayi}} fois',
    bosYerBaslik: "Tu n'es encore allé nulle part",
    bosYerAciklama: 'Au fil de tes check-ins, les lieux que tu visites le plus sont classés ici.',
    ayarlar: 'Réglages',
    fotografEkle: 'Ajouter une photo de profil',
    fotografiBuyut: 'Agrandir la photo de profil',
    fotografKaldir: 'Retirer la photo',
    fotografKaldirOnay: 'Retirer ta photo ?',
    kapat: 'Fermer',
    aniSayisi: 'Souvenirs',
    bagSayisi: 'Amis',
    canliEtiket: 'Tu es ici en ce moment',
    ayril: 'Partir',
    canliSil: 'Supprimer',
    canliSilOnay: 'Supprimer définitivement ce check-in ? Il ne restera pas non plus dans tes souvenirs.',
    bosCanliBaslik: "Tu n'es nulle part en ce moment",
    bosCanliAciklama: 'Fais un check-in là où tu es et vois qui est là au même instant.',
    checkInYap: 'Faire un check-in quelque part',
    anilarBaslik: 'Souvenirs',
    bosAniBaslik: 'Pas encore de souvenirs',
    bosAniAciklama: 'Tes check-ins restent ici comme souvenirs.',
    profilYok: "Ton profil n'est pas encore prêt",
    profilYokAciklama: "Définis ton nom et ton nom d'utilisateur, puis continue depuis ici.",
    profilOlustur: 'Créer ton profil',
  },
  dogrula: {
    geri: 'Retour',
    baslik: 'Vérifie ton e-mail',
    aciklama: 'Nous avons envoyé un code à 6 chiffres à {{eposta}}.',
    kodEtiketi: 'Code de vérification',
    gonder: 'Vérifier',
    gonderiliyor: 'Vérification…',
    kodGelmedi: 'Tu n\'as pas reçu le code ?',
    spamNotu: "S'il n'est pas dans ta boîte de réception, regarde aussi dans les spams.",
    tekrarGonder: 'Renvoyer',
    tekrarBekle: 'Tu peux renvoyer dans {{saniye}} s',
    tekrarGonderildi: 'Un nouveau code a été envoyé.',
    hakKalmadi: 'Trop de codes ont été demandés pour cette adresse. Tu pourras réessayer dans une heure.',
    hataEksik: 'Saisis le code en entier.',
    zatenKayitliBaslik: 'Un compte existe déjà avec cette adresse',
    zatenKayitliAciklama: 'Un compte a déjà été créé avec {{eposta}}. Tu peux te connecter avec ton mot de passe.',
    girisYap: 'Se connecter',
    baskaNumara: 'Continuer avec une autre adresse',
  },
  altGezinme: {
    anaSayfa: 'Accueil',
    bildirimler: 'Notifications',
    mesajlar: 'Messages',
    profil: 'Profil',
  },
  arkadasSecici: {
    baslik: 'Tague tes amis',
    bos: "Tu n'as pas encore d'amis. Quand tu enverras une demande d'amitié et qu'elle sera acceptée, ils apparaîtront ici et tu pourras les taguer dans tes check-ins.",
    tamamSayili: 'OK ({{sayi}})',
  },
  harita: {
    cevre: 'Lieux autour de toi',
    kisiBurada: '{{ad}}, {{sayi}} personnes ici',
    buMekan: 'Ce lieu, {{durum}}',
    buradasin: 'Tu es ici',
  },
  sikayet: {
    baslik: 'Signaler',
    sebepSec: 'Choisis un motif',
    alindi: 'Ton signalement a été reçu',
    tesekkur: 'Merci de nous avoir prévenus.',
    mesajBaglami: "Pendant l'examen, les messages autour de celui-ci sont aussi ouverts à la modération.",
    aciklamaYerTutucu: 'Quelque chose à ajouter ?',
    sebepler: {
      taciz: 'Harcèlement ou intimidation',
      uygunsuz_icerik: 'Contenu inapproprié',
      sahte_hesap: 'Faux compte',
      spam: 'Spam ou publicité',
      diger: 'Autre',
    },
  },
  hesapDurumu: {
    askida: 'Ton compte est suspendu',
    yasakli: 'Ton compte a été définitivement fermé',
    sebep: 'Motif : {{sebep}}',
    bitis: 'Fin : {{tarih}}',
    ipucu: "Pendant ce temps, ton profil n'est pas visible par les autres et tu ne peux pas publier de nouveau contenu. Tes données n'ont pas été supprimées.",
    yenile: 'Actualiser',
    cikisYapilamadi: 'Déconnexion impossible',
  },
  checkIn: {
    baslik: 'Nouveau check-in',
    notYerTutucu: 'Ajoute une note (facultatif)',
    ilkUyariBaslik: 'Que partage ce check-in ?',
    ilkUyariMetin: "Quand tu fais un check-in, le lieu où tu es et ta note (s'il y en a une) deviennent visibles pour tes amis. Il se ferme tout seul quand le check-in expire ou dès que tu dis « Je suis parti ». Si tu veux, tu peux rendre ce check-in masqué et le garder seulement sur ton propre profil.",
    anladim: 'Compris',
    gizliYap: 'Rendre masqué',
    arkadasEkle: 'Ajouter des amis (facultatif)',
    arkadasEkleSecili: 'Ajouter des amis ({{sayi}} sélectionnés)',
    etiketiKaldir: 'Retirer le tag de {{ad}}',
    fotografEkle: 'Ajouter une photo (facultatif)',
    fotografDegistir: 'Changer la photo',
    fotografCek: 'Prendre une photo',
    galeridenSec: 'Choisir dans la galerie',
    kameraIzni: "L'autorisation de la caméra est nécessaire pour prendre une photo.",
    fotografYuklenemedi: "La photo n'a pas pu être envoyée ; ton check-in a été fait avec ta note",
    etiketlenemedi: "Ton check-in est fait, mais tes amis n'ont pas pu être tagués.",
    gonder: 'Faire un check-in',
    gonderiliyor: 'Check-in en cours...',
  },
  mekanDuzenle: {
    baslik: 'Corriger les infos',
    aciklama: "Quelque chose est faux ? Ta correction part à un modérateur ; une fois approuvée, elle est mise à jour pour tout le monde.",
    gonderildiBaslik: 'Ta demande a été envoyée',
    gonderildiMetin: "Les infos du lieu seront mises à jour quand un modérateur les aura examinées et approuvées.",
    bekleyenBaslik: 'Tu as une demande en attente',
    bekleyenMetin: "La demande que tu as envoyée pour ce lieu est encore en cours d'examen. Une fois traitée, tu pourras envoyer une nouvelle correction.",
    adEtiket: 'Nom du lieu',
    adYerTutucu: 'Nom du lieu',
    mahalle: 'Quartier',
    mahalleYerTutucu: 'ex. Alaaddinbey',
    adres: 'Adresse',
    adresYerTutucu: 'Rue, numéro',
    il: 'Province',
    ilYerTutucu: 'Bursa',
    ilce: 'District',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Type',
    kapakFotografi: 'Photo de couverture',
    fotografiKaldir: 'Retirer la photo',
    fotografEkle: 'Ajouter une photo',
    fotografSecilemedi: "La photo n'a pas pu être sélectionnée.",
    galeriIzni: "L'autorisation des photos est nécessaire pour choisir dans la galerie.",
    oturumYok: 'Session introuvable',
    zatenKapali: 'Ce lieu est déjà marqué comme définitivement fermé.',
    kapaliBaslik: 'Ce lieu est définitivement fermé',
    kapaliAciklama: "Si c'est approuvé, ce lieu est retiré des listes et de la recherche. Les check-ins faits ici ne sont pas supprimés.",
    onceDegistir: "Change d'abord quelque chose.",
    talebiGonder: 'Envoyer la demande',
  },
  mekanEkle: {
    baslik: 'Ajouter un nouveau lieu',
    adYerTutucu: 'Nom du lieu',
    turuSec: 'Choisis un type',
    adresYerTutucu: 'Adresse (facultatif)',
    adresSoru: 'Cette adresse est-elle correcte ?',
    adresAciklama: "Trouvée à partir de ta position. Si elle est fausse, tu peux modifier le champ ci-dessus.",
    dogru: 'Correcte',
    benzerBaslik: "Tu voulais dire l'un de ceux-ci ?",
    konumAlinamadi: 'Impossible de récupérer ta position, réessaie',
    adVeTurGerekli: 'Le nom et le type du lieu sont obligatoires',
    ekle: 'Ajouter',
    ekleniyor: 'Ajout...',
  },
  turGruplari: {
    'Yeme içme': 'Restauration',
    Gece: 'Vie nocturne',
    'Açık alan': 'Plein air',
    Kültür: 'Culture',
    Spor: 'Sport',
    Alışveriş: 'Shopping',
    Diğer: 'Autre',
  },
  turler: {
    Kafe: 'Café',
    Kahveci: 'Coffee shop',
    'Çay evi': 'Salon de thé',
    Restoran: 'Restaurant',
    Lokanta: 'Cantine',
    'Türk mutfağı': 'Cuisine turque',
    Kebapçı: 'Kebab',
    'Balık restoranı': 'Restaurant de poisson',
    Ocakbaşı: 'Grill',
    'Kahvaltı salonu': 'Salon de petit-déjeuner',
    Fırın: 'Boulangerie',
    'Fast food': 'Fast-food',
    Burgerci: 'Burger',
    Pizzacı: 'Pizzeria',
    Tatlıcı: 'Pâtisserie',
    Dondurmacı: 'Glacier',
    Bar: 'Bar',
    Pub: 'Pub',
    'Gece kulübü': 'Boîte de nuit',
    Meyhane: 'Taverne',
    'Nargile kafe': 'Salon de chicha',
    'Kokteyl barı': 'Bar à cocktails',
    Park: 'Parc',
    'Halk bahçesi': 'Jardin public',
    'Doğal alan': 'Espace naturel',
    Plaj: 'Plage',
    Meydan: 'Place',
    'Kamp alanı': 'Camping',
    Göl: 'Lac',
    Müze: 'Musée',
    Sinema: 'Cinéma',
    Tiyatro: 'Théâtre',
    'Sanat galerisi': "Galerie d'art",
    Kütüphane: 'Bibliothèque',
    'Tarihi yer': 'Site historique',
    'Konser salonu': 'Salle de concert',
    'Kültür merkezi': 'Centre culturel',
    'Spor salonu': 'Salle de sport',
    Stadyum: 'Stade',
    'Yüzme havuzu': 'Piscine',
    'Halı saha': 'Terrain de foot',
    AVM: 'Centre commercial',
    Market: 'Supermarché',
    Bakkal: 'Épicerie',
    'Giyim mağazası': 'Boutique de vêtements',
    Kitapçı: 'Librairie',
    Kuyumcu: 'Bijouterie',
    Otel: 'Hôtel',
    Eczane: 'Pharmacie',
    Hastane: 'Hôpital',
    Banka: 'Banque',
    Kuaför: 'Coiffeur',
    'Güzellik salonu': 'Salon de beauté',
    Üniversite: 'Université',
    'Canlı müzik': 'Musique live',
  },
  kesfet: {
    baslik: 'Check-in',
    harita: 'Carte',
    liste: 'Liste',
    turSuzgeci: 'Filtre par type',
    turFiltresi: 'Filtre par type',
    turBulunamadi: 'Aucun type à afficher autour de toi.',
    filtreyiKaldir: 'Retirer le filtre',
    tumunuSec: 'Tout sélectionner',
    temizle: 'Effacer',
    kaydet: 'Enregistrer',
    kaydetSayili: 'Enregistrer ({{sayi}})',
    tumu: 'Tous',
    sakin: 'Calme',
    yogun: 'Animé',
    populer: 'Populaire',
    yakinindakiMekanlar: 'Lieux près de toi',
    sonuclar: 'Résultats',
    kisiBurada: '{{sayi}} personnes ici',
    checkIn: 'Check-in',
    konumuGor: 'Voir le lieu',
    checkInYap: 'Faire un check-in ici',
    mekanAra: 'Rechercher des lieux',
    kisi: '{{sayi}} personnes',
    taraniyor: 'Recherche autour de toi…',
    cevreGorunmuyor: 'Nous ne voyons pas tes alentours',
    konumIzniAciklama: "Nous avons besoin de l'autorisation de localisation pour te montrer les lieux à proximité. Active-la dans les réglages du navigateur et réessaie.",
    konumuAc: 'Ouvrir {{ad}}',
    konumuGorEtiketi: 'Voir {{ad}}',
    checkInEtiketi: 'Faire un check-in à {{ad}}',
    filtreyiKaldirEtiketi: 'Retirer le filtre {{tur}}',
    kisiBuradaEtiket: 'personnes ici',
    suAnBuradasin: 'Tu es ici en ce moment',
    ayrildim: 'Je suis parti',
    araniyor: 'Recherche…',
    aramaBulunamadi: "Aucun lieu trouvé pour « {{arama}} ». Essaie de changer l'orthographe.",
    sonucSayisi: '{{sayi}} résultats',
    bosArama: 'Aucun résultat pour « {{arama}} » dans cette province.',
    bosFiltre: 'Aucun lieu à moins de 500 m avec ce filtre.',
    bosCevre: 'Aucun lieu près de toi.',
    mekanEkle: 'Tu ne trouves pas un lieu ? Ajoute-le',
    atif: 'Données des lieux : Foursquare · Quartier et district : © contributeurs OpenStreetMap',
  },
  checkInHaritasi: {
    geri: 'Retour',
    haritaAcikla: "Touche la carte pour l'itinéraire",
    haritadaAc: 'Itinéraire',
    secimBaslik: 'Quelle carte ouvrir ?',
    appleHaritalar: 'Plans (Apple)',
    googleHaritalar: 'Google Maps',
    vazgec: 'Annuler',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Photo de {{ad}}',
    menu: 'Options',
    yolTarifi: 'Itinéraire',
    buradaCheckIn: 'Faire un check-in ici',
    yaklas: 'Rapproche-toi pour faire un check-in · {{mesafe}}',
    buradasinAyril: 'Tu es ici · Partir',
    kapandi: 'Ce lieu est définitivement fermé',
    kapandiAciklama: "Tu ne peux plus faire de check-in ici et le lieu n'est plus affiché dans les listes. Tes souvenirs passés sont conservés.",
    kisiBurada: 'personnes ici',
    bugun: "Aujourd'hui",
    haritadaGoster: 'Montrer le lieu sur la carte',
    checkInSayisi: '{{sayi}} check-ins',
    kisiSayisi: '{{sayi}} personnes',
    ilcedekiYerler: 'lieux à {{ilce}}',
    siralamaYok: 'Pas de classement',
    suAnBurada: 'Ici en ce moment',
    diger: 'Autres',
    biri: "Quelqu'un",
    suAn: 'maintenant',
    liderlik: 'Classement',
    sonCheckInler: 'Récents',
    liderlikBos: "Pas encore de check-ins à afficher ici.",
    sonBos: "Pas encore de check-ins à afficher ici.",
    fotograflar: 'Photos',
    fotografBos: 'Pas encore de photos ici.',
    fotografAc: 'Agrandir la photo',
    dahaFazlaFotograf: 'Plus de photos',
    puan: 'Note',
    puanlamaSayisi: '{{sayi}} avis',
    puanYok: 'Pas encore de note',
    puanAzOy: 'Au moins 3 avis sont nécessaires pour une note',
    puanKotu: 'Mauvais',
    puanIyi: 'Bien',
    puanHarika: 'Génial',
    puanSoru: 'Comment as-tu trouvé ce lieu ?',
    puanSart: "Fais d'abord un check-in ici pour le noter.",
    puanGonder: 'Envoyer',
    puanGuncelle: 'Modifier ta note',
    puanGonderiliyor: 'Envoi…',
    puanTesekkur: 'Ta note a été enregistrée.',
  },
  giris: {
    epostaYerTutucu: 'Adresse e-mail',
    sifreYerTutucu: 'Mot de passe',
    gonder: 'Se connecter',
    gonderiliyor: 'Connexion…',
    kayitOl: 'Créer un nouveau compte',
    hataEposta: 'Saisis une adresse e-mail valide.',
    hataBos: 'Saisis ton adresse e-mail et ton mot de passe.',
    sifremiUnuttum: 'Mot de passe oublié ?',
  },
  sifreSifirla: {
    geri: 'Retour',
    baslik: 'Réinitialise ton mot de passe',
    aciklama: "Saisis l'adresse e-mail de ton compte et nous t'enverrons un code à 6 chiffres.",
    epostaYerTutucu: 'Adresse e-mail',
    kodGonder: 'Envoyer le code',
    gonderiliyor: 'Envoi…',
    hataEposta: 'Saisis une adresse e-mail valide.',
    hataHesapYok: 'Aucun compte trouvé avec cette adresse e-mail.',
    kodBaslik: 'Saisis le code',
    kodAciklama: 'Nous avons envoyé un code à 6 chiffres à {{eposta}}.',
    kodEtiketi: 'Code de vérification',
    dogrula: 'Vérifier',
    dogrulaniyor: 'Vérification…',
    hataEksik: 'Saisis le code en entier.',
    kodGelmedi: "Tu n'as pas reçu le code ?",
    spamNotu: "S'il n'est pas dans ta boîte de réception, regarde aussi dans les spams.",
    tekrarGonder: 'Renvoyer',
    tekrarBekle: 'Tu peux renvoyer dans {{saniye}} s',
    tekrarGonderildi: 'Un nouveau code a été envoyé.',
    hakKalmadi: 'Trop de codes ont été demandés pour cette adresse. Tu pourras réessayer dans une heure.',
    yeniBaslik: 'Définis ton nouveau mot de passe',
    yeniAciklama: 'Le code a été vérifié. Choisis maintenant un nouveau mot de passe.',
    sifreYerTutucu: 'Nouveau mot de passe (au moins {{adet}} caractères)',
    sifreTekrarYerTutucu: 'Nouveau mot de passe (encore une fois)',
    kaydet: 'Enregistrer le mot de passe',
    kaydediliyor: 'Enregistrement…',
    hataSifreKisa: 'Le mot de passe doit contenir au moins {{adet}} caractères.',
    hataSifreEslesmiyor: 'Les mots de passe ne correspondent pas.',
  },
  hatalar: {
    genel: 'Un problème est survenu. Réessaie dans un instant.',
    kullaniciAdi30Gun: "Tu peux changer ton nom d'utilisateur une fois tous les 30 jours. Il reste {{gun}} jours.",
    vt: {
      aski_bitisi_gelecekte_olmali: 'La fin de la suspension doit être dans le futur.',
      bir_moderatore_islem_uygulanamaz: "Aucune action ne peut être appliquée à un modérateur.",
      bu_kisiye_su_an_mesaj_gonderemezsin: 'Tu ne peux pas écrire à cette personne pour le moment.',
      bu_kullanici_adi_alinmis: "Ce nom d'utilisateur est pris, essaie-en un autre.",
      bu_kullanici_bulunamadi: 'Cet utilisateur est introuvable.',
      bu_fotograf_sana_ait_degil: "Cette photo ne t'appartient pas.",
      bu_il_listemizde_yok: "Cette province n'est pas dans notre liste.",
      bu_mekan_bulunamadi: 'Ce lieu est introuvable.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: "La demande que tu as envoyée pour ce lieu est encore en cours d'examen.",
      bu_mekan_kalici_olarak_kapandi: 'Ce lieu est définitivement fermé.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'Ce lieu est déjà marqué comme fermé.',
      bu_tur_listemizde_yok: "Ce type n'est pas dans notre liste.",
      en_az_bir_alan_doldurulmali: 'Tu dois changer au moins une info.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'Tu as atteint la limite quotidienne de corrections (5). Tu pourras réessayer demain.',
      hesabin_su_an_bu_islemi_yapamaz: 'Ton compte ne peut pas faire ça pour le moment.',
      bu_paylasim_bulunamadi: 'Cette publication est introuvable.',
      not_en_fazla_500_karakter_olabilir: 'La note peut contenir au plus 500 caractères.',
      bu_mesaji_sikayet_edemezsin: 'Tu ne peux pas signaler ce message.',
      bugunluk_istek_sinirina_ulastin: "Tu as atteint la limite de demandes d'aujourd'hui.",
      check_in_bulunamadi: 'Check-in introuvable.',
      cok_fazla_kimlik: "Trop d'identifiants envoyés.",
      en_az_2_karakter_gerekli: 'Saisis au moins 2 caractères.',
      gecersiz_bulunurluk_degeri: 'Valeur de disponibilité invalide.',
      gecersiz_gorunurluk_degeri: 'Valeur de visibilité invalide.',
      gecersiz_platform: 'Plateforme invalide.',
      gecersiz_sikayet_durumu: 'Statut de signalement invalide.',
      gecersiz_sikayet_hedefi: 'Cible de signalement invalide.',
      gerekce_belirtilmeli: 'Tu dois indiquer un motif.',
      geri_cekilecek_istek_bulunamadi: 'Aucune demande à retirer.',
      gunluk_mekan_ekleme_limitine_ulastin_5: "Tu as atteint la limite quotidienne d'ajout de lieux (5). Tu pourras réessayer demain.",
      hesabin_su_anda_kullanilamiyor: "Ton compte n'est pas disponible pour le moment.",
      hesabin_zaten_kullanilamaz_durumda: "Ton compte est déjà indisponible.",
      istegin_zaten_gonderilmis: 'Ta demande a déjà été envoyée.',
      jeton_bos_olamaz: 'Le jeton de notification ne peut pas être vide.',
      jeton_cok_uzun: 'Le jeton de notification est trop long.',
      kendi_mesajini_sikayet_edemezsin: 'Tu ne peux pas signaler ton propre message.',
      kendine_islem_uygulayamazsin: "Tu ne peux pas t'appliquer une action à toi-même.",
      kendine_istek_gonderemezsin: "Tu ne peux pas t'envoyer une demande à toi-même.",
      kendine_mesaj_gonderemezsin: "Tu ne peux pas t'écrire à toi-même.",
      kendini_engelleyemezsin: 'Tu ne peux pas te bloquer toi-même.',
      kendini_sikayet_edemezsin: 'Tu ne peux pas te signaler toi-même.',
      kimlik_dogrulamasi_gerekli: 'Tu dois être connecté pour ça.',
      konusma_bulunamadi: 'Conversation introuvable.',
      kullanici_adi_kurallara_uymuyor: "Le nom d'utilisateur ne respecte pas les règles.",
      kullanici_belirtilmeli: 'Un utilisateur doit être indiqué.',
      mekan_bulunamadi: 'Lieu introuvable.',
      gecersiz_puan: 'Note invalide.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: "Fais d'abord un check-in ici pour le noter.",
      mekana_cok_uzaksin_1_km_icinde_olmalisin: "Tu es trop loin du lieu. Pour faire un check-in, tu dois être à moins d'environ 1 kilomètre.",
      mekana_yakin_olmalisin_200_m_icinde: "Pour ajouter un lieu, tu dois être à moins d'environ 200 mètres.",
      mesaj_bos_olamaz: 'Le message ne peut pas être vide.',
      mesaj_bu_konusmada_bulunamadi: 'Le message est introuvable dans cette conversation.',
      mesaj_cok_uzun: 'Le message est trop long.',
      profil_bulunamadi: 'Profil introuvable.',
      sikayet_bulunamadi: 'Signalement introuvable.',
      sikayet_sebebi_belirtilmeli: 'Tu dois indiquer un motif de signalement.',
      yanitlanacak_istek_bulunamadi: 'Aucune demande à laquelle répondre.',
      yetkisiz: "Tu n'as pas l'autorisation pour ça.",
      zaten_bu_kullanici_adini_kullaniyorsun: "Tu utilises déjà ce nom d'utilisateur.",
    },
    kod: {
      '23505': 'Cet enregistrement existe déjà.',
      '57014': "L'opération a pris trop de temps. Réessaie.",
      otp_expired: 'Le code est invalide ou expiré. Demandes-en un nouveau.',
      user_already_exists: 'Un compte existe déjà avec cette adresse. Tu peux te connecter.',
      invalid_credentials: 'Adresse e-mail ou mot de passe incorrect.',
      over_request_rate_limit: 'Tu as essayé trop souvent. Attends un peu et réessaie.',
      over_sms_send_rate_limit: 'Trop de codes demandés. Attends un peu et réessaie.',
      weak_password: 'Le mot de passe est trop faible. Choisis-en un plus fort.',
      same_password: "Le nouveau mot de passe doit être différent de l'ancien.",
      signup_disabled: 'Les nouvelles inscriptions ne sont pas acceptées pour le moment.',
      phone_provider_disabled: 'Impossible d’envoyer un code à ce numéro pour le moment. Réessaie plus tard.',
    },
    metin: {
      sms_saglayici: 'Impossible d’envoyer un code à ce numéro pour le moment. Réessaie plus tard.',
      sms_saglayici2: 'Impossible d’envoyer un code à ce numéro pour le moment. Réessaie plus tard.',
      kod_gecersiz: 'Le code est invalide ou expiré. Demandes-en un nouveau.',
      zaten_kayitli: 'Un compte existe déjà avec cette adresse. Tu peux te connecter.',
      giris_hatali: 'Adresse e-mail ou mot de passe incorrect.',
      cok_sik: 'Tu as essayé trop souvent. Attends un peu et réessaie.',
      sifre_kisa: 'Le mot de passe est trop court.',
      sifre_ayni: "Le nouveau mot de passe doit être différent de l'ancien.",
      kayit_kapali: 'Les nouvelles inscriptions ne sont pas acceptées pour le moment.',
      ag_yok: "Impossible d'atteindre internet. Vérifie ta connexion et réessaie.",
      oturum_dustu: 'Ta session a expiré. Reconnecte-toi.',
    },
  },
} as const
