/**
 * Русские тексты. Зеркалит структуру ключей `tr.ts` 1:1; отсутствующий
 * ключ падает на турецкий, тест паритета
 * (`__tests__/ceviri-tamlik.test.ts`) ловит любое расхождение.
 */
export default {
  // HUKUKI EKRANLAR (i18n E asamasi, 2026-09-13): basliklar ve
  // "Turkce metin esastir" notu. Belgelerin kendisi lib/hukuki/ altinda.
  hukuki: {
    gizlilikBaslik: 'Уведомление о конфиденциальности',
    kosullarBaslik: 'Условия использования',
    sonGuncelleme: 'Последнее обновление: {{tarih}}',
    ustunlukNotu: 'Юридически обязательным является турецкий текст этого документа; перевод приведён только для ознакомления.',
  },

  ortak: {
    devam: 'Продолжить',
    iptal: 'Отмена',
    tumunuSec: 'Выбрать все',
    temizle: 'Очистить',
    kaydet: 'Сохранить',
    tekrarDene: 'Попробовать снова',
    yukleniyor: 'Загрузка…',
    birSorunOldu: 'Что-то пошло не так.',
    agYok: 'Нет подключения к интернету, попробуй снова',
    gonder: 'Отправить',
    gonderiliyor: 'Отправка…',
    tamam: 'Готово',
    sira: 'Место {{sira}}',
    sil: 'Удалить',
    vazgec: 'Отмена',
    geri: 'Назад',
    kapat: 'Закрыть',
    ara: 'Поиск',
    sonucYok: 'Ничего не найдено.',
  },
  karsilama: {
    baslik: 'Узнай, кто рядом, ',
    baslikVurgu: 'исследуй.',
    aciklama: 'Отмечайся, знакомься с новыми людьми.\nОткрывай популярные места вокруг.',
    kisiSayisi: '{{sayi}} чел.',
    disarida: '{{sayi}} чел. рядом с тобой',
    turKafe: 'Кафе',
    turRestoran: 'Ресторан',
    turBar: 'Бар',
    adim1Baslik: 'Отметься',
    adim1Aciklama: 'Будь заметен там, где ты есть',
    adim2Baslik: 'Кто рядом',
    adim2Aciklama: 'Найди людей в том же месте',
    adim3Baslik: 'Общайся',
    adim3Aciklama: 'Знакомься с новыми людьми',
    adim4Baslik: 'Открывай популярные места',
    adim4Aciklama: 'Смотри, где сейчас модно в твоём городе',
    hesapOlustur: 'Создать аккаунт',
    hesabinVarMi: 'Уже есть аккаунт?',
    girisYap: 'Войти',
    haritaAtfi: 'Данные карты © участники OpenStreetMap',
  },
  kayit: {
    baslik: 'Начни с электронной почты',
    epostaEtiket: 'Электронная почта',
    epostaYerTutucu: 'name@example.com',
    devam: 'Продолжить',
    veya: 'или',
    appleIle: 'Продолжить с Apple',
    googleIle: 'Продолжить с Google',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataEpostaKayitli: 'С этой почтой уже есть аккаунт. Можешь войти по паролю.',
    hataSaglayiciKapali: 'Этот способ входа сейчас недоступен. Можешь продолжить с электронной почтой.',
    telefonEtiket: 'Номер телефона',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Отправить код',
    gonderiliyor: 'Отправка…',
    zatenHesap: 'Уже есть аккаунт?',
    girisYap: 'Войти',
    hataTelefon: 'Введи действительный номер телефона.',
    hataZatenKayitli: 'С этим номером уже есть аккаунт. Можешь войти по паролю.',
  },
  profilOlustur: {
    baslik: 'Создать аккаунт',
    adYerTutucu: 'Твоё полное имя',
    adHata: 'Введи своё полное имя.',
    dogumEtiket: 'Дата рождения',
    dogumSec: 'День / Месяц / Год',
    dogumHataGecersiz: 'Выбери дату рождения.',
    dogumHataYas: 'Чтобы пользоваться Slooin, тебе должно быть не меньше 18.',
    tarihGun: 'День',
    tarihAy: 'Месяц',
    tarihYil: 'Год',
    tarihTamam: 'Готово',
    aylar: {
      1: 'Январь',
      2: 'Февраль',
      3: 'Март',
      4: 'Апрель',
      5: 'Май',
      6: 'Июнь',
      7: 'Июль',
      8: 'Август',
      9: 'Сентябрь',
      10: 'Октябрь',
      11: 'Ноябрь',
      12: 'Декабрь',
    },
    kullaniciAdiYerTutucu: 'Имя пользователя',
    kullaniciAdiIpucu: 'Имя пользователя не соответствует нужному формату.',
    kullaniciAdiKontrol: 'Проверка…',
    kullaniciAdiMusait: 'Это имя пользователя свободно.',
    kullaniciAdiAlinmis: 'Это имя пользователя занято, попробуй другое.',
    sifreEtiket: 'Пароль',
    sifreYerTutucu: 'Не меньше {{adet}} символов',
    tekrarEtiket: 'Повтори пароль',
    tekrarYerTutucu: 'Тот же пароль ещё раз',
    sifrelerFarkli: 'Пароли пока не совпадают.',
    sifreGoster: 'Показать пароль',
    sifreGizle: 'Скрыть пароль',
    hataSifreKisa: 'Пароль должен содержать не меньше {{adet}} символов.',
    hataSifreUyusmuyor: 'Пароли не совпадают. Проверь оба.',
    adimSayaci: 'Шаг {{simdiki}} / {{toplam}}',
    adim1Baslik: 'Давай познакомимся',
    adim1Aciklama: 'Твоё имя видно в профиле. Дата рождения никому не показывается.',
    adEtiket: 'Полное имя',
    adOrnek: 'напр. Анна Иванова',
    yasNotu: 'Slooin — для тех, кому 18 и старше.',
    adim2Baslik: 'Выбери имя пользователя',
    adim2Aciklama: '3–20 символов; может содержать строчные буквы, цифры, точки и подчёркивания.',
    kullaniciAdiEtiket: 'Твоё имя пользователя',
    // BOLGE ADIMI (kullanicinin istegi 2026-09-18): ulke -> il -> ilce; ZORUNLU, ayarlardan gizlenebilir.
    adim3Baslik: 'Где ты живёшь',
    adim3Aciklama: 'Никогда не показывается в профиле; хранится только вместе с аккаунтом.',
    bolgeUlkeEtiket: 'Страна',
    bolgeUlkeSec: 'Выбрать страну',
    bolgeIlEtiket: 'Провинция и район',
    bolgeIlSec: 'Выбрать провинцию',
    bolgeIlceSec: 'Выбрать район',
    bolgeYalnizcaUlke: 'Для этой страны нет списка провинций/районов; сохраняется только страна.',
    bolgeHata: 'Выбери провинцию и район.',

    adim4Baslik: 'Задай пароль',
    adim4Aciklama: 'С этим паролем ты будешь входить в аккаунт.',
    sifreUygun: 'Пароль достаточно длинный.',
    sifrelerAyni: 'Пароли совпадают.',
    devam: 'Продолжить',
    sozlesmeNotuOn: 'Создавая аккаунт, ты подтверждаешь, что принимаешь ',
    sozlesmeKosullar: 'Условия использования',
    sozlesmeNotuOrta: ' и прочитал(а) ',
    sozlesmeGizlilik: 'Политику конфиденциальности',
    sozlesmeNotuSon: '.',
    gonder: 'Создать аккаунт',
    gonderiliyor: 'Создание…',
    oturumDustu: 'Сессия истекла, войди снова.',
    beklenmeyenHata: 'Произошла непредвиденная ошибка.',
  },
  bildirimler: {
    baslik: 'Уведомления',
    arkadaslikBolumu: 'Запросы в друзья',
    etiketBolumu: 'Запросы на отметку',
    arkadaslikMetni: 'хочет добавить тебя в друзья.',
    etiketMetni: 'хочет отметить тебя в чек-ине в {{mekan}}.',
    hikayeEtiketMetni: "хочет отметить тебя в своём моменте.",
    hikayeEtiketMetniMekan: "хочет отметить тебя в своём моменте в {{mekan}}.",
    etkilesimBolumu: 'Взаимодействия',
    begeniMetni: 'понравилась ваша публикация',
    yorumMetni: 'прокомментировал(а) вашу публикацию',
    kabul: 'Принять',
    onayla: 'Подтвердить',
    reddet: 'Отклонить',
    bosBaslik: 'Ничего нового',
    bosAciklama: 'Здесь появляются запросы в друзья и те, кто хочет тебя отметить.',
  },
  kisiler: {
    baslik: 'Найти людей',
    yerTutucu: 'Имя пользователя или имя',
    enAzIki: 'Введи не меньше 2 символов.',
    bulunamadi: 'Никого не найдено.',
    ipucu: 'Можно искать по имени пользователя или по имени.',
  },
  arkadaslar: {
    baslik: 'Мои друзья',
    ara: 'Поиск по имени или нику',
    sayi: '{{sayi}} друзей',
    profiliGor: 'Открыть профиль',
    mesajGonder: 'Написать сообщение',
    davetBaslik: 'Открывай места с друзьями',
    davetMetin: 'Пригласи друзей в Slooin.',
    davetDugme: 'Пригласить друзей',
    davetMesaji: 'Присоединяйся ко мне в Slooin 👋',
  },
  baglar: {
    baslik: 'Друзья',
    arkadasliktanCikar: 'Удалить из друзей',
    bosArkadas: 'Друзей пока нет',
    engelle: 'Заблокировать',
  },
  mesajlar: {
    baslik: 'Сообщения',
    bosBaslik: 'Разговоров пока нет',
    silinmisKullanici: 'Удалённый пользователь',
    sil: 'Удалить',
    istekler: 'Запросы',
    istekRozeti: 'Запрос',
    silBaslik: 'Удалить беседу',
  },
  mesajIstekleri: {
    baslik: 'Запросы',
    aciklama: 'Здесь ждут сообщения от людей, которые не в твоих друзьях. Если ответишь, чат перейдёт в Сообщения.',
    bosBaslik: 'Ожидающих запросов нет',
    bosAciklama: 'Если тебе напишет кто-то не из друзей, сообщение появится здесь.',
    kabul: 'Принять',
    reddet: 'Отклонить',
    geri: 'Сообщения',
  },
  hesabiSil: {
    baslik: 'Удалить аккаунт',
    soru: 'Точно хочешь удалить аккаунт?',
    uyari: 'Это нельзя отменить. Если захочешь вернуться, придётся создать новый аккаунт.',
    araSoru: 'Нужна просто пауза?',
    dondur: 'Заморозить аккаунт',
    dogrulaBaslik: 'Подтверди личность',
    dogrulaAciklama: 'Подтверди аккаунт, чтобы продолжить удаление.',
    epostaEtiket: 'Твой адрес эл. почты',
    kodNot: 'На этот адрес придёт 6-значный код.',
    gizliAppleAdresi: '6-значный код пересылается на адрес, привязанный к твоему Apple ID.',
    kodGonder: 'Отправить код подтверждения',
    kodGonderildi: 'Код отправлен; действует 10 минут.',
    kodYerTutucu: '6-значный код',
    kodEksik: 'Введи все 6 цифр кода.',
    tekrarGonder: 'Отправить код ещё раз',
    epostaYok: 'У аккаунта нет адреса эл. почты. Напиши на destek@slooin.com.',
    appleIleDogrula: 'Подтвердить через Apple',
    googleIleDogrula: 'Подтвердить через Google',
    sil: 'Удалить аккаунт навсегда',
  },
  sohbet: {
    baslik: 'Чат',
    istekSeridi: 'Это запрос на переписку. Если ответишь, чат перейдёт в Сообщения.',
    kabulEt: 'Принять',
    reddet: 'Отклонить',
    mesajYok: 'Сообщений пока нет',
    yerTutucu: 'Напиши сообщение...',
    kapaliKapi: 'Сейчас ты не можешь написать этому человеку.',
    teslimEdildi: 'Доставлено',
    bugun: 'Сегодня',
    dun: 'Вчера',
  },
  etkilesim: {
    profiliGor: 'Открыть профиль {{ad}}',
    begen: 'Нравится',
    begeniyiKaldir: 'Убрать «нравится»',
    begenenler: 'Лайки',
    begenenYok: 'Пока нет лайков.',
    paylasimBaslik: 'Публикация',
    paylasimBulunamadi: 'Эта публикация больше недоступна.',
    yorumlar: 'Комментарии',
    yorumSayisi: '{{sayi}} комментариев',
    yorumYaz: 'Напиши комментарий…',
    gonder: 'Отправить',
    paylas: 'Поделиться',
    yorumSil: 'Удалить комментарий',
    yorumSilOnay: 'Удалить этот комментарий?',
    yorumSikayet: 'Пожаловаться',
    yorumSikayetOnay: 'Пожаловаться на этот комментарий? Комментарий сразу скрывается и проверяется командой модерации.',
    yorumSikayetEdildi: 'Жалоба получена, комментарий скрыт.',
    bosYorumBaslik: 'Комментариев пока нет',
    bosYorumAciklama: 'Ты можешь написать первый.',
    silinmisKullanici: 'Удалённый пользователь',
  },
  anaSayfa: {
    checkInYapti: '{{ad}} отметился в {{mekan}}{{ek}}.',
    ileBirlikte: 'вместе с {{adlar}}',
    aramaYerTutucu: 'Поиск',
    suAnDisarida: 'Сейчас на месте',
    disaridaSayi: '{{sayi}} чел.',
    disaridaDiger: 'Ещё',
    disaridaErisim: '{{ad}}, в {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'сейчас здесь',
    bosBaslik: 'Лента пуста',
    bosAciklama: 'Отметься где-нибудь или заведи друзей; их чек-ины появятся здесь.',
    kesfet: 'Исследовать места',
    azOnce: 'только что',
    dakika: '{{sayi}} мин назад',
    saat: '{{sayi}} ч назад',
    gun: '{{sayi}} дн назад',
    silOnay: 'Удалить этот чек-ин навсегда?',
    silAciklama: 'Чек-ин, его заметка и фото удаляются навсегда. В воспоминаниях он тоже не останется; это нельзя отменить.',
    silAriza: 'Не удалось удалить чек-ин.',
    haritadaGor: 'Показать {{ad}} на карте',
    secenekler: 'Действия с публикацией',
    fotografiBuyut: 'Увеличить фото',
    duzenle: 'Изменить',
    arkadasEtiketle: 'Отметить друга',
    duzenleBaslik: 'Изменить публикацию',
    notEtiketi: 'Заметка',
    notYerTutucu: 'Добавить заметку',
    etiketlenenler: 'Отмечены',
    etiketiKaldirEtiketi: 'Убрать отметку {{ad}}',
    duzenleAriza: 'Не удалось обновить публикацию.',
  },
  kullanici: {
    bulunamadi: 'Профиль не найден',
    takipEt: 'Добавить в друзья',
    istekBeklemede: 'Ожидает',
    istegiGeriCek: 'Отозвать запрос',
    geriCekOnayi: 'Отозвать запрос в друзья?',
    geriCekEvet: 'Да, отозвать',
    bagiKopar: 'Удалить из друзей',
    gelenIstekAciklama: 'Если примешь, вы будете видеть чек-ины друг друга и сможете переписываться.',
    kabulEt: 'Принять',
    reddet: 'Отклонить',
    anilar: 'Воспоминания',
    enSik: 'Чаще всего',
    aniYok: 'Воспоминаний пока нет',
    profilKapali: 'Это закрытый профиль',
    profilKapaliAciklama: 'Чтобы видеть воспоминания, нужно быть друзьями.',
    yerYok: 'Мест пока нет',
    fotografYok: 'Фото пока нет',
    arkadasYok: 'Друзей пока нет',
    secenekler: 'Действия с профилем',
    sikayetEt: 'Пожаловаться',
    sikayetEttinNotu: 'Ты пожаловался на этого пользователя',
    sikayetEttinAciklama: 'Твоя жалоба рассматривается. Пожаловаться на этого пользователя повторно нельзя.',
    engelle: 'Заблокировать',
    engelleOnayi: 'После блокировки вы нигде не будете видеть друг друга, а все сообщения между вами удалятся навсегда. Это нельзя отменить.',
    engelleEvet: 'Да, заблокировать',
    vazgec: 'Отмена',
    geri: 'Назад',
    fotografiAc: 'Открыть фото',
    mesajYaz: 'Написать',
    arkadassin: 'Друзья',
    paylas: 'Поделиться профилем',
    paylasMetni: '{{ad}} в Slooin: @{{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'Изменить профиль',
    adEtiket: 'Полное имя',
    adYerTutucu: 'Твоё полное имя',
    adHata: 'Введи своё полное имя.',
    kullaniciAdiEtiket: 'Имя пользователя',
    biyografiEtiket: 'О себе',
    biyografiYerTutucu: 'Расскажи немного о себе',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'твоё имя пользователя',
    instagramIpucu: 'Можно вставить и ссылку. Не проверяется; показывается в профиле как ссылка.',
    instagramHata: 'Имя пользователя Instagram состоит из букв, цифр, точек и подчёркиваний; не может начинаться или заканчиваться точкой.',
    kaydediliyor: 'Сохранение…',
    kaydedildi: 'Профиль обновлён.',
  },
  ayarlar: {
    baslik: 'Настройки',
    geri: 'Назад',
    profilGizli: 'Закрытый профиль',
    profilGizliAciklama: 'Когда включено, твои воспоминания и чек-ины видят только друзья. Имя, имя пользователя и фото остаются открытыми, чтобы тебя могли найти и отправить запрос в друзья.',
    verilerimiIndir: 'Скачать мои данные',
    verilerimiIndirHazirlaniyor: 'Подготовка…',
    verilerimiIndirHata: 'Не удалось подготовить данные. Попробуй снова.',
    gizlilikMetni: 'Политика конфиденциальности',
    bolumGorunurluk: 'Настройки приватности',
    etiketOnayi: 'Спрашивать перед отметкой',
    etiketOnayiAciklama: 'Когда выключено, друзья могут отмечать тебя сразу. Когда включено, тебя сначала спросят; никто не увидит отметку, пока ты не подтвердишь.',
    aramadaGorun: 'Показывать меня в поиске',
    aramadaGorunEtiket: 'Видимость в поиске',
    bolumKisiler: 'Люди',
    engellenenler: 'Заблокированные',
    bolumHesapIslemleri: 'Аккаунт',
    dondur: 'Заморозить аккаунт',
    dondurAciklama: 'Данные не удаляются. Аккаунт автоматически активируется при следующем входе.',
    dondurEvet: 'Да, заморозить',
    vazgec: 'Отмена',
    hesabiSil: 'Удалить аккаунт',
    cikisYap: 'Выйти',
    cikisOnayBaslik: 'Выйти из аккаунта?',
    cikisOnayAciklama: 'Ты выйдешь из своего аккаунта. Войти снова можно в любой момент.',
    secilmedi: 'Не выбрано',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'Новое имя пользователя',
    tekrarUyariBaslik: 'Имя пользователя можно менять раз в 24 часа',
    tekrarUyari: 'Ты уже менял имя пользователя сегодня. Подожди {{saat}} ч., чтобы изменить его снова.',
  },
  engellenenler: {
    baslik: 'Заблокированные',
    engeliKaldir: 'Разблокировать',
    bosBaslik: 'Ты никого не блокировал(а)',
    bosAciklama: 'Если ты кого-то заблокируешь, он появится здесь, и здесь же можно это отменить.',
    geri: 'Назад',
    altBaslik: 'Заблокированные не могут писать тебе и отправлять запросы в друзья.',
    engellendi: 'Заблокирован',
  },
  profil: {
    yerSayisi: 'Места',
    duzenle: 'Изменить профиль',
    paylas: 'Поделиться',
    paylasMetni: 'Добавь меня в Slooin 👋',
    paylasilamadi: 'Не удалось открыть «Поделиться» на этом устройстве.',
    sekmeAnilar: 'Воспоминания',
    sekmeYerler: 'Чаще всего',
    sekmeFotograflar: 'Фото',
    fotografSayisi: 'Фото',
    bosFotografBaslik: 'Фото пока нет',
    bosFotografAciklama: 'Если добавлять фото при чек-ине, все они соберутся здесь.',
    bosArkadasBaslik: 'Друзей пока нет',
    kezSayisi: '{{sayi}} раз',
    bosYerBaslik: 'Ты ещё нигде не был(а)',
    bosYerAciklama: 'С каждым чек-ином здесь выстраиваются места, где ты бываешь чаще всего.',
    ayarlar: 'Настройки',
    fotografEkle: 'Добавить фото профиля',
    fotografiBuyut: 'Увеличить фото профиля',
    fotografKaldir: 'Убрать фото',
    fotografKaldirOnay: 'Убрать фото?',
    kapat: 'Закрыть',
    aniSayisi: 'Воспоминания',
    bagSayisi: 'Друзья',
    canliEtiket: 'Ты сейчас здесь',
    ayril: 'Уйти',
    canliSil: 'Удалить',
    canliSilOnay: 'Удалить этот чек-ин навсегда? В воспоминаниях он тоже не останется.',
    bosCanliBaslik: 'Сейчас ты нигде',
    bosCanliAciklama: 'Отметься там, где ты есть, и увидишь, кто там в эту самую минуту.',
    checkInYap: 'Отметиться где-нибудь',
    anilarBaslik: 'Воспоминания',
    bosAniBaslik: 'Воспоминаний пока нет',
    bosAniAciklama: 'Твои чек-ины остаются здесь как воспоминания.',
    profilYok: 'Профиль ещё не готов',
    profilYokAciklama: 'Задай имя и имя пользователя и продолжай отсюда.',
    profilOlustur: 'Создать профиль',
  },
  dogrula: {
    geri: 'Назад',
    baslik: 'Подтверди почту',
    aciklama: 'Мы отправили 6-значный код на {{eposta}}.',
    kodEtiketi: 'Код подтверждения',
    gonder: 'Подтвердить',
    gonderiliyor: 'Проверка…',
    kodGelmedi: 'Код не пришёл?',
    spamNotu: 'Если его нет во входящих, проверь и папку «Спам».',
    tekrarGonder: 'Отправить снова',
    tekrarBekle: 'Отправить снова можно через {{saniye}} с',
    tekrarGonderildi: 'Новый код отправлен.',
    hakKalmadi: 'Для этого адреса запрошено слишком много кодов. Попробуй снова через час.',
    hataEksik: 'Введи код целиком.',
    zatenKayitliBaslik: 'С этим адресом уже есть аккаунт',
    zatenKayitliAciklama: 'Аккаунт с {{eposta}} уже создан. Можешь войти по паролю.',
    girisYap: 'Войти',
    baskaNumara: 'Продолжить с другим адресом',
  },
  altGezinme: {
    anaSayfa: 'Главная',
    bildirimler: 'Уведомления',
    mesajlar: 'Сообщения',
    profil: 'Профиль',
  },
  // HESAP VE GUVENLIK (kullanicinin referans gorselleri 2026-09-18).
  // GIZLILIK VE ETKILESIM (kullanicinin referans gorselleri 2026-09-18).
  gizlilikEtkilesim: {
    bolum: 'Приватность и взаимодействие',
    gizlilik: 'Приватность',
    gizlilikAciklama: 'Профиль, отметки и заблокированные',
    konum: 'Геолокация и чек-ин',
    konumAciklama: 'Разрешение на геолокацию и видимость в заведении',
    bildirimler: 'Уведомления',
    bildirimlerAciklama: 'Сообщения, друзья и воспоминания',
    gizlilikAlt: 'Ты решаешь, чем и с кем делиться.',
    kartBaslik: 'Границы задаёшь ты',
    kartMetin: 'Каждый выбор ясно говорит, что будет видно.',
    gorunurlugun: 'Твоя видимость',
    profilGorunurlugu: 'Видимость профиля',
    profilGorunurluguAciklama: 'Твои воспоминания и чек-ины',
    herkeseAcik: 'Для всех',
    sadeceArkadaslar: 'Только друзья',
    aramaGorunurlugu: 'Видимость в поиске',
    aramaGorunurluguAciklama: 'Тебя можно найти по имени пользователя',
    acik: 'Вкл',
    kapali: 'Выкл',
    sosyalIzinlerin: 'Социальные разрешения',
    etiketler: 'Отметки',
    etiketlerAciklama: 'Подтверждение и ожидающие отметки',
    onayli: 'С подтверждением',
    otomatik: 'Автоматически',
    mesajIzinleri: 'Кто может писать',
    mesajIzinleriAciklama: 'Кто может отправлять тебе сообщения?',
    herkes: 'Все',
    arkadaslar: 'Друзья',
    engellenenKisiler: 'Заблокированные',
    engellenenAciklama: 'Просмотр и управление блокировками',
    konumAlt: 'Разрешение на геолокацию и как ты выглядишь в заведении.',
    konumIzni: 'Геолокация',
    konumIzniAciklama: 'Нужна для заведений рядом и чек-ина',
    izinVerildi: 'Разрешена',
    izinYok: 'Не разрешена',
    ayarlariAc: 'Открыть настройки',
    mekandaGorunurluk: 'Видимость в заведении',
    mekandaGorunurlukAciklama: 'Кто видит тебя в заведении при чек-ине',
    kimse: 'Никто',
    mesajIzinleriAlt: 'Выбери, кто может писать тебе новые сообщения.',
    herkesAciklama: 'Запрос могут отправить и те, кто не в друзьях.',
    yalnizcaArkadaslarim: 'Только мои друзья',
    yalnizcaArkadaslarimAciklama: 'Новые беседы могут начинать только друзья.',
    hicKimse: 'Никто',
    hicKimseAciklama: 'Не получать новые запросы на сообщения.',
    etiketOnayBaslik: 'Сначала подтверждать отметки',
    etiketOnayAciklama: 'Когда друзья отмечают тебя, отметка скрыта, пока ты её не подтвердишь.',
    bekleyenEtiketler: 'Ожидающие отметки',
    bekleyenEtiketlerAciklama: 'Подтвердить или отклонить',
    bekleyenYok: 'Ожидающих отметок нет.',
    profilGorunurluguAlt: 'Выбери, кто видит твои воспоминания и чек-ины.',
    profilAcikAciklama: 'Твои воспоминания и чек-ины видны всем.',
    profilArkadasAciklama: 'Видят только друзья. Имя, имя пользователя и фото остаются открытыми.',
    aramaGorunurluguAlt: 'Выбери, можно ли найти тебя в поиске людей.',
    aramaAcikAciklama: 'Тебя находят по имени пользователя или имени.',
    aramaKapaliAciklama: 'В поиске тебя нет; найти можно только по ссылке.',
    etiketlerAlt: 'Управляй тем, как друзья отмечают тебя.',
    mekanHerkesAciklama: 'Тебя видят все в заведении.',
    mekanArkadasAciklama: 'Видят только друзья.',
    mekanKimseAciklama: 'В заведении тебя не показывают; чек-ин всё равно попадает в воспоминания.',
    konumErisimi: 'Доступ к геолокации',
    uygulamayiKullanirken: 'При использовании приложения',
    izinSorulmadi: 'Ещё не запрашивался',
    konumIzniYonet: 'Управление геолокацией',
    konumIzniYol: 'Изменить разрешение можно в Настройках телефона → Slooin → Геолокация.',
    anladim: 'Понятно',
  },
  hesapGuvenlik: {
    satirBaslik: 'Аккаунт и безопасность',
    satirAciklama: 'Почта, пароль и активные сеансы',
    bolumHesabin: 'Твой аккаунт',
    baslik: 'Аккаунт и безопасность',
    altBaslik: 'Управляй данными входа и безопасностью аккаунта.',
    girisBilgilerin: 'Данные входа',
    epostaAdresi: 'Адрес эл. почты',
    sifreyiDegistir: 'Сменить пароль',
    sifreAciklama: 'Используй пароль только для этого аккаунта',
    guvenlik: 'Безопасность',
    acikOturumlar: 'Активные сеансы',
    acikOturumlarAciklama: 'Управляй устройствами, где выполнен вход',
    cihazSayisi: '{{sayi}} устр.',
    koruBaslik: 'Защити аккаунт',
    koruMetin: 'Никому не сообщай пароль и коды подтверждения.',
    epostaAlt: 'Адрес, по которому ты входишь в аккаунт.',
    mevcutAdres: 'Текущий адрес',
    yeniAdres: 'Новый адрес эл. почты',
    yeniAdresYerTutucu: 'imya@primer.com',
    epostaNot: 'Сначала попросим подтвердить текущий адрес, затем новый. Адрес входа не изменится, пока новый не подтверждён.',
    devamEt: 'Продолжить',
    epostaGecersiz: 'Введи корректный адрес.',
    epostaAyni: 'Это уже твой текущий адрес.',
    mevcutKodBaslik: 'Подтверди текущий адрес',
    yeniKodBaslik: 'Подтверди новый адрес',
    kodMetin: 'Мы отправили 6-значный код на {{eposta}}.',
    kodYerTutucu: '6-значный код',
    dogrula: 'Подтвердить',
    tekrarGonder: 'Отправить код ещё раз',
    kodEksik: 'Введи 6-значный код.',
    epostaDegisti: 'Адрес эл. почты обновлён.',
    sifreAlt: 'Задай надёжный пароль только для этого аккаунта.',
    mevcutSifre: 'Текущий пароль',
    yeniSifre: 'Новый пароль',
    yeniSifreTekrar: 'Повтори новый пароль',
    sifreIpucu: 'Не менее 12 символов. Выбери длинный пароль, который используешь только в Slooin.',
    sifreGuncelle: 'Обновить пароль',
    sifremiUnuttum: 'Я забыл(а) пароль',
    sifreNot: 'При смене пароля сеансы на других устройствах закрываются.',
    sifreKisa: 'Новый пароль должен быть не короче 12 символов.',
    sifreEslesmiyor: 'Новые пароли не совпадают.',
    mevcutSifreYanlis: 'Текущий пароль неверный.',
    sifreDegisti: 'Пароль обновлён. Сеансы на других устройствах закрыты.',
    digerCihazlarKapatilamadi: 'Пароль обновлён, но другие устройства не удалось отключить.',
    oturumlarAlt: 'Проверь устройства, где открыт твой аккаунт.',
    buCihaz: 'Это устройство',
    sonEtkinlik: 'Последняя активность: {{zaman}}',
    digerCihazlardanCik: 'Выйти из других сеансов',
    cihazBilinmeyen: 'Неизвестное устройство',
    oturumKapatildi: 'Сеанс закрыт.',
    digerleriKapatildi: 'Сеансы на других устройствах закрыты.',
    suAndaKullaniliyor: 'Используется сейчас',
    kapat: 'Закрыть',
    oturumNot: 'Если видишь незнакомое устройство, закрой сеанс и смени пароль.',
  },
  arkadasSecici: {
    baslik: 'Отметь друзей',
    bos: 'Друзей пока нет. Когда ты отправишь запрос в друзья и его примут, они появятся здесь, и ты сможешь отмечать их в чек-инах.',
    tamamSayili: 'Готово ({{sayi}})',
  },
  harita: {
    cevre: 'Места вокруг тебя',
    kisiBurada: '{{ad}}, здесь {{sayi}} чел.',
    buMekan: 'Это место, {{durum}}',
    buradasin: 'Ты здесь',
    kumeEtiketi: 'Мест: {{sayi}}, нажмите, чтобы приблизить',
    konumaDon: 'К моему местоположению',
    adEtiketi: 'Подпись {{ad}}',
  },
  // HIKAYELER (2026-09-22): ana sayfa seridi, ekleme, izleyici.
  // GALERI SAYFASI (check-in formu ve check-in duzenleme; alttan
  // gelen sayfa: ilk kare kamera, sonra telefonun son fotograflari).
  galeri: {
    baslik: 'Выбери фото',
    sonFotograflar: 'Последние фото',
    kamera: 'Камера',
    galeridenSec: 'Выбрать из галереи',
    ekle: 'Добавить ({{adet}})',
  },
  hikaye: {
    notEkle: 'Заметка',
    flas: 'Вспышка',
    kamerayiCevir: 'Сменить камеру',
    konumEkle: "Добавить место",
    konumSec: "Выбери место",
    konumAraniyor: "Ищем места рядом…",
    konumYok: "Рядом не найдено мест.",
    arsivBaslik: "Архив моментов",
    arsivAciklama: "Его видишь только ты. Через 24 часа моменты уходят из ленты и остаются здесь.",
    arsivBos: "У тебя пока нет моментов.",
    arsivAc: "Открыть архив моментов",
    canliKameraYok: "Для живой камеры нужна последняя версия приложения. Сфотографировать можно и круглой кнопкой.",
    kameraIzniKapali: "Доступ к камере выключен.",
    izinVer: "Разрешить",
    ayarlariAc: "Открыть настройки",
    fotografSecBaslik: "Добавить в момент",
    kamerayiAc: 'Открыть камеру',
    galeriyiAc: 'Открыть галерею',
    sonFotograflar: 'Недавние фото',
    birFotografSec: 'Выбери фото',
    fotografSecildi: 'Выбрано фото: {{sayi}}',
    ileri: 'Далее',
    fotografSec: 'Выбрать фото',
    mekanEkle: 'Место',
    etiketle: 'Отметить',
    gorunurlukSec: 'Кто увидит',
    arkadaslar: 'Друзья',
    herkese: 'Все',
    ifadeEkle: 'Эмоция',
    arkadasEkle: 'Друг',
    etiketKaldir: 'Убрать отметку {{ad}}',
    tepkiGonder: 'Отправить реакцию {{emoji}}',
    tepkiGonderildi: '{{emoji}} отправлено',
    sonrakiKisi: 'Следующий человек',
    oncekiKisi: 'Предыдущий человек',
    hikayen: "Момент",
    hikayeEkle: "Добавить момент",
    kisininHikayesi: "Момент: {{ad}}",
    ekleBaslik: "Добавить момент",
    kamera: 'Сделать фото',
    galeri: 'Выбрать из галереи',
    kameraIzni: 'Для съёмки нужно разрешение на камеру.',
    yaziYerTutucu: 'Напиши что-нибудь…',
    mekanEtiketi: 'Метка места',
    mekanKaldir: 'Убрать метку места',
    mekanIpucu: 'Если у тебя есть активный чекин, место добавится автоматически.',
    sureAciklama: "Твой момент виден друзьям 24 часа.",
    paylas: 'Поделиться',
    paylasiliyor: 'Публикуем…',
    paylasildi: "Твой момент опубликован",
    mesajGonder: 'Отправить сообщение',
    yanitYerTutucu: 'Напиши ответ…',
    yanitOnEki: "Ответ на твой момент:",
    yanitGonderildi: 'Ответ отправлен',
    gonder: 'Отправить',
    gorenler: 'Просмотры',
    kisiGordu: 'Просмотрели: {{sayi}}',
    gorenYok: 'Пока никто не посмотрел.',
    secenekler: "Настройки момента",
    sil: "Удалить момент",
    silBaslik: "Удалить этот момент?",
    silAciklama: "Момент будет удалён для всех. Это действие нельзя отменить.",
    silEvet: 'Удалить',
    sonraki: 'Далее',
    onceki: 'Назад',
    duraklat: 'Пауза',
    kapat: 'Закрыть',
    yukleniyor: "Загрузка момента…",
    bulunamadi: "Этот момент больше недоступен.",
  },

  sikayet: {
    sebepSec: 'Выбери причину',
    mesajBaglami: 'При проверке модерации открываются и соседние сообщения.',
    baslik: 'Пожаловаться',
    kahramanBaslik: 'Расскажи, что случилось',
    altBaslikHesap: 'Почему ты жалуешься на этот аккаунт?',
    altBaslikMesaj: 'Почему ты жалуешься на это сообщение?',
    altBaslikHikaye: "Почему ты жалуешься на этот момент?",
    ekAciklama: 'Дополнительно',
    istegeBagli: 'Необязательно',
    aciklamaYerTutucu: 'Кратко опиши, что произошло.',
    aciklamaIpucu: 'Это поможет нам разобраться.',
    fotografEkle: 'Добавить фото',
    fotografDegistir: 'Изменить фото',
    fotografKaldir: 'Убрать фото',
    fotografCek: 'Сделать фото',
    galeridenSec: 'Выбрать из галереи',
    kameraIzni: 'Для съёмки нужен доступ к камере.',
    fotografYuklenemedi: 'Не удалось загрузить фото, попробуйте ещё раз.',
    gonder: 'Отправить жалобу',
    alindi: 'Жалоба получена',
    tesekkur: 'Спасибо, что сообщил(а).\nЖалоба передана на рассмотрение.',
    engelleSoru: 'Заблокировать этот аккаунт?',
    engelleAciklama: 'Он не сможет писать тебе и взаимодействовать с тобой.',
    hesabiEngelle: 'Заблокировать',
    engellendi: 'Аккаунт заблокирован',
    tamam: 'Готово',
    sebepler: {
      taciz: 'Домогательства или травля',
      uygunsuz_icerik: 'Неприемлемый контент',
      sahte_hesap: 'Поддельный аккаунт',
      spam: 'Спам или реклама',
      diger: 'Другое',
    },
  },
  hesapDurumu: {
    askida: 'Аккаунт приостановлен',
    yasakli: 'Аккаунт закрыт навсегда',
    sebep: 'Причина: {{sebep}}',
    bitis: 'До: {{tarih}}',
    ipucu: 'В это время твой профиль не виден другим, и ты не можешь публиковать новое. Данные не удалены.',
    yenile: 'Обновить',
    cikisYapilamadi: 'Не удалось выйти',
  },
  checkIn: {
    baslik: 'Новый чек-ин',
    degistir: 'Изменить',
    istegeBagli: 'Заметка, фото и друзья — по желанию.',
    notEtiket: 'Твоя заметка',
    notYerTutucu: 'Напиши что-нибудь об этом моменте...',
    fotografEtiket: 'Фото',
    fotografEkle: 'Добавить фото',
    fotografKaldir: 'Убрать фото',
    arkadasEtiketle: 'Отметить друзей',
    kimlerle: 'С кем ты?',
    birlikte: 'Вместе с',
    ekle: 'Добавить',
    etiketiKaldir: 'Убрать отметку {{ad}}',
    fotografCek: 'Сделать фото',
    galeridenSec: 'Выбрать из галереи',
    kameraIzni: 'Для съёмки нужен доступ к камере.',
    fotografYuklenemedi: 'Фото не загрузилось; чек-ин сделан с заметкой',
    etiketlenemedi: 'Чек-ин сделан, но друзей отметить не удалось.',
    gorunurlukNotu: 'Видимость определяется настройками приватности.',
    gonder: 'Отметиться',
    paylas: 'Поделиться чек-ином',
    gonderiliyor: 'Отправка...',
    // IFADE SECICI (2026-09-21)
    ifadeEkle: 'Добавить настроение',
    ifadeBaslik: 'Как ты, чем занимаешься?',
    ifadeKaldir: 'Убрать настроение',
    // CHECK-IN'I DUZENLE sayfasi + coklu fotograf (2026-09-21)
    duzenleBaslik: 'Изменить чекин',
    fotograflar: 'Фото',
    kameraVeyaGaleri: 'Камера или галерея',
    ifade: 'Настроение',
    istegeBagliKisa: 'Необязательно',
    fotografSayisi: '{{n}} фото',
    ifadeEkleAlt: 'Добавь настроение к этому моменту',
    birlikteAlt: 'Отметь друзей',
    degistirmekIcinDokun: 'Нажми, чтобы изменить',
  },
  mekanDuzenle: {
    baslik: 'Исправить данные',
    aciklama: 'Что-то не так? Твоё исправление уйдёт модератору; после одобрения оно обновится для всех.',
    gonderildiBaslik: 'Запрос отправлен',
    gonderildiMetin: 'Данные места обновятся, когда модератор проверит и одобрит.',
    bekleyenBaslik: 'У тебя есть ожидающий запрос',
    bekleyenMetin: 'Запрос по этому месту ещё рассматривается. Когда он будет решён, ты сможешь отправить новое исправление.',
    adEtiket: 'Название места',
    adYerTutucu: 'Название места',
    mahalle: 'Район (махалле)',
    mahalleYerTutucu: 'напр. Alaaddinbey',
    adres: 'Адрес',
    adresYerTutucu: 'Улица, номер',
    il: 'Провинция',
    ilYerTutucu: 'Bursa',
    ilce: 'Район',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Тип',
    kapakFotografi: 'Обложка',
    fotografiKaldir: 'Убрать фото',
    fotografEkle: 'Добавить фото',
    fotografSecilemedi: 'Не удалось выбрать фото.',
    galeriIzni: 'Чтобы выбрать из галереи, нужен доступ к фото.',
    oturumYok: 'Сессия не найдена',
    zatenKapali: 'Это место уже отмечено как закрытое навсегда.',
    kapaliBaslik: 'Это место закрылось навсегда',
    kapaliAciklama: 'Если одобрят, место уберут из списков и поиска. Сделанные здесь чек-ины не удаляются.',
    onceDegistir: 'Сначала что-нибудь измени.',
    talebiGonder: 'Отправить запрос',
  },
  mekanEkle: {
    baslik: 'Добавить новое место',
    adYerTutucu: 'Название места',
    turuSec: 'Выбери тип',
    adresYerTutucu: 'Адрес (необязательно)',
    adresSoru: 'Этот адрес верный?',
    adresAciklama: 'Найден по твоему местоположению. Если неверный, отредактируй поле выше.',
    dogru: 'Верный',
    benzerBaslik: 'Может, ты имел(а) в виду одно из этих?',
    konumAlinamadi: 'Не удалось определить местоположение, попробуй снова',
    adVeTurGerekli: 'Нужны название и тип места',
    ekle: 'Добавить',
    ekleniyor: 'Добавление...',
  },
  turGruplari: {
    'Yeme içme': 'Еда и напитки',
    Gece: 'Ночная жизнь',
    'Açık alan': 'На открытом воздухе',
    Kültür: 'Культура',
    Spor: 'Спорт',
    Alışveriş: 'Покупки',
    Diğer: 'Другое',
  },
  turler: {
    Kafe: 'Кафе',
    Kahveci: 'Кофейня',
    'Çay evi': 'Чайная',
    Restoran: 'Ресторан',
    Lokanta: 'Столовая',
    'Türk mutfağı': 'Турецкая кухня',
    Kebapçı: 'Кебабная',
    'Balık restoranı': 'Рыбный ресторан',
    Ocakbaşı: 'Гриль-бар',
    'Kahvaltı salonu': 'Завтраки',
    Fırın: 'Пекарня',
    'Fast food': 'Фастфуд',
    Burgerci: 'Бургерная',
    Pizzacı: 'Пиццерия',
    Tatlıcı: 'Кондитерская',
    Dondurmacı: 'Мороженое',
    Bar: 'Бар',
    Pub: 'Паб',
    'Gece kulübü': 'Ночной клуб',
    Meyhane: 'Таверна',
    'Nargile kafe': 'Кальянная',
    'Kokteyl barı': 'Коктейль-бар',
    Park: 'Парк',
    'Halk bahçesi': 'Городской сад',
    'Doğal alan': 'Природная зона',
    Plaj: 'Пляж',
    Meydan: 'Площадь',
    'Kamp alanı': 'Кемпинг',
    Göl: 'Озеро',
    Müze: 'Музей',
    Sinema: 'Кинотеатр',
    Tiyatro: 'Театр',
    'Sanat galerisi': 'Художественная галерея',
    Kütüphane: 'Библиотека',
    'Tarihi yer': 'Историческое место',
    'Konser salonu': 'Концертный зал',
    'Kültür merkezi': 'Культурный центр',
    'Spor salonu': 'Спортзал',
    Stadyum: 'Стадион',
    'Yüzme havuzu': 'Бассейн',
    'Halı saha': 'Футбольное поле',
    AVM: 'Торговый центр',
    Market: 'Супермаркет',
    Bakkal: 'Продуктовый магазин',
    'Giyim mağazası': 'Магазин одежды',
    Kitapçı: 'Книжный',
    Kuyumcu: 'Ювелирный',
    Otel: 'Отель',
    Eczane: 'Аптека',
    Hastane: 'Больница',
    Banka: 'Банк',
    Kuaför: 'Парикмахерская',
    'Güzellik salonu': 'Салон красоты',
    Üniversite: 'Университет',
    'Canlı müzik': 'Живая музыка',
  },
  kesfet: {
    baslik: 'Чек-ин',
    harita: 'Карта',
    liste: 'Список',
    turSuzgeci: 'Фильтр по типу',
    turFiltresi: 'Фильтр по типу',
    turBulunamadi: 'Вокруг тебя нет типов для показа.',
    filtreyiKaldir: 'Убрать фильтр',
    tumunuSec: 'Выбрать все',
    temizle: 'Очистить',
    kaydet: 'Сохранить',
    kaydetSayili: 'Сохранить ({{sayi}})',
    tumu: 'Все',
    sakin: 'Тихо',
    yogun: 'Людно',
    populer: 'Популярно',
    yakinindakiMekanlar: 'Места рядом с тобой',
    mesafeyeGore: 'По расстоянию',
    mesafe: 'Расстояние',
    aktifCheckIn: 'АКТИВНЫЙ ЧЕК-ИН',
    mesafeSec: 'Выбрать расстояние',
    mesafeIcinde: 'В радиусе {{mesafe}}',
    mesafeTumu: 'В радиусе 1 км',
    digerMekanlar: 'Показать другие места',
    yakinMekanlariGoster: 'Показать места рядом',
    paneliKapat: 'Закрыть список',
    yolTarifi: 'Маршрут',
    sonuclar: 'Результаты',
    kisiBurada: 'здесь {{sayi}} чел.',
    checkIn: 'Чек-ин',
    konumuGor: 'Показать место',
    checkInYap: 'Отметиться здесь',
    mekanAra: 'Поиск мест',
    kisi: '{{sayi}} чел.',
    taraniyor: 'Осматриваемся вокруг…',
    cevreGorunmuyor: 'Мы не видим, что вокруг тебя',
    konumIzniAciklama: 'Чтобы показать места рядом, нужен доступ к местоположению. Включи его в настройках браузера и попробуй снова.',
    konumuAc: 'Открыть {{ad}}',
    konumuGorEtiketi: 'Показать {{ad}}',
    checkInEtiketi: 'Отметиться в {{ad}}',
    filtreyiKaldirEtiketi: 'Убрать фильтр {{tur}}',
    kisiBuradaEtiket: 'чел. здесь',
    suAnBuradasin: 'Ты сейчас здесь',
    ayrildim: 'Я ушёл',
    araniyor: 'Поиск…',
    aramaBulunamadi: 'По запросу «{{arama}}» мест не найдено. Попробуй изменить написание.',
    sonucSayisi: 'Результатов: {{sayi}}',
    bosArama: 'В этой провинции по запросу «{{arama}}» ничего нет.',
    bosFiltre: 'С этим фильтром в радиусе 500 м мест нет.',
    bosCevre: 'Рядом с тобой мест нет.',
    mekanEkle: 'Не нашёл место? Добавь его',
    atif: 'Данные о местах: Foursquare · Район: © участники OpenStreetMap',
  },
  checkInHaritasi: {
    geri: 'Назад',
    haritaAcikla: 'Нажми на карту, чтобы построить маршрут',
    haritadaAc: 'Маршрут',
    secimBaslik: 'Какую карту открыть?',
    appleHaritalar: 'Apple Карты',
    googleHaritalar: 'Google Карты',
    vazgec: 'Отмена',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Фото {{ad}}',
    menu: 'Действия',
    yolTarifi: 'Маршрут',
    buradaCheckIn: 'Отметиться здесь',
    yaklas: 'Подойди ближе, чтобы отметиться · {{mesafe}}',
    buradasinAyril: 'Ты здесь · Уйти',
    kapandi: 'Это место закрылось навсегда',
    kapandiAciklama: 'Здесь больше нельзя отметиться, и место не показывается в списках. Твои прошлые воспоминания остаются.',
    kisiBurada: 'чел. здесь',
    bugun: 'Сегодня',
    haritadaGoster: 'Показать место на карте',
    checkInSayisi: '{{sayi}} чек-инов',
    kisiSayisi: '{{sayi}} чел.',
    ilcedekiYerler: 'мест в {{ilce}}',
    siralamaYok: 'Нет рейтинга',
    suAnBurada: 'Сейчас здесь',
    diger: 'Ещё',
    biri: 'Кто-то',
    suAn: 'сейчас',
    liderlik: 'Лидеры',
    sonCheckInler: 'Недавние',
    liderlikBos: 'Здесь пока нет чек-инов для показа.',
    sonBos: 'Здесь пока нет чек-инов для показа.',
    fotograflar: 'Фото',
    fotografBos: 'Здесь пока нет фото.',
    fotografAc: 'Увеличить фото',
    dahaFazlaFotograf: 'Ещё фото',
    puan: 'Оценка',
    puanlamaSayisi: '{{sayi}} оценок',
    puanYok: 'Оценок пока нет',
    puanAzOy: 'Для балла нужно не меньше 3 оценок',
    puanKotu: 'Плохо',
    puanIyi: 'Хорошо',
    puanHarika: 'Отлично',
    puanSoru: 'Как тебе это место?',
    puanSart: 'Сначала отметься здесь, чтобы оценить.',
    puanGonder: 'Отправить',
    puanGuncelle: 'Изменить оценку',
    puanGonderiliyor: 'Отправка…',
    puanTesekkur: 'Оценка сохранена.',
  },
  giris: {
    epostaYerTutucu: 'Электронная почта',
    sifreYerTutucu: 'Пароль',
    gonder: 'Войти',
    gonderiliyor: 'Вход…',
    kayitOl: 'Создать новый аккаунт',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataBos: 'Введи электронную почту и пароль.',
    sifremiUnuttum: 'Забыл(а) пароль?',
  },
  sifreSifirla: {
    geri: 'Назад',
    baslik: 'Сбросить пароль',
    aciklama: 'Введи почту аккаунта, и мы отправим 6-значный код.',
    epostaYerTutucu: 'Электронная почта',
    kodGonder: 'Отправить код',
    gonderiliyor: 'Отправка…',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataHesapYok: 'Аккаунт с этой почтой не найден.',
    kodBaslik: 'Введи код',
    kodAciklama: 'Мы отправили 6-значный код на {{eposta}}.',
    kodEtiketi: 'Код подтверждения',
    dogrula: 'Подтвердить',
    dogrulaniyor: 'Проверка…',
    hataEksik: 'Введи код целиком.',
    kodGelmedi: 'Код не пришёл?',
    spamNotu: 'Если его нет во входящих, проверь и папку «Спам».',
    tekrarGonder: 'Отправить снова',
    tekrarBekle: 'Отправить снова можно через {{saniye}} с',
    tekrarGonderildi: 'Новый код отправлен.',
    hakKalmadi: 'Для этого адреса запрошено слишком много кодов. Попробуй снова через час.',
    yeniBaslik: 'Задай новый пароль',
    yeniAciklama: 'Код подтверждён. Теперь выбери новый пароль.',
    sifreYerTutucu: 'Новый пароль (не меньше {{adet}} символов)',
    sifreTekrarYerTutucu: 'Новый пароль (ещё раз)',
    kaydet: 'Сохранить пароль',
    kaydediliyor: 'Сохранение…',
    hataSifreKisa: 'Пароль должен содержать не меньше {{adet}} символов.',
    hataSifreEslesmiyor: 'Пароли не совпадают.',
  },
  hatalar: {
    genel: 'Что-то пошло не так. Попробуй чуть позже.',
    kullaniciAdi24Saat: 'Имя пользователя можно менять раз в 24 часа. Осталось {{saat}} ч.',
    vt: {
      ayni_anda_en_fazla_10_hikayen_olabilir: "Одновременно можно иметь не больше 10 активных моментов.",
      hikaye_yazisi_en_fazla_200_karakter_olabilir: "Текст момента может содержать не больше 200 символов.",
      bu_hikayeyi_sikayet_edemezsin: "Ты не можешь пожаловаться на этот момент.",
      hikaye_bulunamadi: "Момент не найден.",
      parola_yanlis: 'Неверный пароль.',
      su_anda_dogrulanamadi: 'Сейчас не удалось проверить, попробуйте чуть позже.',
      silme_su_anda_tamamlanamadi: 'Удаление сейчас не удалось завершить, попробуйте снова.',
      giris_taze_degil: 'Код подтверждения не проверен или истёк; отправьте код снова.',
      silme_onayi_gerekli: 'Сначала подтвердите код, затем удаляйте.',
      aski_bitisi_gelecekte_olmali: 'Окончание блокировки должно быть в будущем.',
      bir_moderatore_islem_uygulanamaz: 'К модератору нельзя применить действие.',
      bu_kisiye_su_an_mesaj_gonderemezsin: 'Сейчас ты не можешь написать этому человеку.',
      bu_kullanici_adi_alinmis: 'Это имя пользователя занято, попробуй другое.',
      bu_kullanici_bulunamadi: 'Пользователь не найден.',
      bu_fotograf_sana_ait_degil: 'Это фото не твоё.',
      bu_il_listemizde_yok: 'Этой провинции нет в нашем списке.',
      bu_mekan_bulunamadi: 'Место не найдено.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'Запрос по этому месту ещё рассматривается.',
      bu_mekan_kalici_olarak_kapandi: 'Это место закрылось навсегда.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'Это место уже отмечено как закрытое.',
      bu_tur_listemizde_yok: 'Этого типа нет в нашем списке.',
      en_az_bir_alan_doldurulmali: 'Нужно изменить хотя бы одно поле.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'Достигнут дневной лимит исправлений (5). Попробуй завтра.',
      hesabin_su_an_bu_islemi_yapamaz: 'Твой аккаунт сейчас не может это сделать.',
      bu_paylasim_bulunamadi: 'Публикация не найдена.',
      not_en_fazla_500_karakter_olabilir: 'Заметка может содержать не больше 500 символов.',
      bu_mesaji_sikayet_edemezsin: 'На это сообщение нельзя пожаловаться.',
      bugunluk_istek_sinirina_ulastin: 'Достигнут лимит запросов на сегодня.',
      check_in_bulunamadi: 'Чек-ин не найден.',
      cok_fazla_kimlik: 'Отправлено слишком много идентификаторов.',
      en_az_2_karakter_gerekli: 'Введи не меньше 2 символов.',
      gecersiz_bulunurluk_degeri: 'Недопустимое значение доступности.',
      gecersiz_ifade: 'Это выражение настроения не распознано; обновите приложение.',
      kendi_anina_ifade_atamazsin: "Нельзя отправить настроение к своему моменту.",
      en_fazla_5_fotograf: 'К чекину можно добавить не более 5 фото.',
      gecersiz_gorunurluk_degeri: 'Недопустимое значение видимости.',
      gecersiz_platform: 'Недопустимая платформа.',
      gecersiz_sikayet_durumu: 'Недопустимый статус жалобы.',
      gecersiz_sikayet_hedefi: 'Недопустимая цель жалобы.',
      gerekce_belirtilmeli: 'Нужно указать причину.',
      geri_cekilecek_istek_bulunamadi: 'Запрос для отзыва не найден.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'Достигнут дневной лимит добавления мест (5). Попробуй завтра.',
      hesabin_su_anda_kullanilamiyor: 'Твой аккаунт сейчас недоступен.',
      hesabin_zaten_kullanilamaz_durumda: 'Твой аккаунт уже недоступен.',
      istegin_zaten_gonderilmis: 'Запрос уже отправлен.',
      jeton_bos_olamaz: 'Токен уведомлений не может быть пустым.',
      jeton_cok_uzun: 'Токен уведомлений слишком длинный.',
      kendi_mesajini_sikayet_edemezsin: 'Нельзя пожаловаться на своё сообщение.',
      kendine_islem_uygulayamazsin: 'Нельзя применить действие к себе.',
      kendine_istek_gonderemezsin: 'Нельзя отправить запрос самому себе.',
      kendine_mesaj_gonderemezsin: 'Нельзя написать самому себе.',
      kendini_engelleyemezsin: 'Нельзя заблокировать самого себя.',
      kendini_sikayet_edemezsin: 'Нельзя пожаловаться на самого себя.',
      kimlik_dogrulamasi_gerekli: 'Для этого нужно войти.',
      konusma_bulunamadi: 'Разговор не найден.',
      kullanici_adi_kurallara_uymuyor: 'Имя пользователя не соответствует правилам.',
      kullanici_belirtilmeli: 'Нужно указать пользователя.',
      mekan_bulunamadi: 'Место не найдено.',
      gecersiz_puan: 'Недопустимая оценка.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'Сначала отметься здесь, чтобы оценить.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'Ты слишком далеко от места. Чтобы отметиться, нужно быть в пределах примерно 1 км.',
      mekana_yakin_olmalisin_200_m_icinde: 'Чтобы добавить место, нужно быть в пределах примерно 200 м от него.',
      mesaj_bos_olamaz: 'Сообщение не может быть пустым.',
      mesaj_bu_konusmada_bulunamadi: 'Сообщение не найдено в этом разговоре.',
      mesaj_cok_uzun: 'Сообщение слишком длинное.',
      profil_bulunamadi: 'Профиль не найден.',
      sikayet_bulunamadi: 'Жалоба не найдена.',
      sikayet_sebebi_belirtilmeli: 'Нужно указать причину жалобы.',
      yanitlanacak_istek_bulunamadi: 'Запрос для ответа не найден.',
      yetkisiz: 'У тебя нет прав на это.',
      zaten_bu_kullanici_adini_kullaniyorsun: 'Ты уже используешь это имя пользователя.',
    },
    kod: {
      '23505': 'Такая запись уже есть.',
      '57014': 'Операция заняла слишком много времени. Попробуй снова.',
      otp_expired: 'Код недействителен или истёк. Запроси новый.',
      user_already_exists: 'С этим адресом уже есть аккаунт. Можешь войти.',
      invalid_credentials: 'Неверная почта или пароль.',
      over_request_rate_limit: 'Слишком много попыток. Подожди немного и попробуй снова.',
      over_sms_send_rate_limit: 'Запрошено слишком много кодов. Подожди немного и попробуй снова.',
      weak_password: 'Пароль слишком слабый. Выбери надёжнее.',
      same_password: 'Новый пароль должен отличаться от старого.',
      signup_disabled: 'Новые регистрации сейчас не принимаются.',
      phone_provider_disabled: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
    },
    metin: {
      sms_saglayici: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
      sms_saglayici2: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
      kod_gecersiz: 'Код недействителен или истёк. Запроси новый.',
      zaten_kayitli: 'С этим адресом уже есть аккаунт. Можешь войти.',
      giris_hatali: 'Неверная почта или пароль.',
      cok_sik: 'Слишком много попыток. Подожди немного и попробуй снова.',
      sifre_kisa: 'Пароль слишком короткий.',
      sifre_ayni: 'Новый пароль должен отличаться от старого.',
      kayit_kapali: 'Новые регистрации сейчас не принимаются.',
      ag_yok: 'Нет доступа к интернету. Проверь подключение и попробуй снова.',
      oturum_dustu: 'Сессия истекла. Войди снова.',
    },
  },

  bildirimAyarlari: {
    altBaslik: "Когда и о чём тебе сообщать?",
    anlik: "Push-уведомления",
    anlikAciklama: "Уведомления Slooin на твоём телефоне.",
    insanlar: "Люди и взаимодействие",
    arkadaslik: "Запросы в друзья",
    arkadaslikAciklama: "Новые запросы и принятые дружбы.",
    mesajlar: "Сообщения",
    mesajlarAciklama: "Новые сообщения и запросы на переписку.",
    etiketler: "Отметки",
    etiketlerAciklama: "Запросы на отметку и подтверждения.",
    kesif: "Открытия и воспоминания",
    aniHatirlatma: "Напоминания о воспоминаниях",
    aniHatirlatmaAciklama: "Вспомни свои лучшие моменты.",
    etkilesim: 'Лайки и комментарии',
    etkilesimAciklama: 'Люди, которым нравятся ваши публикации или которые их комментируют',
    sessiz: "Тихие часы",
    geceSessiz: "Не беспокоить ночью",
    geceSessizAciklama: "С 22:00 до 08:00 push-уведомления не отправляются.",
    sessizNot: "Тихие часы работают по местному времени устройства. Уведомления внутри приложения и непрочитанные сообщения сохраняются.",
    cihazAyarlari: "Настройки уведомлений устройства",
    izinYonet: "Управление разрешением на уведомления",
    izinYol: "Разрешить или отключить уведомления можно в разделе Настройки → Уведомления → Slooin на телефоне.",
  },

  uygulama: {
    bolum: "Приложение",
    gorunum: "Оформление",
    gorunumAciklama: "Тема и настройки движения",
    tema: "Тема",
    temaSistem: "Как в системе",
    temaSistemAciklama: "Следовать оформлению устройства.",
    temaAcik: "Светлая",
    temaAcikAciklama: "Светлый и простой вид.",
    temaKoyu: "Тёмная",
    temaKoyuAciklama: "Мягче при слабом освещении.",
    yardim: "Центр помощи",
    yardimAciklama: "Найти ответ или сообщить о проблеме",
    yardimAlt: "Давай вместе найдём ответы на твои вопросы.",
    sikSorulanlar: "Частые вопросы",
    sorunBildir: "Сообщить о проблеме",
    sorunKonu: "Сообщение о проблеме в Slooin",
    soru1: "Как работает закрытый профиль?",
    cevap1: "Когда профиль закрыт, твои воспоминания и чекины видят только друзья. Имя, имя пользователя и фото профиля остаются открытыми, чтобы тебя могли найти и отправить запрос в друзья. Чтобы добавить закрытый профиль, нужен запрос; открытый профиль добавляется сразу. Изменить можно в Настройки → Приватность → Видимость профиля.",
    soru2: "Моё местоположение передаётся постоянно?",
    cevap2: "Нет. Местоположение передаётся только при чекине. Через час или когда ты нажимаешь «Уйти», чекин становится воспоминанием; в этот момент координаты удаляются, и остаётся только место. При поиске мест координаты устройства отправляются на сервер, но не сохраняются.",
    soru3: "Как заблокировать человека?",
    cevap3: "Открой профиль человека и нажми «Заблокировать» в меню справа вверху. Заблокированный не сможет писать тебе и отправлять запросы в друзья, а переписка между вами удаляется с обеих сторон. Разблокировать можно в Настройки → Приватность → Заблокированные.",
    soru4: "Чем заморозка аккаунта отличается от удаления?",
    cevap4: "Заморозка временная: профиль становится невидимым, данные сохраняются, и при следующем входе аккаунт открывается сам. Удаление окончательное: аккаунт и данные не восстановить; сообщения и жалобы становятся анонимными. Оба действия — в Настройки → Управление аккаунтом.",
    hakkinda: "О Slooin",
    hakkindaAciklama: "Правила сообщества и юридическая информация",
    hakkindaAlt: "Правила и документы, которые вместе делают Slooin хорошим местом.",
    birlikteDahaIyi: "Вместе лучше",
    toplulukKurallari: "Правила сообщества",
    toplulukAciklama: "Уважительное и безопасное пространство",
    gizlilikPolitikasi: "Политика конфиденциальности",
    gizlilikPolitikasiAciklama: "Как обрабатываются твои данные",
    kullanimKosullari: "Условия использования",
    kullanimKosullariAciklama: "Правила пользования",
    surum: "Slooin {{surum}}",
  },

  toplulukKurallari: {
    baslik: "Правила сообщества",
    giris: "Slooin создан, чтобы знакомиться с новыми людьми в реальных местах. Чтобы это было безопасно, все должны соблюдать эти правила.",
    k1b: "Будь уважительным",
    k1m: "Оскорбления, травля, угрозы и язык вражды запрещены. Никто не обязан продолжать разговор, которого не хочет.",
    k2b: "Будь настоящим",
    k2m: "Не выдавай себя за другого, не создавай поддельные аккаунты и не используй чужое фото как фото профиля.",
    k3b: "Уважай чужую приватность",
    k3m: "Не публикуй фото, местоположение или личные данные человека без его согласия. Отмеченный человек может убрать отметку.",
    k4b: "Встречайся безопасно",
    k4m: "Встречайся с новыми знакомыми в людных, открытых местах. Если чувствуешь себя небезопасно — уходи, заблокируй человека и пожалуйся.",
    k5b: "Не публикуй вводящий в заблуждение контент",
    k5m: "Ложные чекины, неверные данные о местах, реклама и спам запрещены. Исправления мест проходят проверку модератора.",
    k6b: "Будь старше 18",
    k6m: "Slooin только для людей от 18 лет. Аккаунты с ложным возрастом закрываются.",
    kapanis: "Аккаунты, нарушающие правила, могут получить предупреждение, быть приостановлены или закрыты навсегда. Увидел проблему — пожалуйся; каждую жалобу рассматривает модератор.",
  },

  hesapYonetimi: {
    bolum: "Действия с аккаунтом",
    satirBaslik: "Управление аккаунтом",
    satirAciklama: "Заморозка и удаление",
    baslik: "Управление аккаунтом",
    altBaslik: "Сделай паузу или закрой аккаунт навсегда.",
    dondur: "Заморозить аккаунт",
    dondurAciklama: "Можно вернуться в любой момент",
    sil: "Удалить аккаунт",
    silAciklama: "Запросить окончательное удаление",
    kartBaslik: "Сохрани свои воспоминания",
    kartMetin: "Перед этим ты можешь скачать копию своих данных.",
  },
} as const
