/**
 * Русские тексты. Зеркалит структуру ключей `tr.ts` 1:1; отсутствующий
 * ключ падает на турецкий, тест паритета
 * (`__tests__/ceviri-tamlik.test.ts`) ловит любое расхождение.
 */
export default {
  ortak: {
    devam: 'Продолжить',
    iptal: 'Отмена',
    tumunuSec: 'Выбрать все',
    temizle: 'Очистить',
    kaydet: 'Сохранить',
    tekrarDene: 'Попробовать снова',
    yukleniyor: 'Загрузка…',
    birSorunOldu: 'Что-то пошло не так.',
    agYok: 'Нет подключения к интернету, попробуй снова',
    gonder: 'Отправить',
    gonderiliyor: 'Отправка…',
    tamam: 'Готово',
    sira: 'Место {{sira}}',
    sil: 'Удалить',
    vazgec: 'Отмена',
    geri: 'Назад',
    kapat: 'Закрыть',
    ara: 'Поиск',
    sonucYok: 'Ничего не найдено.',
  },
  karsilama: {
    baslik: 'Узнай, кто рядом, ',
    baslikVurgu: 'исследуй.',
    aciklama: 'Отмечайся, знакомься с новыми людьми.\nОткрывай популярные места вокруг.',
    kisiSayisi: '{{sayi}} чел.',
    disarida: '{{sayi}} чел. рядом с тобой',
    turKafe: 'Кафе',
    turRestoran: 'Ресторан',
    turBar: 'Бар',
    adim1Baslik: 'Отметься',
    adim1Aciklama: 'Будь заметен там, где ты есть',
    adim2Baslik: 'Кто рядом',
    adim2Aciklama: 'Найди людей в том же месте',
    adim3Baslik: 'Общайся',
    adim3Aciklama: 'Знакомься с новыми людьми',
    adim4Baslik: 'Открывай популярные места',
    adim4Aciklama: 'Смотри, где сейчас модно в твоём городе',
    hesapOlustur: 'Создать аккаунт',
    hesabinVarMi: 'Уже есть аккаунт?',
    girisYap: 'Войти',
    haritaAtfi: 'Данные карты © участники OpenStreetMap',
  },
  kayit: {
    baslik: 'Начни с электронной почты',
    epostaEtiket: 'Электронная почта',
    epostaYerTutucu: 'name@example.com',
    devam: 'Продолжить',
    veya: 'или',
    appleIle: 'Продолжить с Apple',
    googleIle: 'Продолжить с Google',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataEpostaKayitli: 'С этой почтой уже есть аккаунт. Можешь войти по паролю.',
    hataSaglayiciKapali: 'Этот способ входа сейчас недоступен. Можешь продолжить с электронной почтой.',
    telefonEtiket: 'Номер телефона',
    telefonYerTutucu: '05XX XXX XX XX',
    gonder: 'Отправить код',
    gonderiliyor: 'Отправка…',
    zatenHesap: 'Уже есть аккаунт?',
    girisYap: 'Войти',
    hataTelefon: 'Введи действительный номер телефона.',
    hataZatenKayitli: 'С этим номером уже есть аккаунт. Можешь войти по паролю.',
  },
  profilOlustur: {
    baslik: 'Создать аккаунт',
    adYerTutucu: 'Твоё полное имя',
    adHata: 'Введи своё полное имя.',
    dogumEtiket: 'Дата рождения',
    dogumSec: 'День / Месяц / Год',
    dogumHataGecersiz: 'Выбери дату рождения.',
    dogumHataYas: 'Чтобы пользоваться Slooin, тебе должно быть не меньше 18.',
    tarihGun: 'День',
    tarihAy: 'Месяц',
    tarihYil: 'Год',
    tarihTamam: 'Готово',
    aylar: {
      1: 'Январь',
      2: 'Февраль',
      3: 'Март',
      4: 'Апрель',
      5: 'Май',
      6: 'Июнь',
      7: 'Июль',
      8: 'Август',
      9: 'Сентябрь',
      10: 'Октябрь',
      11: 'Ноябрь',
      12: 'Декабрь',
    },
    kullaniciAdiYerTutucu: 'Имя пользователя',
    kullaniciAdiIpucu: 'Имя пользователя не соответствует нужному формату.',
    kullaniciAdiKontrol: 'Проверка…',
    kullaniciAdiMusait: 'Это имя пользователя свободно.',
    kullaniciAdiAlinmis: 'Это имя пользователя занято, попробуй другое.',
    sifreEtiket: 'Пароль',
    sifreYerTutucu: 'Не меньше {{adet}} символов',
    tekrarEtiket: 'Повтори пароль',
    tekrarYerTutucu: 'Тот же пароль ещё раз',
    sifrelerFarkli: 'Пароли пока не совпадают.',
    sifreGoster: 'Показать пароль',
    sifreGizle: 'Скрыть пароль',
    hataSifreKisa: 'Пароль должен содержать не меньше {{adet}} символов.',
    hataSifreUyusmuyor: 'Пароли не совпадают. Проверь оба.',
    adimSayaci: 'Шаг {{simdiki}} / {{toplam}}',
    adim1Baslik: 'Давай познакомимся',
    adim1Aciklama: 'Твоё имя видно в профиле. Дата рождения никому не показывается.',
    adEtiket: 'Полное имя',
    adOrnek: 'напр. Анна Иванова',
    yasNotu: 'Slooin — для тех, кому 18 и старше.',
    adim2Baslik: 'Выбери имя пользователя',
    adim2Aciklama: '3–20 символов; может содержать строчные буквы, цифры, точки и подчёркивания.',
    kullaniciAdiEtiket: 'Твоё имя пользователя',
    adim3Baslik: 'Задай пароль',
    adim3Aciklama: 'С этим паролем ты будешь входить в аккаунт.',
    sifreUygun: 'Пароль достаточно длинный.',
    sifrelerAyni: 'Пароли совпадают.',
    devam: 'Продолжить',
    sozlesmeNotuOn: 'Создавая аккаунт, ты подтверждаешь, что принимаешь ',
    sozlesmeKosullar: 'Условия использования',
    sozlesmeNotuOrta: ' и прочитал(а) ',
    sozlesmeGizlilik: 'Политику конфиденциальности',
    sozlesmeNotuSon: '.',
    gonder: 'Создать аккаунт',
    gonderiliyor: 'Создание…',
    oturumDustu: 'Сессия истекла, войди снова.',
    beklenmeyenHata: 'Произошла непредвиденная ошибка.',
  },
  bildirimler: {
    baslik: 'Уведомления',
    arkadaslikBolumu: 'Запросы в друзья',
    etiketBolumu: 'Запросы на отметку',
    arkadaslikMetni: 'хочет добавить тебя в друзья.',
    etiketMetni: 'хочет отметить тебя в чек-ине в {{mekan}}.',
    kabul: 'Принять',
    onayla: 'Подтвердить',
    reddet: 'Отклонить',
    bosBaslik: 'Ничего нового',
    bosAciklama: 'Здесь появляются запросы в друзья и те, кто хочет тебя отметить.',
  },
  kisiler: {
    baslik: 'Найти людей',
    yerTutucu: 'Имя пользователя или имя',
    enAzIki: 'Введи не меньше 2 символов.',
    bulunamadi: 'Никого не найдено.',
    ipucu: 'Можно искать по имени пользователя или по имени.',
  },
  baglar: {
    baslik: 'Друзья',
    arkadasliktanCikar: 'Удалить из друзей',
    bosArkadas: 'Друзей пока нет',
    engelle: 'Заблокировать',
  },
  mesajlar: {
    baslik: 'Сообщения',
    bosBaslik: 'Разговоров пока нет',
    silinmisKullanici: 'Удалённый пользователь',
    gizle: 'Скрыть',
    istekler: 'Запросы',
    istekRozeti: 'Запрос',
  },
  mesajIstekleri: {
    baslik: 'Запросы',
    aciklama: 'Здесь ждут сообщения от людей, которые не в твоих друзьях. Если ответишь, чат перейдёт в Сообщения.',
    bosBaslik: 'Ожидающих запросов нет',
    bosAciklama: 'Если тебе напишет кто-то не из друзей, сообщение появится здесь.',
    kabul: 'Принять',
    reddet: 'Отклонить',
    geri: 'Сообщения',
  },
  hesabiSil: {
    baslik: 'Удалить аккаунт',
    uyari: 'Это нельзя отменить. Если захочешь вернуться, придётся создать новый аккаунт с нуля.',
    ipucu: 'Профиль, воспоминания, дружбы и список разговоров удаляются. Твои сообщения остаются в истории собеседника, но твоё имя больше не показывается.',
    dondur: 'Лучше заморозить аккаунт',
    parolaEtiket: 'Введи пароль для подтверждения',
    parolaYerTutucu: 'твой пароль',
    parolaGerekli: 'Введи пароль для подтверждения.',
    sil: 'Удалить мой аккаунт навсегда',
  },
  sohbet: {
    baslik: 'Чат',
    istekSeridi: 'Это запрос на переписку. Если ответишь, чат перейдёт в Сообщения.',
    kabulEt: 'Принять',
    reddet: 'Отклонить',
    mesajYok: 'Сообщений пока нет',
    yerTutucu: 'Напиши сообщение...',
    kapaliKapi: 'Сейчас ты не можешь написать этому человеку.',
  },
  etkilesim: {
    profiliGor: 'Открыть профиль {{ad}}',
    begen: 'Нравится',
    begeniyiKaldir: 'Убрать «нравится»',
    yorumlar: 'Комментарии',
    yorumSayisi: '{{sayi}} комментариев',
    yorumYaz: 'Напиши комментарий…',
    gonder: 'Отправить',
    paylas: 'Поделиться',
    yorumSil: 'Удалить комментарий',
    yorumSilOnay: 'Удалить этот комментарий?',
    yorumSikayet: 'Пожаловаться',
    yorumSikayetOnay: 'Пожаловаться на этот комментарий? Комментарий сразу скрывается и проверяется командой модерации.',
    yorumSikayetEdildi: 'Жалоба получена, комментарий скрыт.',
    bosYorumBaslik: 'Комментариев пока нет',
    bosYorumAciklama: 'Ты можешь написать первый.',
    silinmisKullanici: 'Удалённый пользователь',
  },
  anaSayfa: {
    aramaYerTutucu: 'Поиск',
    suAnDisarida: 'Сейчас на месте',
    disaridaSayi: '{{sayi}} чел.',
    disaridaDiger: 'Ещё',
    disaridaErisim: '{{ad}}, в {{mekan}}',
    baslik: 'slooin',
    suAnBurada: 'сейчас здесь',
    bosBaslik: 'Лента пуста',
    bosAciklama: 'Отметься где-нибудь или заведи друзей; их чек-ины появятся здесь.',
    kesfet: 'Исследовать места',
    azOnce: 'только что',
    dakika: '{{sayi}} мин назад',
    saat: '{{sayi}} ч назад',
    gun: '{{sayi}} дн назад',
    silOnay: 'Удалить этот чек-ин навсегда?',
    silAciklama: 'Чек-ин, его заметка и фото удаляются навсегда. В воспоминаниях он тоже не останется; это нельзя отменить.',
    silAriza: 'Не удалось удалить чек-ин.',
    haritadaGor: 'Показать {{ad}} на карте',
    secenekler: 'Действия с публикацией',
    fotografiBuyut: 'Увеличить фото',
    duzenle: 'Изменить',
    arkadasEtiketle: 'Отметить друга',
    duzenleBaslik: 'Изменить публикацию',
    notEtiketi: 'Заметка',
    notYerTutucu: 'Добавить заметку',
    etiketlenenler: 'Отмечены',
    etiketiKaldirEtiketi: 'Убрать отметку {{ad}}',
    duzenleAriza: 'Не удалось обновить публикацию.',
  },
  kullanici: {
    bulunamadi: 'Профиль не найден',
    takipEt: 'Добавить в друзья',
    istekBeklemede: 'Ожидает',
    istegiGeriCek: 'Отозвать запрос',
    bagiKopar: 'Удалить из друзей',
    gelenIstekAciklama: 'Если примешь, вы будете видеть чек-ины друг друга и сможете переписываться.',
    kabulEt: 'Принять',
    reddet: 'Отклонить',
    anilar: 'Воспоминания',
    enSik: 'Чаще всего',
    aniYok: 'Воспоминаний пока нет',
    profilKapali: 'Это закрытый профиль',
    profilKapaliAciklama: 'Чтобы видеть воспоминания, нужно быть друзьями.',
    yerYok: 'Мест пока нет',
    sikayetEt: 'Пожаловаться',
    engelle: 'Заблокировать',
    engelleOnayi: 'После блокировки вы нигде не будете видеть друг друга, а все сообщения между вами удалятся навсегда. Это нельзя отменить.',
    engelleEvet: 'Да, заблокировать',
    vazgec: 'Отмена',
    geri: 'Назад',
    mesajYaz: 'Написать',
    arkadassin: 'Друзья',
    paylas: 'Поделиться профилем',
    paylasMetni: '{{ad}} в Slooin: {{kullaniciAdi}}',
  },
  profilDuzenle: {
    baslik: 'Изменить профиль',
    adEtiket: 'Полное имя',
    adYerTutucu: 'Твоё полное имя',
    adHata: 'Введи своё полное имя.',
    kullaniciAdiEtiket: 'Имя пользователя',
    biyografiEtiket: 'О себе',
    biyografiYerTutucu: 'Расскажи немного о себе',
    instagramEtiket: 'Instagram',
    instagramYerTutucu: 'твоё имя пользователя',
    instagramIpucu: 'Можно вставить и ссылку. Не проверяется; показывается в профиле как ссылка.',
    bolgeEtiket: 'Где ты живёшь',
    bolgeSecilmedi: 'Не выбрано',
    bolgeIpucu: 'Необязательно. Если выберешь, будет видно в профиле.',
    bolgeIlSec: 'Выбрать провинцию',
    bolgeIlceSec: 'Выбрать район',
    bolgeKaldir: 'Убрать регион',
    instagramHata: 'Имя пользователя Instagram состоит из букв, цифр, точек и подчёркиваний; не может начинаться или заканчиваться точкой.',
    kaydediliyor: 'Сохранение…',
    kaydedildi: 'Профиль обновлён.',
  },
  ayarlar: {
    baslik: 'Настройки',
    geri: 'Назад',
    profilGizli: 'Закрытый профиль',
    profilGizliAciklama: 'Когда включено, твои воспоминания и чек-ины видят только друзья. Имя, имя пользователя и фото остаются открытыми, чтобы тебя могли найти и отправить запрос в друзья.',
    verilerimiIndir: 'Скачать мои данные',
    verilerimiIndirHazirlaniyor: 'Подготовка…',
    verilerimiIndirHata: 'Не удалось подготовить данные. Попробуй снова.',
    gizlilikMetni: 'Политика конфиденциальности',
    bolumGorunurluk: 'Настройки приватности',
    aniGorunurlugu: 'Мои прошлые воспоминания',
    etiketOnayi: 'Спрашивать перед отметкой',
    etiketOnayiAciklama: 'Когда выключено, друзья могут отмечать тебя сразу. Когда включено, тебя сначала спросят; никто не увидит отметку, пока ты не подтвердишь.',
    aramadaGorun: 'Показывать меня в поиске',
    aramadaGorunEtiket: 'Видимость в поиске',
    bolumKisiler: 'Люди',
    engellenenler: 'Заблокированные',
    bolumHesapIslemleri: 'Аккаунт',
    dondur: 'Заморозить аккаунт',
    dondurAciklama: 'Данные не удаляются. Аккаунт автоматически активируется при следующем входе.',
    dondurEvet: 'Да, заморозить',
    vazgec: 'Отмена',
    hesabiSil: 'Удалить аккаунт',
    cikisYap: 'Выйти',
    aniHerkeseAcik: 'Все',
    aniTakipcilerim: 'Только мои подписчики',
    aniKimse: 'Никто',
    secilmedi: 'Не выбрано',
  },
  kullaniciAdiEkrani: {
    yerTutucu: 'Новое имя пользователя',
    sonrakiDegisim: 'Снова изменить можно: {{tarih}}',
  },
  aniGorunurlugu: {
    baslik: 'Мои прошлые воспоминания',
    geri: 'Назад',
    aciklama: 'Этот выбор применяется ко всем воспоминаниям, но воспоминания из скрытого чек-ина не затрагиваются и остаются приватными.',
  },
  engellenenler: {
    baslik: 'Заблокированные',
    engeliKaldir: 'Разблокировать',
    bosBaslik: 'Ты никого не блокировал(а)',
    bosAciklama: 'Если ты кого-то заблокируешь, он появится здесь, и здесь же можно это отменить.',
    geri: 'Назад',
  },
  profil: {
    yerSayisi: 'Места',
    duzenle: 'Изменить профиль',
    paylas: 'Поделиться',
    paylasilamadi: 'Не удалось открыть «Поделиться» на этом устройстве.',
    sekmeAnilar: 'Воспоминания',
    sekmeYerler: 'Чаще всего',
    sekmeFotograflar: 'Фото',
    fotografSayisi: 'Фото',
    bosFotografBaslik: 'Фото пока нет',
    bosFotografAciklama: 'Если добавлять фото при чек-ине, все они соберутся здесь.',
    bosArkadasBaslik: 'Друзей пока нет',
    kezSayisi: '{{sayi}} раз',
    bosYerBaslik: 'Ты ещё нигде не был(а)',
    bosYerAciklama: 'С каждым чек-ином здесь выстраиваются места, где ты бываешь чаще всего.',
    ayarlar: 'Настройки',
    fotografEkle: 'Добавить фото профиля',
    fotografiBuyut: 'Увеличить фото профиля',
    fotografKaldir: 'Убрать фото',
    fotografKaldirOnay: 'Убрать фото?',
    kapat: 'Закрыть',
    aniSayisi: 'Воспоминания',
    bagSayisi: 'Друзья',
    canliEtiket: 'Ты сейчас здесь',
    ayril: 'Уйти',
    canliSil: 'Удалить',
    canliSilOnay: 'Удалить этот чек-ин навсегда? В воспоминаниях он тоже не останется.',
    bosCanliBaslik: 'Сейчас ты нигде',
    bosCanliAciklama: 'Отметься там, где ты есть, и увидишь, кто там в эту самую минуту.',
    checkInYap: 'Отметиться где-нибудь',
    anilarBaslik: 'Воспоминания',
    bosAniBaslik: 'Воспоминаний пока нет',
    bosAniAciklama: 'Твои чек-ины остаются здесь как воспоминания.',
    profilYok: 'Профиль ещё не готов',
    profilYokAciklama: 'Задай имя и имя пользователя и продолжай отсюда.',
    profilOlustur: 'Создать профиль',
  },
  dogrula: {
    geri: 'Назад',
    baslik: 'Подтверди почту',
    aciklama: 'Мы отправили 6-значный код на {{eposta}}.',
    kodEtiketi: 'Код подтверждения',
    gonder: 'Подтвердить',
    gonderiliyor: 'Проверка…',
    kodGelmedi: 'Код не пришёл?',
    spamNotu: 'Если его нет во входящих, проверь и папку «Спам».',
    tekrarGonder: 'Отправить снова',
    tekrarBekle: 'Отправить снова можно через {{saniye}} с',
    tekrarGonderildi: 'Новый код отправлен.',
    hakKalmadi: 'Для этого адреса запрошено слишком много кодов. Попробуй снова через час.',
    hataEksik: 'Введи код целиком.',
    zatenKayitliBaslik: 'С этим адресом уже есть аккаунт',
    zatenKayitliAciklama: 'Аккаунт с {{eposta}} уже создан. Можешь войти по паролю.',
    girisYap: 'Войти',
    baskaNumara: 'Продолжить с другим адресом',
  },
  altGezinme: {
    anaSayfa: 'Главная',
    bildirimler: 'Уведомления',
    mesajlar: 'Сообщения',
    profil: 'Профиль',
  },
  arkadasSecici: {
    baslik: 'Отметь друзей',
    bos: 'Друзей пока нет. Когда ты отправишь запрос в друзья и его примут, они появятся здесь, и ты сможешь отмечать их в чек-инах.',
    tamamSayili: 'Готово ({{sayi}})',
  },
  harita: {
    cevre: 'Места вокруг тебя',
    kisiBurada: '{{ad}}, здесь {{sayi}} чел.',
    buMekan: 'Это место, {{durum}}',
    buradasin: 'Ты здесь',
  },
  sikayet: {
    baslik: 'Пожаловаться',
    sebepSec: 'Выбери причину',
    alindi: 'Жалоба получена',
    tesekkur: 'Спасибо, что сообщил(а).',
    mesajBaglami: 'При проверке модерации открываются и соседние сообщения.',
    aciklamaYerTutucu: 'Хочешь что-то добавить?',
    sebepler: {
      taciz: 'Домогательства или травля',
      uygunsuz_icerik: 'Неприемлемый контент',
      sahte_hesap: 'Поддельный аккаунт',
      spam: 'Спам или реклама',
      diger: 'Другое',
    },
  },
  hesapDurumu: {
    askida: 'Аккаунт приостановлен',
    yasakli: 'Аккаунт закрыт навсегда',
    sebep: 'Причина: {{sebep}}',
    bitis: 'До: {{tarih}}',
    ipucu: 'В это время твой профиль не виден другим, и ты не можешь публиковать новое. Данные не удалены.',
    yenile: 'Обновить',
    cikisYapilamadi: 'Не удалось выйти',
  },
  checkIn: {
    baslik: 'Новый чек-ин',
    notYerTutucu: 'Добавь заметку (необязательно)',
    ilkUyariBaslik: 'Чем делится этот чек-ин?',
    ilkUyariMetin: 'Когда ты отмечаешься, место, где ты находишься, и заметка (если есть) становятся видны друзьям. Он закрывается сам, когда чек-ин истекает или как только ты нажмёшь «Я ушёл». Если хочешь, можешь сделать этот чек-ин скрытым и оставить только в своём профиле.',
    anladim: 'Понятно',
    gizliYap: 'Сделать скрытым',
    arkadasEkle: 'Добавить друзей (необязательно)',
    arkadasEkleSecili: 'Добавить друзей (выбрано: {{sayi}})',
    etiketiKaldir: 'Убрать отметку {{ad}}',
    fotografEkle: 'Добавить фото (необязательно)',
    fotografDegistir: 'Изменить фото',
    fotografCek: 'Сделать фото',
    galeridenSec: 'Выбрать из галереи',
    kameraIzni: 'Чтобы сделать фото, нужен доступ к камере.',
    fotografYuklenemedi: 'Не удалось загрузить фото; чек-ин сделан с заметкой',
    etiketlenemedi: 'Чек-ин сделан, но друзей отметить не удалось.',
    gonder: 'Отметиться',
    gonderiliyor: 'Отмечаемся...',
  },
  mekanDuzenle: {
    baslik: 'Исправить данные',
    aciklama: 'Что-то не так? Твоё исправление уйдёт модератору; после одобрения оно обновится для всех.',
    gonderildiBaslik: 'Запрос отправлен',
    gonderildiMetin: 'Данные места обновятся, когда модератор проверит и одобрит.',
    bekleyenBaslik: 'У тебя есть ожидающий запрос',
    bekleyenMetin: 'Запрос по этому месту ещё рассматривается. Когда он будет решён, ты сможешь отправить новое исправление.',
    adEtiket: 'Название места',
    adYerTutucu: 'Название места',
    mahalle: 'Район (махалле)',
    mahalleYerTutucu: 'напр. Alaaddinbey',
    adres: 'Адрес',
    adresYerTutucu: 'Улица, номер',
    il: 'Провинция',
    ilYerTutucu: 'Bursa',
    ilce: 'Район',
    ilceYerTutucu: 'Nilüfer',
    tur: 'Тип',
    kapakFotografi: 'Обложка',
    fotografiKaldir: 'Убрать фото',
    fotografEkle: 'Добавить фото',
    fotografSecilemedi: 'Не удалось выбрать фото.',
    galeriIzni: 'Чтобы выбрать из галереи, нужен доступ к фото.',
    oturumYok: 'Сессия не найдена',
    zatenKapali: 'Это место уже отмечено как закрытое навсегда.',
    kapaliBaslik: 'Это место закрылось навсегда',
    kapaliAciklama: 'Если одобрят, место уберут из списков и поиска. Сделанные здесь чек-ины не удаляются.',
    onceDegistir: 'Сначала что-нибудь измени.',
    talebiGonder: 'Отправить запрос',
  },
  mekanEkle: {
    baslik: 'Добавить новое место',
    adYerTutucu: 'Название места',
    turuSec: 'Выбери тип',
    adresYerTutucu: 'Адрес (необязательно)',
    adresSoru: 'Этот адрес верный?',
    adresAciklama: 'Найден по твоему местоположению. Если неверный, отредактируй поле выше.',
    dogru: 'Верный',
    benzerBaslik: 'Может, ты имел(а) в виду одно из этих?',
    konumAlinamadi: 'Не удалось определить местоположение, попробуй снова',
    adVeTurGerekli: 'Нужны название и тип места',
    ekle: 'Добавить',
    ekleniyor: 'Добавление...',
  },
  turGruplari: {
    'Yeme içme': 'Еда и напитки',
    Gece: 'Ночная жизнь',
    'Açık alan': 'На открытом воздухе',
    Kültür: 'Культура',
    Spor: 'Спорт',
    Alışveriş: 'Покупки',
    Diğer: 'Другое',
  },
  turler: {
    Kafe: 'Кафе',
    Kahveci: 'Кофейня',
    'Çay evi': 'Чайная',
    Restoran: 'Ресторан',
    Lokanta: 'Столовая',
    'Türk mutfağı': 'Турецкая кухня',
    Kebapçı: 'Кебабная',
    'Balık restoranı': 'Рыбный ресторан',
    Ocakbaşı: 'Гриль-бар',
    'Kahvaltı salonu': 'Завтраки',
    Fırın: 'Пекарня',
    'Fast food': 'Фастфуд',
    Burgerci: 'Бургерная',
    Pizzacı: 'Пиццерия',
    Tatlıcı: 'Кондитерская',
    Dondurmacı: 'Мороженое',
    Bar: 'Бар',
    Pub: 'Паб',
    'Gece kulübü': 'Ночной клуб',
    Meyhane: 'Таверна',
    'Nargile kafe': 'Кальянная',
    'Kokteyl barı': 'Коктейль-бар',
    Park: 'Парк',
    'Halk bahçesi': 'Городской сад',
    'Doğal alan': 'Природная зона',
    Plaj: 'Пляж',
    Meydan: 'Площадь',
    'Kamp alanı': 'Кемпинг',
    Göl: 'Озеро',
    Müze: 'Музей',
    Sinema: 'Кинотеатр',
    Tiyatro: 'Театр',
    'Sanat galerisi': 'Художественная галерея',
    Kütüphane: 'Библиотека',
    'Tarihi yer': 'Историческое место',
    'Konser salonu': 'Концертный зал',
    'Kültür merkezi': 'Культурный центр',
    'Spor salonu': 'Спортзал',
    Stadyum: 'Стадион',
    'Yüzme havuzu': 'Бассейн',
    'Halı saha': 'Футбольное поле',
    AVM: 'Торговый центр',
    Market: 'Супермаркет',
    Bakkal: 'Продуктовый магазин',
    'Giyim mağazası': 'Магазин одежды',
    Kitapçı: 'Книжный',
    Kuyumcu: 'Ювелирный',
    Otel: 'Отель',
    Eczane: 'Аптека',
    Hastane: 'Больница',
    Banka: 'Банк',
    Kuaför: 'Парикмахерская',
    'Güzellik salonu': 'Салон красоты',
    Üniversite: 'Университет',
    'Canlı müzik': 'Живая музыка',
  },
  kesfet: {
    baslik: 'Чек-ин',
    harita: 'Карта',
    liste: 'Список',
    turSuzgeci: 'Фильтр по типу',
    turFiltresi: 'Фильтр по типу',
    turBulunamadi: 'Вокруг тебя нет типов для показа.',
    filtreyiKaldir: 'Убрать фильтр',
    tumunuSec: 'Выбрать все',
    temizle: 'Очистить',
    kaydet: 'Сохранить',
    kaydetSayili: 'Сохранить ({{sayi}})',
    tumu: 'Все',
    sakin: 'Тихо',
    yogun: 'Людно',
    populer: 'Популярно',
    yakinindakiMekanlar: 'Места рядом с тобой',
    sonuclar: 'Результаты',
    kisiBurada: 'здесь {{sayi}} чел.',
    checkIn: 'Чек-ин',
    konumuGor: 'Показать место',
    checkInYap: 'Отметиться здесь',
    mekanAra: 'Поиск мест',
    kisi: '{{sayi}} чел.',
    taraniyor: 'Осматриваемся вокруг…',
    cevreGorunmuyor: 'Мы не видим, что вокруг тебя',
    konumIzniAciklama: 'Чтобы показать места рядом, нужен доступ к местоположению. Включи его в настройках браузера и попробуй снова.',
    konumuAc: 'Открыть {{ad}}',
    konumuGorEtiketi: 'Показать {{ad}}',
    checkInEtiketi: 'Отметиться в {{ad}}',
    filtreyiKaldirEtiketi: 'Убрать фильтр {{tur}}',
    kisiBuradaEtiket: 'чел. здесь',
    suAnBuradasin: 'Ты сейчас здесь',
    ayrildim: 'Я ушёл',
    araniyor: 'Поиск…',
    aramaBulunamadi: 'По запросу «{{arama}}» мест не найдено. Попробуй изменить написание.',
    sonucSayisi: 'Результатов: {{sayi}}',
    bosArama: 'В этой провинции по запросу «{{arama}}» ничего нет.',
    bosFiltre: 'С этим фильтром в радиусе 500 м мест нет.',
    bosCevre: 'Рядом с тобой мест нет.',
    mekanEkle: 'Не нашёл место? Добавь его',
    atif: 'Данные о местах: Foursquare · Район: © участники OpenStreetMap',
  },
  checkInHaritasi: {
    geri: 'Назад',
    haritaAcikla: 'Нажми на карту, чтобы построить маршрут',
    haritadaAc: 'Маршрут',
    secimBaslik: 'Какую карту открыть?',
    appleHaritalar: 'Apple Карты',
    googleHaritalar: 'Google Карты',
    vazgec: 'Отмена',
  },
  mekanSayfasi: {
    fotografEtiketi: 'Фото {{ad}}',
    menu: 'Действия',
    yolTarifi: 'Маршрут',
    buradaCheckIn: 'Отметиться здесь',
    yaklas: 'Подойди ближе, чтобы отметиться · {{mesafe}}',
    buradasinAyril: 'Ты здесь · Уйти',
    kapandi: 'Это место закрылось навсегда',
    kapandiAciklama: 'Здесь больше нельзя отметиться, и место не показывается в списках. Твои прошлые воспоминания остаются.',
    kisiBurada: 'чел. здесь',
    bugun: 'Сегодня',
    haritadaGoster: 'Показать место на карте',
    checkInSayisi: '{{sayi}} чек-инов',
    kisiSayisi: '{{sayi}} чел.',
    ilcedekiYerler: 'мест в {{ilce}}',
    siralamaYok: 'Нет рейтинга',
    suAnBurada: 'Сейчас здесь',
    diger: 'Ещё',
    biri: 'Кто-то',
    suAn: 'сейчас',
    liderlik: 'Лидеры',
    sonCheckInler: 'Недавние',
    liderlikBos: 'Здесь пока нет чек-инов для показа.',
    sonBos: 'Здесь пока нет чек-инов для показа.',
    fotograflar: 'Фото',
    fotografBos: 'Здесь пока нет фото.',
    fotografAc: 'Увеличить фото',
    dahaFazlaFotograf: 'Ещё фото',
    puan: 'Оценка',
    puanlamaSayisi: '{{sayi}} оценок',
    puanYok: 'Оценок пока нет',
    puanAzOy: 'Для балла нужно не меньше 3 оценок',
    puanKotu: 'Плохо',
    puanIyi: 'Хорошо',
    puanHarika: 'Отлично',
    puanSoru: 'Как тебе это место?',
    puanSart: 'Сначала отметься здесь, чтобы оценить.',
    puanGonder: 'Отправить',
    puanGuncelle: 'Изменить оценку',
    puanGonderiliyor: 'Отправка…',
    puanTesekkur: 'Оценка сохранена.',
  },
  giris: {
    epostaYerTutucu: 'Электронная почта',
    sifreYerTutucu: 'Пароль',
    gonder: 'Войти',
    gonderiliyor: 'Вход…',
    kayitOl: 'Создать новый аккаунт',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataBos: 'Введи электронную почту и пароль.',
    sifremiUnuttum: 'Забыл(а) пароль?',
  },
  sifreSifirla: {
    geri: 'Назад',
    baslik: 'Сбросить пароль',
    aciklama: 'Введи почту аккаунта, и мы отправим 6-значный код.',
    epostaYerTutucu: 'Электронная почта',
    kodGonder: 'Отправить код',
    gonderiliyor: 'Отправка…',
    hataEposta: 'Введи действительный адрес электронной почты.',
    hataHesapYok: 'Аккаунт с этой почтой не найден.',
    kodBaslik: 'Введи код',
    kodAciklama: 'Мы отправили 6-значный код на {{eposta}}.',
    kodEtiketi: 'Код подтверждения',
    dogrula: 'Подтвердить',
    dogrulaniyor: 'Проверка…',
    hataEksik: 'Введи код целиком.',
    kodGelmedi: 'Код не пришёл?',
    spamNotu: 'Если его нет во входящих, проверь и папку «Спам».',
    tekrarGonder: 'Отправить снова',
    tekrarBekle: 'Отправить снова можно через {{saniye}} с',
    tekrarGonderildi: 'Новый код отправлен.',
    hakKalmadi: 'Для этого адреса запрошено слишком много кодов. Попробуй снова через час.',
    yeniBaslik: 'Задай новый пароль',
    yeniAciklama: 'Код подтверждён. Теперь выбери новый пароль.',
    sifreYerTutucu: 'Новый пароль (не меньше {{adet}} символов)',
    sifreTekrarYerTutucu: 'Новый пароль (ещё раз)',
    kaydet: 'Сохранить пароль',
    kaydediliyor: 'Сохранение…',
    hataSifreKisa: 'Пароль должен содержать не меньше {{adet}} символов.',
    hataSifreEslesmiyor: 'Пароли не совпадают.',
  },
  hatalar: {
    genel: 'Что-то пошло не так. Попробуй чуть позже.',
    kullaniciAdi30Gun: 'Имя пользователя можно менять раз в 30 дней. Осталось {{gun}} дн.',
    vt: {
      aski_bitisi_gelecekte_olmali: 'Окончание блокировки должно быть в будущем.',
      bir_moderatore_islem_uygulanamaz: 'К модератору нельзя применить действие.',
      bu_kisiye_su_an_mesaj_gonderemezsin: 'Сейчас ты не можешь написать этому человеку.',
      bu_kullanici_adi_alinmis: 'Это имя пользователя занято, попробуй другое.',
      bu_kullanici_bulunamadi: 'Пользователь не найден.',
      bu_fotograf_sana_ait_degil: 'Это фото не твоё.',
      bu_il_listemizde_yok: 'Этой провинции нет в нашем списке.',
      bu_mekan_bulunamadi: 'Место не найдено.',
      bu_mekan_icin_bekleyen_bir_talebin_zaten_var: 'Запрос по этому месту ещё рассматривается.',
      bu_mekan_kalici_olarak_kapandi: 'Это место закрылось навсегда.',
      bu_mekan_zaten_kapali_olarak_isaretli: 'Это место уже отмечено как закрытое.',
      bu_tur_listemizde_yok: 'Этого типа нет в нашем списке.',
      en_az_bir_alan_doldurulmali: 'Нужно изменить хотя бы одно поле.',
      gunluk_duzenleme_talebi_sinirina_ulastin: 'Достигнут дневной лимит исправлений (5). Попробуй завтра.',
      hesabin_su_an_bu_islemi_yapamaz: 'Твой аккаунт сейчас не может это сделать.',
      bu_paylasim_bulunamadi: 'Публикация не найдена.',
      not_en_fazla_500_karakter_olabilir: 'Заметка может содержать не больше 500 символов.',
      bu_mesaji_sikayet_edemezsin: 'На это сообщение нельзя пожаловаться.',
      bugunluk_istek_sinirina_ulastin: 'Достигнут лимит запросов на сегодня.',
      check_in_bulunamadi: 'Чек-ин не найден.',
      cok_fazla_kimlik: 'Отправлено слишком много идентификаторов.',
      en_az_2_karakter_gerekli: 'Введи не меньше 2 символов.',
      gecersiz_bulunurluk_degeri: 'Недопустимое значение доступности.',
      gecersiz_gorunurluk_degeri: 'Недопустимое значение видимости.',
      gecersiz_platform: 'Недопустимая платформа.',
      gecersiz_sikayet_durumu: 'Недопустимый статус жалобы.',
      gecersiz_sikayet_hedefi: 'Недопустимая цель жалобы.',
      gerekce_belirtilmeli: 'Нужно указать причину.',
      geri_cekilecek_istek_bulunamadi: 'Запрос для отзыва не найден.',
      gunluk_mekan_ekleme_limitine_ulastin_5: 'Достигнут дневной лимит добавления мест (5). Попробуй завтра.',
      hesabin_su_anda_kullanilamiyor: 'Твой аккаунт сейчас недоступен.',
      hesabin_zaten_kullanilamaz_durumda: 'Твой аккаунт уже недоступен.',
      istegin_zaten_gonderilmis: 'Запрос уже отправлен.',
      jeton_bos_olamaz: 'Токен уведомлений не может быть пустым.',
      jeton_cok_uzun: 'Токен уведомлений слишком длинный.',
      kendi_mesajini_sikayet_edemezsin: 'Нельзя пожаловаться на своё сообщение.',
      kendine_islem_uygulayamazsin: 'Нельзя применить действие к себе.',
      kendine_istek_gonderemezsin: 'Нельзя отправить запрос самому себе.',
      kendine_mesaj_gonderemezsin: 'Нельзя написать самому себе.',
      kendini_engelleyemezsin: 'Нельзя заблокировать самого себя.',
      kendini_sikayet_edemezsin: 'Нельзя пожаловаться на самого себя.',
      kimlik_dogrulamasi_gerekli: 'Для этого нужно войти.',
      konusma_bulunamadi: 'Разговор не найден.',
      kullanici_adi_kurallara_uymuyor: 'Имя пользователя не соответствует правилам.',
      kullanici_belirtilmeli: 'Нужно указать пользователя.',
      mekan_bulunamadi: 'Место не найдено.',
      gecersiz_puan: 'Недопустимая оценка.',
      puan_vermek_icin_once_burada_check_in_yapmalisin: 'Сначала отметься здесь, чтобы оценить.',
      mekana_cok_uzaksin_1_km_icinde_olmalisin: 'Ты слишком далеко от места. Чтобы отметиться, нужно быть в пределах примерно 1 км.',
      mekana_yakin_olmalisin_200_m_icinde: 'Чтобы добавить место, нужно быть в пределах примерно 200 м от него.',
      mesaj_bos_olamaz: 'Сообщение не может быть пустым.',
      mesaj_bu_konusmada_bulunamadi: 'Сообщение не найдено в этом разговоре.',
      mesaj_cok_uzun: 'Сообщение слишком длинное.',
      profil_bulunamadi: 'Профиль не найден.',
      sikayet_bulunamadi: 'Жалоба не найдена.',
      sikayet_sebebi_belirtilmeli: 'Нужно указать причину жалобы.',
      yanitlanacak_istek_bulunamadi: 'Запрос для ответа не найден.',
      yetkisiz: 'У тебя нет прав на это.',
      zaten_bu_kullanici_adini_kullaniyorsun: 'Ты уже используешь это имя пользователя.',
    },
    kod: {
      '23505': 'Такая запись уже есть.',
      '57014': 'Операция заняла слишком много времени. Попробуй снова.',
      otp_expired: 'Код недействителен или истёк. Запроси новый.',
      user_already_exists: 'С этим адресом уже есть аккаунт. Можешь войти.',
      invalid_credentials: 'Неверная почта или пароль.',
      over_request_rate_limit: 'Слишком много попыток. Подожди немного и попробуй снова.',
      over_sms_send_rate_limit: 'Запрошено слишком много кодов. Подожди немного и попробуй снова.',
      weak_password: 'Пароль слишком слабый. Выбери надёжнее.',
      same_password: 'Новый пароль должен отличаться от старого.',
      signup_disabled: 'Новые регистрации сейчас не принимаются.',
      phone_provider_disabled: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
    },
    metin: {
      sms_saglayici: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
      sms_saglayici2: 'На этот номер сейчас нельзя отправить код. Попробуй позже.',
      kod_gecersiz: 'Код недействителен или истёк. Запроси новый.',
      zaten_kayitli: 'С этим адресом уже есть аккаунт. Можешь войти.',
      giris_hatali: 'Неверная почта или пароль.',
      cok_sik: 'Слишком много попыток. Подожди немного и попробуй снова.',
      sifre_kisa: 'Пароль слишком короткий.',
      sifre_ayni: 'Новый пароль должен отличаться от старого.',
      kayit_kapali: 'Новые регистрации сейчас не принимаются.',
      ag_yok: 'Нет доступа к интернету. Проверь подключение и попробуй снова.',
      oturum_dustu: 'Сессия истекла. Войди снова.',
    },
  },
} as const
