"""Foursquare kategorisi -> Slooin turu (kullaniciya gorunen Turkce ad).

Foursquare'in 1.279 kategorisi alti seviyeli bir agac ve YALNIZCA
Ingilizce. Buradaki sozluk agacin en ozgul dugumunden yukari dogru
bakar: "Dining and Drinking > Restaurant > Turkish Restaurant > Kofte
Place" icin once tam yol, sonra "... > Turkish Restaurant", sonra
"... > Restaurant", en sonda "Dining and Drinking" aranir. Boylece her
kategori bir Turkce ada duser; hicbir kayit sozluk yuzunden disarida
kalmaz ve ekranda hicbir zaman ham Ingilizce kategori gorunmez.

TUR ADLARI OVERTURE SOZLUGUYLE AYNI (araclar/kategori-eslemesi.py):
kesfetteki sosyal-tur suzgeci (`lib/mekan.ts` SOSYAL_TURLER) ve
testler bu adlara bagli. Yeni ad eklerken o listeye de bakilir.

Kapsam disi (hic yuklenmez, bkz. araclar/fsq-indir.py):
apartman/konut, toplu konut, ofis, fabrika, yol, etkinlik; kapali ve
bayrakli kayitlar.
"""

# En ozgul dugumden ust dugume dogru aranir. Anahtar: etiketin sonundan
# bir parca ("Kofte Place") ya da tam yol. Deger: Turkce tur.
ESLEME: dict[str, str] = {
    # ---------------- Yeme icme ----------------
    'Dining and Drinking': 'Yeme içme',
    'Restaurant': 'Restoran',
    'Turkish Restaurant': 'Türk mutfağı',
    'Kofte Place': 'Köfteci',
    'Kokoreç Restaurant': 'Kokoreççi',
    'Kumpir Restaurant': 'Kumpirci',
    'Kumru Restaurant': 'Kumrucu',
    'Manti Place': 'Mantıcı',
    'Meyhane': 'Meyhane',
    'Pide Place': 'Pideci',
    'Pilavcı': 'Pilavcı',
    'Söğüş Place': 'Söğüşçü',
    'Tantuni Restaurant': 'Tantunici',
    'Turkish Coffeehouse': 'Kahvehane',
    'Turkish Home Cooking Restaurant': 'Ev yemekleri',
    'Cigkofte Place': 'Çiğköfteci',
    'Çöp Şiş Place': 'Ocakbaşı',
    'Kebab Restaurant': 'Kebapçı',
    'Doner Restaurant': 'Dönerci',
    'Gozleme Place': 'Gözlemeci',
    'Cafeteria': 'Lokanta',
    'Diner': 'Lokanta',
    'Comfort Food Restaurant': 'Lokanta',
    'Buffet': 'Lokanta',
    'Soup Spot': 'Çorbacı',
    'Steakhouse': 'Steakhouse',
    'BBQ Joint': 'Ocakbaşı',
    'Fast Food Restaurant': 'Fast food',
    'Burger Joint': 'Burgerci',
    'Fried Chicken Joint': 'Fast food',
    'Wings Joint': 'Fast food',
    'Hot Dog Joint': 'Fast food',
    'Sandwich Spot': 'Fast food',
    'Fish and Chips Shop': 'Balık restoranı',
    'Seafood Restaurant': 'Balık restoranı',
    'Pizzeria': 'Pizzacı',
    'Italian Restaurant': 'İtalyan restoranı',
    'Chinese Restaurant': 'Çin restoranı',
    'Asian Restaurant': 'Asya mutfağı',
    'Japanese Restaurant': 'Japon restoranı',
    'Sushi Restaurant': 'Suşi restoranı',
    'Mexican Restaurant': 'Meksika restoranı',
    'Middle Eastern Restaurant': 'Restoran',
    'Mediterranean Restaurant': 'Restoran',
    'Greek Restaurant': 'Restoran',
    'American Restaurant': 'Restoran',
    'French Restaurant': 'Restoran',
    'Vegan and Vegetarian Restaurant': 'Vegan restoran',
    'Salad Restaurant': 'Restoran',
    'Halal Restaurant': 'Restoran',
    'Deli': 'Şarküteri',
    'Bistro': 'Restoran',
    'Theme Restaurant': 'Restoran',
    'Breakfast Spot': 'Kahvaltı salonu',
    'Cafe, Coffee, and Tea House': 'Kafe',
    'Café': 'Kafe',
    'Coffee Shop': 'Kahveci',
    'Tea Room': 'Çay evi',
    'Bar': 'Bar',
    'Pub': 'Pub',
    'Lounge': 'Bar',
    'Beer Garden': 'Bira bahçesi',
    'Beer Bar': 'Bira evi',
    'Cocktail Bar': 'Kokteyl barı',
    'Hookah Bar': 'Nargile kafe',
    'Hotel Bar': 'Bar',
    'Dive Bar': 'Bar',
    'Sports Bar': 'Spor barı',
    'Speakeasy': 'Bar',
    'Karaoke Bar': 'Karaoke',
    'Whisky Bar': 'Bar',
    'Wine Bar': 'Şarap evi',
    'Brewery': 'Bira fabrikası',
    'Winery': 'Şaraphane',
    'Vineyard': 'Şaraphane',
    'Distillery': 'Bira fabrikası',
    'Dessert Shop': 'Tatlıcı',
    'Ice Cream Parlor': 'Dondurmacı',
    'Pastry Shop': 'Pastane',
    'Cupcake Shop': 'Pastane',
    'Pie Shop': 'Pastane',
    'Bakery': 'Fırın',
    'Bagel Shop': 'Simitçi',
    'Donut Shop': 'Tatlıcı',
    'Creperie': 'Tatlıcı',
    'Food Court': 'Yemek katı',
    'Snack Place': 'Büfe',
    'Food Stand': 'Büfe',
    'Food Truck': 'Büfe',
    'Juice Bar': 'Meyve suyu barı',
    'Smoothie Shop': 'Meyve suyu barı',
    'Night Market': 'Semt pazarı',

    # ---------------- Gece hayati ----------------
    'Nightlife Spot': 'Bar',
    'Night Club': 'Gece kulübü',
    'Salsa Club': 'Gece kulübü',
    'Country Dance Club': 'Gece kulübü',
    'Strip Club': 'Gece kulübü',

    # ---------------- Sanat ve eglence ----------------
    'Arts and Entertainment': 'Sanat ve eğlence',
    'Performing Arts Venue': 'Sahne sanatları',
    'Music Venue': 'Canlı müzik',
    'Concert Hall': 'Konser salonu',
    'Theater': 'Tiyatro',
    'Amphitheater': 'Sahne sanatları',
    'Movie Theater': 'Sinema',
    'Indie Movie Theater': 'Sinema',
    'Drive-in Theater': 'Sinema',
    'Art Gallery': 'Sanat galerisi',
    'Museum': 'Müze',
    'History Museum': 'Müze',
    'Art Museum': 'Müze',
    'Arcade': 'Oyun salonu',
    'Gaming Cafe': 'Oyun salonu',
    'VR Cafe': 'Oyun salonu',
    'Internet Cafe': 'İnternet kafe',
    'Pool Hall': 'Bilardo salonu',
    'Bowling Alley': 'Bowling salonu',
    'Amusement Park': 'Lunapark',
    'Water Park': 'Aquapark',
    'Go Kart Track': 'Go-kart pisti',
    'Laser Tag Center': 'Oyun salonu',
    'Escape Room': 'Oyun salonu',
    'Mini Golf Course': 'Golf sahası',
    'Stadium': 'Stadyum',
    'Aquarium': 'Akvaryum',
    'Zoo': 'Hayvanat bahçesi',
    'Public Art': 'Anıt',
    'Exhibit': 'Sanat galerisi',
    'Fair': 'Lunapark',
    'Carnival': 'Lunapark',
    'Circus': 'Sanat ve eğlence',
    'Comedy Club': 'Sahne sanatları',
    'Casino': 'Sanat ve eğlence',
    'Planetarium': 'Müze',
    'Roller Rink': 'Kaykay parkı',
    'Disc Golf': 'Golf sahası',
    'Dance Hall': 'Gece kulübü',
    'Party Center': 'Düğün salonu',
    'Psychic and Astrologer': 'Sanat ve eğlence',
    'Karaoke Box': 'Karaoke',

    # ---------------- Acik alan ve yerler ----------------
    'Landmarks and Outdoors': 'Doğal alan',
    'Park': 'Park',
    'Playground': 'Park',
    'National Park': 'Milli park',
    'Dog Park': 'Park',
    'Garden': 'Halk bahçesi',
    'Botanical Garden': 'Botanik bahçe',
    'Sculpture Garden': 'Halk bahçesi',
    'Plaza': 'Meydan',
    'Pedestrian Plaza': 'Meydan',
    'Scenic Lookout': 'Seyir terası',
    'Roof Deck': 'Seyir terası',
    'Beach': 'Plaj',
    'Nudist Beach': 'Plaj',
    'Bathing Area': 'Plaj',
    'Waterfront': 'Sahil',
    'Harbor or Marina': 'Marina',
    'Bay': 'Sahil',
    'Lake': 'Göl',
    'Pond': 'Göl',
    'Reservoir': 'Baraj',
    'Dam': 'Baraj',
    'River': 'Nehir',
    'Canal': 'Nehir',
    'Waterfall': 'Şelale',
    'Hot Spring': 'Kaplıca',
    'Mountain': 'Dağ',
    'Hill': 'Dağ',
    'Volcano': 'Dağ',
    'Cave': 'Doğal alan',
    'Forest': 'Orman',
    'Nature Preserve': 'Tabiat parkı',
    'Hiking Trail': 'Yürüyüş parkuru',
    'Nature Trail': 'Yürüyüş parkuru',
    'Bike Trail': 'Yürüyüş parkuru',
    'Campground': 'Kamp alanı',
    'Picnic Shelter': 'Piknik alanı',
    'Farm': 'Çiftlik',
    'Orchard': 'Çiftlik',
    'Stable': 'Çiftlik',
    'Field': 'Doğal alan',
    'Historic and Protected Site': 'Tarihi yer',
    'Archaeological Site': 'Ören yeri',
    'Ruin': 'Ören yeri',
    'Castle': 'Kale',
    'Fort': 'Kale',
    'Palace': 'Tarihi yer',
    'Monument': 'Anıt',
    'Memorial Site': 'Anıt',
    'Fountain': 'Meydan',
    'Bridge': 'Köprü',
    'Tower': 'Tarihi yer',
    'Lighthouse': 'Tarihi yer',
    'Windmill': 'Tarihi yer',
    'Watermill': 'Tarihi yer',
    'Structure': 'Yapı',
    'Landmark Building': 'Tarihi yer',
    'Island': 'Doğal alan',
    'Well': 'Doğal alan',
    'Tree': 'Doğal alan',
    'Rock Climbing Spot': 'Doğal alan',
    'Dive Spot': 'Plaj',
    'Surf Spot': 'Plaj',
    'Tunnel': 'Yapı',
    'Guildhall': 'Tarihi yer',
    'Mountain Hut': 'Dinlenme tesisi',
    'Boardwalk': 'Sahil',
    'Pass': 'Doğal alan',
    'Valley': 'Doğal alan',
    'Wetland': 'Doğal alan',
    'Desert': 'Doğal alan',
    'Cape': 'Sahil',
    'Fjord': 'Sahil',
    'Quarry': 'yer-degil',
    'Natural Gas Field': 'yer-degil',
    'Boat Launch': 'İskele',
    'Canal Lock': 'Yapı',
    # Yer adlari (mahalle, koy, sehir): check-in yapilacak bir mekan degil.
    'States and Municipalities': 'yer-degil',
    'Region': 'yer-degil',

    # ---------------- Spor ----------------
    'Sports and Recreation': 'Spor ve rekreasyon',
    'Gym and Studio': 'Spor salonu',
    'Gym': 'Spor salonu',
    'Gym Pool': 'Yüzme havuzu',
    'Pilates Studio': 'Pilates stüdyosu',
    'Yoga Studio': 'Yoga stüdyosu',
    'Dance Studio': 'Dans stüdyosu',
    'Boxing Gym': 'Dövüş sporları salonu',
    'Martial Arts Dojo': 'Dövüş sporları salonu',
    'Personal Trainer': 'Spor salonu',
    'Soccer': 'Halı saha',
    'Soccer Field': 'Halı saha',
    'Athletic Field': 'Spor sahası',
    'Basketball': 'Basketbol sahası',
    'Basketball Court': 'Basketbol sahası',
    'Volleyball Court': 'Voleybol sahası',
    'Racquet Sports': 'Tenis kortu',
    'Tennis': 'Tenis kortu',
    'Water Sports': 'Yüzme havuzu',
    'Swimming': 'Yüzme havuzu',
    'Swimming Pool': 'Yüzme havuzu',
    'Recreation Center': 'Spor kulübü',
    'Sports Club': 'Spor kulübü',
    'Snow Sports': 'Kayak merkezi',
    'Ski Resort and Area': 'Kayak merkezi',
    'Running and Track': 'Spor sahası',
    'Track': 'Spor sahası',
    'Race Track': 'Yarış pisti',
    'Golf': 'Golf sahası',
    'Skating': 'Kaykay parkı',
    'Fishing Area': 'Doğal alan',
    'Gun Range': 'Atış poligonu',
    'Paintball Field': 'Paintball sahası',
    'Indoor Play Area': 'Oyun alanı',
    'Gymnastics': 'Spor salonu',
    'Skydiving Center': 'Spor ve rekreasyon',
    'Equestrian Facility': 'Binicilik tesisi',
    'Sauna': 'Spa',
    'Hunting Area': 'Doğal alan',
    'Baseball': 'Spor sahası',
    'Rugby': 'Spor sahası',
    'Football': 'Spor sahası',
    'Hockey': 'Spor sahası',
    'Cricket Ground': 'Spor sahası',
    'Bowling Green': 'Spor sahası',
    'Curling Ice': 'Spor sahası',

    # ---------------- Seyahat ve ulasim ----------------
    'Travel and Transportation': 'Ulaşım noktası',
    'Lodging': 'Konaklama',
    'Hotel': 'Otel',
    'Bed and Breakfast': 'Pansiyon',
    'Boarding House': 'Pansiyon',
    'Inn': 'Pansiyon',
    'Hostel': 'Hostel',
    'Motel': 'Motel',
    'Resort': 'Tatil köyü',
    'Transport Hub': 'Ulaşım noktası',
    'Bus Stop': 'Otobüs durağı',
    'Bus Station': 'Otogar',
    'Metro Station': 'Metro istasyonu',
    'Tram Station': 'Tramvay durağı',
    'Train Station': 'Tren istasyonu',
    'Airport': 'Havalimanı',
    'Heliport': 'Havalimanı',
    'Taxi Stand': 'Taksi durağı',
    'Rental Car Location': 'Araç kiralama',
    'Transportation Service': 'Ulaşım noktası',
    'Parking': 'Otopark',
    'Fuel Station': 'Benzin istasyonu',
    'Electric Vehicle Charging Station': 'Şarj istasyonu',
    'Rest Area': 'Dinlenme tesisi',
    'Travel Agency': 'Seyahat acentesi',
    'Tourist Information and Service': 'Turizm danışma',
    'Boat or Ferry': 'İskele',
    'Pier': 'İskele',
    'Port': 'Liman',
    'Cruise': 'İskele',
    'Cable Car': 'Teleferik',
    'Funicular': 'Teleferik',
    'Bike Rental': 'Bisiklet kiralama',
    'Boat Rental': 'Marina',
    'Travel Lounge': 'Ulaşım noktası',
    'RV Park': 'Kamp alanı',
    'Border Crossing': 'Sınır kapısı',
    'Toll Plaza': 'yer-degil',
    'Toll Booth': 'yer-degil',
    'Moving Target': 'yer-degil',
    'Platform': 'Ulaşım noktası',
    'Baggage Locker': 'Ulaşım noktası',
    'Train': 'Ulaşım noktası',
    'Elevator': 'yer-degil',
    'Street': 'yer-degil',
    'Truck Stop': 'Dinlenme tesisi',
    'Hot Air Balloon Tour Agency': 'Seyahat acentesi',
    'General Travel': 'Ulaşım noktası',

    # ---------------- Alisveris ----------------
    'Retail': 'Alışveriş',
    'Shopping Mall': 'AVM',
    'Outlet Mall': 'AVM',
    'Shopping Plaza': 'Çarşı',
    'Department Store': 'Mağaza',
    'Big Box Store': 'Mağaza',
    'Discount Store': 'Mağaza',
    'Outlet Store': 'Mağaza',
    'Warehouse or Wholesale Store': 'Toptancı',
    'Market': 'Semt pazarı',
    'Farmers Market': 'Semt pazarı',
    'Flea Market': 'Bitpazarı',
    'Floating Market': 'Semt pazarı',
    'Convenience Store': 'Bakkal',
    'Grocery Store': 'Market',
    'Supermarket': 'Süpermarket',
    'Food and Beverage Retail': 'Market',
    'Butcher': 'Kasap',
    'Fish Market': 'Balıkçı',
    'Fruit and Vegetable Store': 'Manav',
    'Kuruyemişçi Shop': 'Kuruyemişçi',
    'Turşucu Shop': 'Turşucu',
    'Herbs and Spices Store': 'Aktar',
    'Candy Store': 'Şekerci',
    'Chocolate Store': 'Şekerci',
    'Cheese Store': 'Şarküteri',
    'Dairy Store': 'Şarküteri',
    'Gourmet Store': 'Şarküteri',
    'Health Food Store': 'Market',
    'Liquor Store': 'Tekel bayii',
    'Fashion Retail': 'Giyim mağazası',
    'Clothing Store': 'Giyim mağazası',
    "Women's Store": 'Giyim mağazası',
    "Men's Store": 'Giyim mağazası',
    "Children's Clothing Store": 'Giyim mağazası',
    'Shoe Store': 'Ayakkabı mağazası',
    'Jewelry Store': 'Kuyumcu',
    'Watch Store': 'Saatçi',
    'Bridal Store': 'Gelinlikçi',
    'Lingerie Store': 'Giyim mağazası',
    'Fashion Accessories Store': 'Aksesuar mağazası',
    'Boutique': 'Butik',
    'Vintage and Thrift Store': 'Butik',
    'Costume Store': 'Giyim mağazası',
    'Leather Goods Store': 'Giyim mağazası',
    'Luggage Store': 'Giyim mağazası',
    'Perfume Store': 'Kozmetik mağazası',
    'Cosmetics Store': 'Kozmetik mağazası',
    'Computers and Electronics Retail': 'Elektronik mağazası',
    'Electronics Store': 'Elektronik mağazası',
    'Mobile Phone Store': 'Telefoncu',
    'Camera Store': 'Elektronik mağazası',
    'Video Games Store': 'Oyuncakçı',
    'Furniture and Home Store': 'Mobilyacı',
    'Carpet Store': 'Halıcı',
    'Lighting Store': 'Ev eşyası mağazası',
    'Mattress Store': 'Mobilyacı',
    'Kitchen Supply Store': 'Ev eşyası mağazası',
    'Automotive Retail': 'Oto galeri',
    'Car Dealership': 'Oto galeri',
    'Motorcycle Dealership': 'Motosiklet bayii',
    'Auto Workshop': 'Oto tamirci',
    'Automotive Shop': 'Oto yedek parça',
    'Construction Supplies Store': 'Yapı marketi',
    'Hardware Store': 'Nalbur',
    'Garden Center': 'Çiçekçi',
    'Flower Store': 'Çiçekçi',
    'Pharmacy': 'Eczane',
    'Drugstore': 'Eczane',
    'Medical Supply Store': 'Medikal malzeme',
    'Supplement Store': 'Medikal malzeme',
    'Eyecare Store': 'Optik',
    'Bookstore': 'Kitapçı',
    'Used Bookstore': 'Kitapçı',
    'Comic Book Store': 'Kitapçı',
    'Stationery Store': 'Kırtasiye',
    'Office Supply Store': 'Kırtasiye',
    'Print Store': 'Matbaa',
    'Newsstand': 'Büfe',
    'Newsagent': 'Büfe',
    'Gift Store': 'Hediyelik eşya',
    'Souvenir Store': 'Hediyelik eşya',
    'Toy Store': 'Oyuncakçı',
    'Hobby Store': 'Hobi mağazası',
    'Arts and Crafts Store': 'Hobi mağazası',
    'Knitting Store': 'Hobi mağazası',
    'Framing Store': 'Hobi mağazası',
    'Music Store': 'Müzik mağazası',
    'Record Store': 'Müzik mağazası',
    'Video Store': 'Müzik mağazası',
    'Sporting Goods Retail': 'Spor mağazası',
    'Bicycle Store': 'Bisikletçi',
    'Fishing Store': 'Spor mağazası',
    'Hunting Supply Store': 'Spor mağazası',
    'Gun Store': 'Spor mağazası',
    'Outdoor Supply Store': 'Spor mağazası',
    'Board Store': 'Spor mağazası',
    'Pet Supplies Store': 'Petshop',
    'Baby Store': 'Bebek mağazası',
    'Textiles Store': 'Kumaşçı',
    'Miscellaneous Store': 'Mağaza',
    'Smoke Shop': 'Tekel bayii',
    'Tobacco Store': 'Tekel bayii',
    'Vape Store': 'Tekel bayii',
    'Adult Store': 'Mağaza',
    'Antique Store': 'Antikacı',
    'Betting Shop': 'Bayi',
    'Mobility Store': 'Medikal malzeme',
    'Pawn Shop': 'Mağaza',
    'Pop-Up Store': 'Mağaza',
    'Party Supply Store': 'Mağaza',
    'Packaging Supply Store': 'Mağaza',
    'Fireworks Store': 'Mağaza',
    'Auction House': 'Mağaza',
    'Duty-free Store': 'Mağaza',
    'Dance Store': 'Mağaza',
    'Swimming Pool Supply Store': 'Mağaza',
    'Vending Machine': 'yer-degil',
    'Financial or Legal Service': 'Kamu hizmeti',
    'Cannabis Store': 'yer-degil',
    'Marijuana Dispensary': 'yer-degil',

    # ---------------- Kamu, egitim, inanc ----------------
    'Community and Government': 'Kamu kurumu',
    'Education': 'Eğitim kurumu',
    # Universite agaci: Foursquare kampusteki her binayi, dersligi,
    # yurdu ayri kayit yapiyor (TR'de 240 bin). Universite yalnizca
    # kurumun kendisi; binalar 'Kampus binasi', yurtlar 'Ogrenci yurdu'.
    'College and University': 'Kampüs binası',
    'College and University > University': 'Üniversite',
    'Community College': 'Üniversite',
    'Medical School': 'Üniversite',
    'Law School': 'Üniversite',
    'College Residence Hall': 'Öğrenci yurdu',
    'Fraternity House': 'Öğrenci yurdu',
    'Sorority House': 'Öğrenci yurdu',
    'College Library': 'Kütüphane',
    'College Gym': 'Spor salonu',
    'College Stadium': 'Stadyum',
    'College Cafeteria': 'Yemekhane',
    'College Auditorium': 'Konferans salonu',
    'College Bookstore': 'Kitapçı',
    'College Theater': 'Tiyatro',
    'Airport > Plane': 'yer-degil',
    'Plane': 'yer-degil',
    'Beach Bar': 'Plaj barı',
    'Primary and Secondary School': 'Okul',
    'Private School': 'Okul',
    'Nursery School': 'Anaokulu',
    'Preschool': 'Anaokulu',
    'Language School': 'Dil okulu',
    'Driving School': 'Sürücü kursu',
    'Music School': 'Müzik okulu',
    'Adult Education': 'Eğitim kurumu',
    'Trade School': 'Eğitim kurumu',
    'Religious School': 'Eğitim kurumu',
    'Flight School': 'Eğitim kurumu',
    'Government Building': 'Kamu kurumu',
    'Courthouse': 'Adliye',
    'City Hall': 'Belediye',
    'Town Hall': 'Belediye',
    'Capitol Building': 'Kamu kurumu',
    'Law Enforcement and Public Safety': 'Karakol',
    'Military': 'Askeri alan',
    'Post Office': 'Postane',
    'Embassy or Consulate': 'Konsolosluk',
    'Spiritual Center': 'İbadet yeri',
    'Mosque': 'Cami',
    'Shrine': 'Türbe',
    'Prayer Room': 'Mescit',
    'Church': 'Kilise',
    'Synagogue': 'Sinagog',
    'Library': 'Kütüphane',
    'Community Center': 'Toplum merkezi',
    'Cultural Center': 'Kültür merkezi',
    'Social Club': 'Dernek',
    'Organization': 'Dernek',
    'Non-Profit Organization': 'Dernek',
    'Club House': 'Dernek',
    'Cemetery': 'Mezarlık',
    'Assisted Living': 'Huzurevi',
    'Retirement Home': 'Huzurevi',
    'Rehabilitation Center': 'Sağlık merkezi',
    'Addiction Treatment Center': 'Sağlık merkezi',
    'Animal Shelter': 'Hayvan barınağı',
    'Observatory': 'Müze',
    'Summer Camp': 'Kamp alanı',
    'Prison': 'Kamu kurumu',
    'Public Bathroom': 'yer-degil',
    'Public and Social Service': 'Kamu hizmeti',
    'Polling Place': 'Kamu kurumu',
    'Utility Company': 'Kamu hizmeti',
    'Trailer Park': 'Kamp alanı',
    'Dump': 'yer-degil',
    'Homeless Shelter': 'Kamu hizmeti',
    'Housing Authority': 'Kamu kurumu',
    'Disabled Persons Service': 'Kamu hizmeti',
    'Domestic Abuse Treatment Center': 'Kamu hizmeti',
    'Senior Citizen Service': 'Kamu hizmeti',
    'Government Lobbyist': 'Kamu kurumu',

    # ---------------- Saglik ----------------
    'Health and Medicine': 'Sağlık merkezi',
    'Hospital': 'Hastane',
    'Hospital Unit': 'Hastane',
    'Emergency Service': 'Hastane',
    'Emergency Room': 'Hastane',
    'Urgent Care Center': 'Sağlık merkezi',
    'Medical Center': 'Sağlık merkezi',
    'Healthcare Clinic': 'Sağlık merkezi',
    'Physician': 'Doktor',
    "Doctor's Office": 'Doktor',
    'Dentist': 'Diş kliniği',
    'Veterinarian': 'Veteriner',
    'Medical Lab': 'Laboratuvar',
    'Mental Health Service': 'Psikolog',
    'Mental Health Clinic': 'Psikolog',
    'Physical Therapy Clinic': 'Fizik tedavi',
    'Alternative Medicine Clinic': 'Sağlık merkezi',
    'Acupuncture Clinic': 'Sağlık merkezi',
    'Chiropractor': 'Sağlık merkezi',
    'Optometrist': 'Optik',
    'Nutritionist': 'Diyetisyen',
    'Weight Loss Center': 'Diyetisyen',
    'Maternity Clinic': 'Sağlık merkezi',
    "Women's Health Clinic": 'Sağlık merkezi',
    'Home Health Care Service': 'Sağlık merkezi',
    'Other Healthcare Professional': 'Sağlık merkezi',
    'Blood Bank': 'Sağlık merkezi',
    'Nursing Home': 'Huzurevi',
    'Hospice': 'Sağlık merkezi',
    'Podiatrist': 'Sağlık merkezi',
    'Sports Medicine Clinic': 'Sağlık merkezi',
    'AIDS Resource': 'Sağlık merkezi',
    'Assisted Living Service': 'Huzurevi',
    'Nurse': 'Sağlık merkezi',

    # ---------------- Is ve hizmet ----------------
    'Business and Professional Services': 'İşletme',
    'Health and Beauty Service': 'Güzellik salonu',
    'Hair Salon': 'Kuaför',
    'Barbershop': 'Berber',
    'Nail Salon': 'Tırnak bakımı',
    'Spa': 'Spa',
    'Massage Clinic': 'Spa',
    'Bath House': 'Hamam',
    'Tanning Salon': 'Güzellik salonu',
    'Tattoo Parlor': 'Dövme stüdyosu',
    'Dry Cleaner': 'Kuru temizleme',
    'Laundry Service': 'Çamaşırhane',
    'Laundromat': 'Çamaşırhane',
    'Automotive Service': 'Oto servis',
    'Automotive Repair Shop': 'Oto tamirci',
    'Car Wash and Detail': 'Oto yıkama',
    'Tire Repair Shop': 'Lastikçi',
    'Vehicle Inspection Station': 'Araç muayene',
    'Financial Service': 'Banka',
    'Banking and Finance': 'Banka',
    'ATM': 'ATM',
    'Currency Exchange': 'Döviz bürosu',
    'Insurance Agency': 'Sigorta acentesi',
    'Accounting and Bookkeeping Service': 'Muhasebeci',
    'Check Cashing Service': 'Banka',
    'Legal Service': 'Avukat',
    'Law Office': 'Avukat',
    'Notary': 'Noter',
    'Real Estate Service': 'Emlakçı',
    'Real Estate Agency': 'Emlakçı',
    'Business Center': 'İş merkezi',
    'Business Service': 'İşletme',
    'Design Studio': 'Tasarım stüdyosu',
    'Art Studio': 'Sanat atölyesi',
    'Photography Service': 'Fotoğrafçı',
    'Photography Lab': 'Fotoğrafçı',
    'Photography Studio': 'Fotoğrafçı',
    'Advertising Agency': 'Reklam ajansı',
    'Wedding Hall': 'Düğün salonu',
    'Ballroom': 'Düğün salonu',
    'Event Space': 'Etkinlik alanı',
    'Outdoor Event Space': 'Etkinlik alanı',
    'Event Service': 'Organizasyon',
    'Convention Center': 'Kongre merkezi',
    'Conference Room': 'Kongre merkezi',
    'Auditorium': 'Konferans salonu',
    'Tailor': 'Terzi',
    'Shoe Repair Service': 'Ayakkabı tamircisi',
    'Locksmith': 'Çilingir',
    'Repair Service': 'Tamirci',
    'Computer Repair Service': 'Bilgisayar tamircisi',
    'Home Improvement Service': 'Tadilat',
    'Home Service': 'Tadilat',
    'Construction': 'İnşaat firması',
    'Architecture Firm': 'Mimarlık ofisi',
    'Engineer': 'Mühendislik ofisi',
    'Technology Business': 'Teknoloji şirketi',
    'IT Service': 'Teknoloji şirketi',
    'Software Company': 'Teknoloji şirketi',
    'Telecommunication Service': 'Teknoloji şirketi',
    'Mobile Company': 'Teknoloji şirketi',
    'Storage Facility': 'Depo',
    'Warehouse': 'Depo',
    'Distribution Center': 'Depo',
    'Shipping, Freight, and Material Transportation Service': 'Kargo',
    'Industrial Estate': 'Sanayi sitesi',
    'Machine Shop': 'Sanayi sitesi',
    'Welding Service': 'Sanayi sitesi',
    'Metals Supplier': 'Sanayi sitesi',
    'Manufacturer': 'Sanayi sitesi',
    'Industrial Equipment Supplier': 'Sanayi sitesi',
    'Electrical Equipment Supplier': 'Sanayi sitesi',
    'Automation and Control System': 'Sanayi sitesi',
    'Plastics Supplier': 'Sanayi sitesi',
    'Wholesaler': 'Toptancı',
    'Import and Export Service': 'Toptancı',
    'Recycling Facility': 'yer-degil',
    'Waste Management Service': 'yer-degil',
    'Power Plant': 'yer-degil',
    'Water Treatment Service': 'yer-degil',
    'Salvage Yard': 'yer-degil',
    'Research Laboratory': 'Laboratuvar',
    'Laboratory': 'Laboratuvar',
    'Research Station': 'Laboratuvar',
    'TV Station': 'Medya',
    'Radio Station': 'Medya',
    'Media Agency': 'Medya',
    'Film Studio': 'Medya',
    'Recording Studio': 'Stüdyo',
    'Audiovisual Service': 'Medya',
    'Publisher': 'Medya',
    'Print, TV, Radio and Outdoor Advertising Service': 'Reklam ajansı',
    'Entertainment Service': 'Organizasyon',
    'Entertainment Agency': 'Organizasyon',
    'Pet Service': 'Pet kuaförü',
    'Child Care Service': 'Kreş',
    'Daycare': 'Kreş',
    'Tutoring Service': 'Eğitim kurumu',
    'Employment Agency': 'İşletme',
    'Funeral Home': 'Cenaze hizmetleri',
    'Rental Service': 'Kiralama',
    'Equipment Rental Service': 'Kiralama',
    'Food and Beverage Service': 'Catering',
    'Lottery Retailer': 'Bayi',
    'Security and Safety': 'İşletme',
    'Management Consultant': 'Danışmanlık',
    'Market Research and Consulting Service': 'Danışmanlık',
    'Appraiser': 'Danışmanlık',
    'Agriculture and Forestry Service': 'Çiftlik',
    'Renewable Energy Service': 'İşletme',
    'Creative Service': 'Tasarım stüdyosu',
    'Refrigeration and Ice Supplier': 'Toptancı',
    'Logging Service': 'İşletme',
    'Online Advertising Service': 'Reklam ajansı',
    'Paper Supplier': 'Toptancı',
    'Search Engine Marketing and Optimization Service': 'Reklam ajansı',
    'Writing, Copywriting and Technical Writing Service': 'İşletme',
    'Art Restoration Service': 'Sanat atölyesi',
    'Career Counselor': 'Danışmanlık',
    'Chemicals and Gasses Manufacturer': 'Sanayi sitesi',
    'Direct Mail and Email Marketing Service': 'Reklam ajansı',
    'Geological Service': 'İşletme',
    'Human Resources Agency': 'İşletme',
    'Leather Supplier': 'Toptancı',
    'Petroleum Supplier': 'Toptancı',
    'Promotional Item Service': 'Reklam ajansı',
    'Public Relations Firm': 'Reklam ajansı',
    'Rubber Supplier': 'Toptancı',
    'Scientific Equipment Supplier': 'Toptancı',
    'Translation Service': 'İşletme',
}

# Bu tur adlari kesfette "sosyal" sayilmaz; yalnizca aramada bulunur.
# (lib/mekan.ts SOSYAL_TURLER listesiyle birlikte okunur.)


def tur_bul(etiket: str | None) -> str | None:
    """Foursquare etiketini ("A > B > C") Turkce ture cevirir.

    En ozgul parcadan ust parcaya dogru bakar. Etiket yoksa None doner
    (yukleyici o kaydi 'Mekan' turu ile alir - kategorisiz kayit
    Bursa'da ~%1).
    """
    if not etiket:
        return None
    parcalar = [p.strip() for p in etiket.split('>')]
    for i in range(len(parcalar), 0, -1):
        tam_yol = ' > '.join(parcalar[:i])
        if tam_yol in ESLEME:
            return ESLEME[tam_yol]
        # Son iki parca ("College and University > University") da bir anahtar olabilir.
        if i >= 2 and ' > '.join(parcalar[i - 2:i]) in ESLEME:
            return ESLEME[' > '.join(parcalar[i - 2:i])]
        if parcalar[i - 1] in ESLEME:
            return ESLEME[parcalar[i - 1]]
    return None
